window.artifactData = [
  {
    "SetName": "Aethercore",
    "SetId": "Mp",
    "IndividualBonus": null,
    "PerPieceBonus": "MP: <color=#AAFF00FF>+10% per level</color>",
    "PerRefineBonus": "MP: <color=#AAFF00FF>+0.25% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nMP:",
    "Source": "Scroll - Flora\nJewel - Fungi\nJewel - Frost Glimmer\nRune - Shroom\nRelic - Shroom\nRelic - Nautilus\nRune - Sea Blossom\nRune - Conch\nScroll - Conch\nJewel - Hermit\nRelic - Hermit\nScroll - Toadstool",
    "Droprate": "400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%",
    "Location": "Mystic Lake 1\nLake Field\nMystic Lake 1\nLake Field\nLake Field\nMystic Lake 1\nMystic Lake 1\nMystic Lake 2\nMystic Lake 2\nMystic Lake 2\nMystic Lake 2\nLake Field",
    "SpriteId": "T_Artifact_Aethercore_0\nT_Artifact_Aethercore_1\nT_Artifact_Aethercore_2\nT_Artifact_Aethercore_3",
    "SourceLevel": 26
  },
  {
    "SetName": "Arcane Elementalist",
    "SetId": "Wizard_4",
    "IndividualBonus": "<color=#FF9700FF>Casting cannot be interrupted.</color>\nGrants <color=#AAFF00FF> Free Cast</color>\nCast Speed: <color=#AAFF00FF>+1% per level</color>\nMP Regen: <color=#AAFF00FF>+2% per level</color>",
    "PerPieceBonus": null,
    "PerRefineBonus": null,
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+3</color>\n<color=#B2B2B2FF>Four attunements share one page, arguing until they become a single harmony.</color>\n<color=#FF9700FF><color=#AAFF00FF>Elemental Attunement</color> replaces Fire Attunement</color>\n<color=#FF9700FF><color=#AAFF00FF>Elemental Attunement</color> replaces Water Attunement</color>\n<color=#FF9700FF><color=#AAFF00FF>Elemental Attunement</color> replaces Wind Attunement</color>\n<color=#FF9700FF><color=#AAFF00FF>Elemental Attunement</color> replaces Earth Attunement</color>\n-----------------------------------------------------\n<color=#C37CFFFF>Elemental Attunement</color>\nFire Damage: <color=#AAFF00FF>+5% per level</color>\nWater Damage: <color=#AAFF00FF>+5% per level</color>\nWind Damage: <color=#AAFF00FF>+5% per level</color>\nEarth Damage: <color=#AAFF00FF>+5% per level</color>\n<color=#B2B2B2FF>Elemental sigils raise matching barriers whenever avatar power gathers around the caster.</color>\nApply <color=#AAFF00FF>Arcane Barrier</color> for <color=#AAFF00FF>1 seconds</color> when applying <color=#AAFF00FF>Fire Barrier</color>\nApply <color=#AAFF00FF>Arcane Barrier</color> for <color=#AAFF00FF>1 seconds</color> when applying <color=#AAFF00FF>Water Barrier</color>\nApply <color=#AAFF00FF>Arcane Barrier</color> for <color=#AAFF00FF>1 seconds</color> when applying <color=#AAFF00FF>Wind Barrier</color>\nApply <color=#AAFF00FF>Arcane Barrier</color> for <color=#AAFF00FF>1 seconds</color> when applying <color=#AAFF00FF>Earth Barrier</color>\n-----------------------------------------------------\n<color=#C37CFFFF>Arcane Barrier</color>\nFire Damage: <color=#AAFF00FF>+10%</color>\nFire Resistance: <color=#AAFF00FF>+10%</color>\nDuration: <color=#AAFF00FF>1 seconds</color>\n-----------------------------------------------------\n<color=#C37CFFFF>Arcane Barrier</color>\nWater Damage: <color=#AAFF00FF>+10%</color>\nWater Resistance: <color=#AAFF00FF>+10%</color>\nDuration: <color=#AAFF00FF>1 seconds</color>\n-----------------------------------------------------\n<color=#C37CFFFF>Arcane Barrier</color>\nWind Damage: <color=#AAFF00FF>+10%</color>\nWind Resistance: <color=#AAFF00FF>+10%</color>\nDuration: <color=#AAFF00FF>1 seconds</color>\n-----------------------------------------------------\n<color=#C37CFFFF>Arcane Barrier</color>\nEarth Damage: <color=#AAFF00FF>+10%</color>\nEarth Resistance: <color=#AAFF00FF>+10%</color>\nDuration: <color=#AAFF00FF>1 seconds</color>\nStr:",
    "Source": "Crafted",
    "Droprate": null,
    "Location": "Mystic Lake 2",
    "SpriteId": "artifacts-wizard-1_0\nartifacts-wizard-1_1\nartifacts-wizard-1_2\nartifacts-wizard-1_3"
  },
  {
    "SetName": "Arcanum",
    "SetId": "Magic",
    "IndividualBonus": null,
    "PerPieceBonus": "Magic Damage: <color=#AAFF00FF>+3% per level</color>",
    "PerRefineBonus": "Magic Damage: <color=#AAFF00FF>+0.125% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nMagic Damage: <color=#AAFF00FF>+3%</color>",
    "Source": "Jewel - Digger\nRune - Sparkit\nRelic - Hound\nScroll - Pup\nRune - Frost Wisp\nJewel - Lightning Wisp\nScroll - Fire Wisp\nRelic - Earth Wisp",
    "Droprate": "500.0%\n500.0%\n500.0%\n500.0%\n500.0%\n500.0%\n500.0%\n500.0%",
    "Location": "Forest Field 2\nForest Field 2\nForest Field 2\nForest Field 2\nForest Field 1\nForest Field 1\nForest Field 1\nForest Field 1",
    "SpriteId": "T_Artifact_Arcanum_0\nT_Artifact_Arcanum_1\nT_Artifact_Arcanum_2\nT_Artifact_Arcanum_3",
    "SourceLevel": 11
  },
  {
    "SetName": "Arcanum Verge",
    "SetId": "Cost",
    "IndividualBonus": null,
    "PerPieceBonus": "MP Cost: <color=#AAFF00FF>-10% per level</color>",
    "PerRefineBonus": "MP Cost: <color=#AAFF00FF>-0.25% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nStr:",
    "Source": "Rune - Bomb\nRelic - Shadow Wyvern\nScroll - Phantom\nRune - Soul Mage\nJewel - Spook",
    "Droprate": "300.0%\n300.0%\n300.0%\n300.0%\n300.0%",
    "Location": "Sanctum of Light\nSanctum of Light\nSanctum of Light\nSanctum of Light\nSanctum of Light",
    "SpriteId": "T_Artifact_ArcanumVerge_0\nT_Artifact_ArcanumVerge_1\nT_Artifact_ArcanumVerge_2\nT_Artifact_ArcanumVerge_3",
    "SourceLevel": 81
  },
  {
    "SetName": "Bastion",
    "SetId": "Bastion",
    "IndividualBonus": "<color=#FF9700FF>Immune to knockback.</color>\n<color=#FF9700FF>Immune to flinching from damage.</color>\n<color=#FF9700FF>Casting cannot be interrupted.</color>\n<color=#FF9700FF>Immune to reflected damage.</color>",
    "PerPieceBonus": null,
    "PerRefineBonus": null,
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+5</color>\nHP: <color=#AAFF00FF>+10%</color>\nMP: <color=#AAFF00FF>+10%</color>",
    "Source": "Rune - Bluefin\nRelic - Aqua Merling\nRune - Roseate Merling\nJewel - Canary Merling\nScroll - Sapphire Merman\nRelic - Coral Merman\nRune - Topaz Merman\nJewel - Rosetail\nScroll - Goldtail\nRune - Azure Squid\nJewel - Amber Squid\nScroll - Plum Squid\nScroll - Amber Cuttlefish\nRelic - Violet Cuttlefish\nRune - Pearl Cuttlefish\nJewel - Bull Shark\nRelic - Squidling",
    "Droprate": "200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%",
    "Location": "Sunken Depths\nSunken Depths\nSunken Depths\nSunken Depths\nSunken Depths\nSunken Depths\nSunken Depths\nSunken Depths\nSunken Depths\nSunken Depths\nSunken Depths\nSunken Depths\nSunken Depths\nSunken Depths\nSunken Depths\nSunken Depths\nSunken Depths",
    "SpriteId": "T_Artifact_Bastion_0\nT_Artifact_Bastion_1\nT_Artifact_Bastion_2\nT_Artifact_Bastion_3",
    "SourceLevel": 101
  },
  {
    "SetName": "Blitzcore",
    "SetId": "Auto",
    "IndividualBonus": null,
    "PerPieceBonus": "Attack Speed: <color=#AAFF00FF>+3% per level</color>",
    "PerRefineBonus": "Attack Speed: <color=#AAFF00FF>+0.25% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nAuto-Attack Chain: <color=#AAFF00FF>+2</color>\nAttack Speed: <color=#AAFF00FF>+3%</color>",
    "Source": "Rune - Bat\nJewel - Crawler\nRelic - Horror\nScroll - Lurker\nJewel - Viper\nRelic - Adder\nJewel - Spider\nScroll - Arachne\nRune - Widow\nRune - Nosferatu",
    "Droprate": "400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%",
    "Location": "Forgotten Depths 1\nForgotten Depths 1\nForgotten Depths 2\nForgotten Depths 1\nForgotten Depths 2\nForgotten Depths 1\nForgotten Depths 1\nForgotten Depths 2\nForgotten Depths 1\nForgotten Depths 2",
    "SpriteId": "T_Artifact_Blitzcore_0\nT_Artifact_Blitzcore_1\nT_Artifact_Blitzcore_2\nT_Artifact_Blitzcore_3",
    "SourceLevel": 41
  },
  {
    "SetName": "Bloodbind",
    "SetId": "Leech",
    "IndividualBonus": null,
    "PerPieceBonus": "Health on Kill: <color=#AAFF00FF>+25 per level</color>\nMana on Kill: <color=#AAFF00FF>+5 per level</color>",
    "PerRefineBonus": "Health on Kill: <color=#AAFF00FF>+5 per level</color>\nMana on Kill: <color=#AAFF00FF>+1 per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nStr:\nStr:",
    "Source": "Rune - Azure Gazer\nJewel - Jade Gazer\nScroll - Ruby Gazer\nRelic - Skeleton\nJewel - Wolf\nRelic - Wolf\nRune - Wolf Cub\nScroll - Wolf Cub",
    "Droprate": "500.0%\n500.0%\n500.0%\n500.0%\n400.0%\n400.0%\n400.0%\n400.0%",
    "Location": "Festering Woods 1\nFestering Woods 1\nFestering Woods 1\nFestering Woods 1\nFestering Woods 2\nFestering Woods 2\nFestering Woods 2\nFestering Woods 2",
    "SpriteId": "T_Artifact_Bloodbind_0\nT_Artifact_Bloodbind_1\nT_Artifact_Bloodbind_2\nT_Artifact_Bloodbind_3",
    "SourceLevel": 21
  },
  {
    "SetName": "Bloodfury",
    "SetId": "Berserker_1",
    "IndividualBonus": "Execute Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nCyclone Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nAxe Throw Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nDark Claw Damage: <color=#AAFF00FF>+5% + 2% per level</color>",
    "PerPieceBonus": null,
    "PerRefineBonus": null,
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+3</color>",
    "Source": "Crafted",
    "Droprate": null,
    "Location": "Windy Desert",
    "SpriteId": "artifacts-berserker-1_0\nartifacts-berserker-1_1\nartifacts-berserker-1_2\nartifacts-berserker-1_3"
  },
  {
    "SetName": "Corporeal",
    "SetId": "Corporeal",
    "IndividualBonus": null,
    "PerPieceBonus": "Poison Damage: <color=#AAFF00FF>+3% per level</color>\nUndead Damage: <color=#AAFF00FF>+3% per level</color>\nShadow Damage: <color=#AAFF00FF>+3% per level</color>\nHoly Damage: <color=#AAFF00FF>+3% per level</color>",
    "PerRefineBonus": "Poison Damage: <color=#AAFF00FF>+0.125% per level</color>\nUndead Damage: <color=#AAFF00FF>+0.125% per level</color>\nShadow Damage: <color=#AAFF00FF>+0.125% per level</color>\nHoly Damage: <color=#AAFF00FF>+0.125% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nPoison Damage: <color=#AAFF00FF>+3%</color>\nUndead Damage: <color=#AAFF00FF>+3%</color>\nShadow Damage: <color=#AAFF00FF>+3%</color>\nHoly Damage: <color=#AAFF00FF>+3%</color>",
    "Source": "Jewel - Boxy Robot\nRelic - Delivery Robot\nScroll - Gripper Robot\nJewel - Nose Robot\nRelic - Nozzle Robot\nRune - Razor Robot\nJewel - Shell Robot\nRune - Snout Robot\nScroll - Spider Robot\nRune - Spiderling Robot\nScroll - Spike Robot",
    "Droprate": "100.0%\n100.0%\n100.0%\n100.0%\n100.0%\n100.0%\n100.0%\n100.0%\n100.0%\n100.0%\n100.0%",
    "Location": "The Forge\nThe Forge\nThe Forge\nThe Forge\nThe Forge\nThe Forge\nThe Forge\nThe Forge\nThe Forge\nThe Forge\nThe Forge",
    "SpriteId": "T_Artifact_Corporeal_0\nT_Artifact_Corporeal_1\nT_Artifact_Corporeal_2\nT_Artifact_Corporeal_3",
    "SourceLevel": 126
  },
  {
    "SetName": "Eternis",
    "SetId": "Eternis",
    "IndividualBonus": null,
    "PerPieceBonus": null,
    "PerRefineBonus": null,
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+5</color>\nGrants <color=#AAFF00FF>Lv.5 Heal</color>\nGrants <color=#AAFF00FF>Lv.5 Haste</color>\nHP: <color=#AAFF00FF>+10%</color>\nMP: <color=#AAFF00FF>+10%</color>\nATK: <color=#AAFF00FF>+5%</color>\nMATK: <color=#AAFF00FF>+5%</color>",
    "Source": "Rune - Voidgazer\nScroll - Chompbloom\nRelic - Cindermaw\nJewel - Stormcoil",
    "Droprate": "100.0%\n100.0%\n100.0%\n100.0%",
    "Location": "Night Garden\nNight Garden\nNight Garden\nNight Garden",
    "SpriteId": "T_Artifact_Eternis_0\nT_Artifact_Eternis_1\nT_Artifact_Eternis_2\nT_Artifact_Eternis_3",
    "SourceLevel": 126
  },
  {
    "SetName": "Fateweave",
    "SetId": "Weaver_1",
    "IndividualBonus": "Firebolt Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nIcebolt Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nThunderbolt Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nEarthbolt Damage: <color=#AAFF00FF>+5% + 2% per level</color>",
    "PerPieceBonus": null,
    "PerRefineBonus": null,
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+3</color>",
    "Source": "Crafted",
    "Droprate": null,
    "Location": "Starfall Tundra",
    "SpriteId": "artifacts-weaver-1_0\nartifacts-weaver-1_1\nartifacts-weaver-1_2\nartifacts-weaver-1_3"
  },
  {
    "SetName": "Frozen Dominion",
    "SetId": "Wizard_2",
    "IndividualBonus": "Blizzard Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nIce Shard Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nFrozen Ground Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nMP Regen: <color=#AAFF00FF>+2% per level</color>",
    "PerPieceBonus": null,
    "PerRefineBonus": null,
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+3</color>\n<color=#B2B2B2FF>Frozen lasts longer. Blizzard and Ice Shard can create Frozen Ground.</color>\nStatus Duration: <color=#AAFF00FF>+30%</color>\n<color=#FF9700FF>Blizzard: <color=#AAFF00FF>Remove Knockback</color></color>\n<color=#FF9700FF>Blizzard autocasts Frozen Ground</color>\nAutocast <color=#AAFF00FF>Frozen Ground</color> with <color=#AAFF00FF>Ice Shard</color> hits\n-----------------------------------------------------\n<color=#00E2FFFF>Frozen Ground</color>\n<color=#B2B2B2FF>Freeze the ground beneath enemies, damaging them repeatedly with a chance to leave them Frozen.</color>\nType: <color=#00E2FFFF>Magic</color>\nElement: <sprite name=water> <color=#79D7FDFF>Water</color>\nDamage: <color=#AAFF00FF>500% MATK</color>\nHits: <color=#AAFF00FF>2</color>\nDuration: <color=#AAFF00FF>2 seconds</color>\nMaximum Instances: <color=#AAFF00FF>3</color>\nCost: <color=#AAFF00FF>20 + 10 mana per level</color>\n-----------------------------------------------------\n<color=#FFD900FF>Status Effects</color>\n<color=#C37CFFFF>Frozen</color>\n<color=#FF0073FF>Cannot attack or move.</color>\n<color=#FF0073FF>Flee is disabled.</color>\n<color=#FF0073FF>Block is disabled.</color>\nDuration: <color=#AAFF00FF>10 seconds</color>\nChance: <color=#AAFF00FF>5% per level</color>\nStr:",
    "Source": "Crafted",
    "Droprate": null,
    "Location": "Mystic Lake 2",
    "SpriteId": "artifacts-wizard-1_0\nartifacts-wizard-1_1\nartifacts-wizard-1_2\nartifacts-wizard-1_3"
  },
  {
    "SetName": "Furybrand",
    "SetId": "Crit",
    "IndividualBonus": null,
    "PerPieceBonus": "Crit: <color=#AAFF00FF>+5 per level</color>",
    "PerRefineBonus": "CRIT Damage: <color=#AAFF00FF>+0.25% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nCRIT Damage: <color=#AAFF00FF>+5%</color>\nStr:",
    "Source": "Jewel - Flame Drake\nJewel - Inferno Wyvern\nScroll - Spark Drake\nRelic - Elder Fire\nRune - Ember\nRune - Fire Mage\nRelic - Blaze\nRelic - Magma Golem\nRune - Imp\nJewel - Gremlin\nScroll - Shade\nScroll - Nightfiend",
    "Droprate": "200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%",
    "Location": "Demon's Maw\nDemon's Maw\nDemon's Maw\nDemon's Maw\nDemon's Maw\nDemon's Maw\nDemon's Maw\nDemon's Maw\nDemon's Maw\nDemon's Maw\nDemon's Maw\nDemon's Maw",
    "SpriteId": "T_Artifact_Furybrand_0\nT_Artifact_Furybrand_1\nT_Artifact_Furybrand_2\nT_Artifact_Furybrand_3",
    "SourceLevel": 96
  },
  {
    "SetName": "Hawkeye",
    "SetId": "Hit",
    "IndividualBonus": null,
    "PerPieceBonus": "Hit: <color=#AAFF00FF>+15 per level</color>",
    "PerRefineBonus": "Hit: <color=#AAFF00FF>+1 per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nTotal HIT: <color=#AAFF00FF>+10%</color>",
    "Source": "Jewel - Sharkling\nJewel - Shark Buccaneer\nRune - Turtle Baby\nScroll - Azure Terrapin\nRelic - Verdant Terrapin\nRune - Crimson Terrapin",
    "Droprate": "400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%",
    "Location": "Stormreef Isle\nStormreef Isle\nStormreef Isle\nStormreef Isle\nStormreef Isle\nStormreef Isle",
    "SpriteId": "T_Artifact_Hawkeye_0\nT_Artifact_Hawkeye_1\nT_Artifact_Hawkeye_2\nT_Artifact_Hawkeye_3",
    "SourceLevel": 61
  },
  {
    "SetName": "Hexbrand",
    "SetId": "Hexbrand",
    "IndividualBonus": null,
    "PerPieceBonus": "Status Damage: <color=#AAFF00FF>+5% per level</color>",
    "PerRefineBonus": "Status Damage: <color=#AAFF00FF>+0.25% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nStatus Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Jewel - Chomproot\nRelic - Voidspawn\nJewel - Cinderspike\nScroll - Chompcap\nScroll - Cinderwheel\nRune - Hawker\nRune - Grave Worm\nJewel - Bluebottle\nRune - Stormjelly\nScroll - Bloodsucker\nJewel - Snapvine\nRelic - Vinecrawler\nScroll - Jellooze\nRune - Oozelord\nRune - Stormstinger\nRelic - Worm",
    "Droprate": "300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%",
    "Location": "Dark Forest\nDark Forest\nDark Forest\nDark Forest\nDark Forest\nSwamp Wilderness\nSwamp Wilderness\nSwamp Wilderness\nDark Forest\nSwamp Wilderness\nSwamp Wilderness\nSwamp Wilderness\nSwamp Wilderness\nSwamp Wilderness\nDark Forest\nSwamp Wilderness",
    "SpriteId": "T_Artifact_Hexbrand_0\nT_Artifact_Hexbrand_1\nT_Artifact_Hexbrand_2\nT_Artifact_Hexbrand_3",
    "SourceLevel": 66
  },
  {
    "SetName": "Lifebloom",
    "SetId": "Healing",
    "IndividualBonus": null,
    "PerPieceBonus": "Healing: <color=#AAFF00FF>+5% per level</color>",
    "PerRefineBonus": "Healing: <color=#AAFF00FF>+0.25% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nHealing:",
    "Source": "Rune - Angel\nRune - Archangel\nScroll - Dusk Drake\nJewel - Night Drake\nJewel - Ghost\nScroll - Banshee\nRelic - Soul",
    "Droprate": "300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%",
    "Location": "Sanctum of Light\nSanctum of Light\nSanctum of Light\nSanctum of Light\nSanctum of Light\nSanctum of Light\nSanctum of Light",
    "SpriteId": "T_Artifact_LifeBloom_0\nT_Artifact_LifeBloom_1\nT_Artifact_LifeBloom_2\nT_Artifact_LifeBloom_3",
    "SourceLevel": 76
  },
  {
    "SetName": "Meteoric Cataclysm",
    "SetId": "Wizard_3",
    "IndividualBonus": "Meteor Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nFire Pillar Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nCombustion Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nMATK: <color=#AAFF00FF>+1% per level</color>",
    "PerPieceBonus": null,
    "PerRefineBonus": null,
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+3</color>\n<color=#B2B2B2FF>Burning or Stun triggers Combustion. Fire Pillar gains more instances, and Meteor becomes Meteor Storm.</color>\nAutocast <color=#AAFF00FF>Combustion</color> when applying <color=#AAFF00FF>Burning</color>\nAutocast <color=#AAFF00FF>Combustion</color> when applying <color=#AAFF00FF>Stun</color>\nFire Pillar Maximum Instances: <color=#AAFF00FF>+2</color>\n<color=#FF9700FF><color=#AAFF00FF>Meteor Storm</color> replaces Meteor</color>\n-----------------------------------------------------\n<color=#C37CFFFF>Burning</color>\n<color=#FF9700FF>Drains hp over time</color>\n<color=#FF9700FF>Drains 3% HP per second</color>\n<color=#FF9700FF>Stackable</color>\n-----------------------------------------------------\n<color=#C37CFFFF>Stun</color>\n<color=#FF0073FF>Cannot attack or move.</color>\n<color=#FF0073FF>Flee is disabled.</color>\n<color=#FF0073FF>Block is disabled.</color>\n-----------------------------------------------------\n<color=#00E2FFFF>Meteor Storm</color>\n<color=#B2B2B2FF>Call down a lingering storm of meteors, raining Fire damage across the targeted area.</color>\n\nElement: <sprite name=fire> <color=#FF7026FF>Fire</color>\nDuration: <color=#AAFF00FF>5 seconds</color>\nArea: <color=#AAFF00FF>7</color>\n-----------------------------------------------------\nCast Range: <color=#AAFF00FF>12</color>\nCast Time: <color=#AAFF00FF>1 seconds per level</color>\nCooldown: <color=#AAFF00FF>7 seconds</color>\nCost: <color=#AAFF00FF>80 + 40 mana per level</color>",
    "Source": "Crafted",
    "Droprate": null,
    "Location": "Mystic Lake 2",
    "SpriteId": "artifacts-wizard-1_0\nartifacts-wizard-1_1\nartifacts-wizard-1_2\nartifacts-wizard-1_3"
  },
  {
    "SetName": "Nullmark",
    "SetId": "Immune",
    "IndividualBonus": "Resistance to Blind: <color=#AAFF00FF>+50%</color>\nResistance to Silence: <color=#AAFF00FF>+50%</color>\nResistance to Poison: <color=#AAFF00FF>+50%</color>\nResistance to Bleeding: <color=#AAFF00FF>+50%</color>",
    "PerPieceBonus": null,
    "PerRefineBonus": "Resistance to Stun: <color=#AAFF00FF>+2.5% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nResistance to Slow: <color=#AAFF00FF>+50%</color>",
    "Source": "Rune - Nightbloom\nScroll - Deathblossom\nRune - Venom Bud\nJewel - Elder Lightning\nJewel - Miasma\nRelic - Maggot\nScroll - Grub",
    "Droprate": "300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%",
    "Location": "Underground Cavern\nUnderground Cavern\nUnderground Cavern\nUnderground Cavern\nUnderground Cavern\nUnderground Cavern\nUnderground Cavern",
    "SpriteId": "T_Artifact_Nullmark_0\nT_Artifact_Nullmark_1\nT_Artifact_Nullmark_4\nT_Artifact_Nullmark_5",
    "SourceLevel": 86
  },
  {
    "SetName": "Oathbound",
    "SetId": "Oathbound",
    "IndividualBonus": null,
    "PerPieceBonus": "Buff Duration: <color=#AAFF00FF>+10% per level</color>",
    "PerRefineBonus": "Buff Duration: <color=#AAFF00FF>+0.25% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nBuff Duration:",
    "Source": "Rune - Little Star\nJewel - Starry\nRune - Twinkle\nScroll - Ice Bear\nRelic - Festive Bear\nJewel - Ice Golem\nScroll - Shadow Golem\nRelic - Starflake\nRune - Vanilla Ice\nJewel - Shadow Ice\nJewel - Ice Baby\nScroll - Festive Baby\nRelic - Ice Cube\nRune - Shadow Cube",
    "Droprate": "100.0%\n200.0%\n100.0%\n100.0%\n100.0%\n200.0%\n200.0%\n100.0%\n100.0%\n100.0%\n100.0%\n100.0%\n200.0%\n200.0%",
    "Location": "Starfall Tundra\nAncient Ruins\nStarfall Tundra\nStarfall Tundra\nStarfall Tundra\nAncient Ruins\nAncient Ruins\nStarfall Tundra\nStarfall Tundra\nStarfall Tundra\nStarfall Tundra\nStarfall Tundra\nAncient Ruins\nAncient Ruins",
    "SpriteId": "T_Artifact_Oathbound_0\nT_Artifact_Oathbound_1\nT_Artifact_Oathbound_2\nT_Artifact_Oathbound_3",
    "SourceLevel": 131
  },
  {
    "SetName": "Pioneer",
    "SetId": "Novice",
    "IndividualBonus": null,
    "PerPieceBonus": "HP: <color=#AAFF00FF>+20 per level</color>\nMP: <color=#AAFF00FF>+10 per level</color>",
    "PerRefineBonus": null,
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nHP Regen: <color=#AAFF00FF>+5</color>\nMP Regen: <color=#AAFF00FF>+2</color>\nAtk: <color=#AAFF00FF>+3</color>\nMatk: <color=#AAFF00FF>+3</color>",
    "Source": "Rune - Bee\nRune - Rooster\nJewel - Bumblebee\nJewel - Chick\nScroll - Egg\nScroll - Fledgling\nRune - Pollen\nRelic - Seedling\nRelic - Sprout",
    "Droprate": "500.0%\n500.0%\n500.0%\n1000.0%\n1000.0%\n500.0%\n1000.0%\n1000.0%\n500.0%",
    "Location": "Sunny Meadows 2\nSunny Meadows 2\nSunny Meadows 2\nSunny Meadows 1\nSunny Meadows 1\nSunny Meadows 2\nSunny Meadows 1\nSunny Meadows 1\nSunny Meadows 2",
    "SpriteId": "T_Artifact_Pioneer_0\nT_Artifact_Pioneer_1\nT_Artifact_Pioneer_2\nT_Artifact_Pioneer_3",
    "SourceLevel": 1
  },
  {
    "SetName": "Primordial",
    "SetId": "Primordial",
    "IndividualBonus": null,
    "PerPieceBonus": "Fire Damage: <color=#AAFF00FF>+3% per level</color>\nWater Damage: <color=#AAFF00FF>+3% per level</color>\nWind Damage: <color=#AAFF00FF>+3% per level</color>\nEarth Damage: <color=#AAFF00FF>+3% per level</color>",
    "PerRefineBonus": "Fire Damage: <color=#AAFF00FF>+0.125% per level</color>\nWater Damage: <color=#AAFF00FF>+0.125% per level</color>\nWind Damage: <color=#AAFF00FF>+0.125% per level</color>\nEarth Damage: <color=#AAFF00FF>+0.125% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nFire Damage: <color=#AAFF00FF>+3%</color>\nWater Damage: <color=#AAFF00FF>+3%</color>\nWind Damage: <color=#AAFF00FF>+3%</color>\nEarth Damage: <color=#AAFF00FF>+3%</color>",
    "Source": "Jewel - Azure Octopus\nScroll - Amber Octopus\nRelic - Violet Octopus\nRune - Hydro Turtle\nRune - Solar Turtle\nJewel - Storm Turtle",
    "Droprate": "100.0%\n100.0%\n100.0%\n100.0%\n100.0%\n100.0%",
    "Location": "Turtle Nexus\nTurtle Nexus\nTurtle Nexus\nTurtle Nexus\nTurtle Nexus\nTurtle Nexus",
    "SpriteId": "T_Artifact_Primordial_0\nT_Artifact_Primordial_1\nT_Artifact_Primordial_2\nT_Artifact_Primordial_3",
    "SourceLevel": 131
  },
  {
    "SetName": "Shadebound",
    "SetId": "Flee",
    "IndividualBonus": null,
    "PerPieceBonus": "Flee: <color=#AAFF00FF>+15 per level</color>",
    "PerRefineBonus": "Flee: <color=#AAFF00FF>+1 per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nPerfect Dodge: <color=#AAFF00FF>+10%</color>\nStr:",
    "Source": "Rune - Darter\nJewel - Skimmer\nJewel - Gadfly\nScroll - Blowfly\nScroll - Gnat\nRelic - Mosquito\nRelic - Spitter\nRune - Slime",
    "Droprate": "400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%",
    "Location": "Swamp\nSwamp\nSwamp\nSwamp\nSwamp\nSwamp\nSwamp\nSwamp",
    "SpriteId": "T_Artifact_Shadebound_0\nT_Artifact_Shadebound_1\nT_Artifact_Shadebound_2\nT_Artifact_Shadebound_3",
    "SourceLevel": 36
  },
  {
    "SetName": "Spellweaver",
    "SetId": "Cast",
    "IndividualBonus": null,
    "PerPieceBonus": "Cast Speed: <color=#AAFF00FF>+10% per level</color>",
    "PerRefineBonus": "Cast Speed: <color=#AAFF00FF>+0.25% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nCast Speed:",
    "Source": "Relic - Fairy\nRune - Sprite\nRelic - Pixie\nRune - Fire Glimmer\nRune - Celestial Moth\nJewel - Luna Moth\nJewel - Moon Moth\nScroll - Nymph\nScroll - Sylvie",
    "Droprate": "400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%",
    "Location": "Fairy Glen\nFairy Glen\nFairy Glen\nFairy Glen\nFairy Glen\nFairy Glen\nFairy Glen\nFairy Glen\nFairy Glen",
    "SpriteId": "T_Artifact_Spellweaver_0\nT_Artifact_Spellweaver_1\nT_Artifact_Spellweaver_2\nT_Artifact_Spellweaver_3",
    "SourceLevel": 31
  },
  {
    "SetName": "Starfire",
    "SetId": "Matk",
    "IndividualBonus": null,
    "PerPieceBonus": "Matk: <color=#AAFF00FF>+5 per level</color>\nMP: <color=#AAFF00FF>+5% per level</color>\nHP: <color=#FF0073FF>-10% per level</color>",
    "PerRefineBonus": "MATK: <color=#AAFF00FF>+0.25% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nMatk: <color=#AAFF00FF>+10</color>\nMP: <color=#AAFF00FF>+5%</color>\nHP: <color=#FF0073FF>-10%</color>\nEnergy Shield Level: <color=#AAFF00FF>+2</color>",
    "Source": "Rune - Eyeclops Bat\nScroll - Eyeclops Mage\nScroll - Eyeclops Arcanist\nJewel - Wight\nJewel - Direwolf\nJewel - Azure Eyestalk\nScroll - Jade Eyestalk\nRelic - Ruby Eyestalk\nRelic - Azure Beholder\nRune - Jade Beholder\nJewel - Ruby Beholder\nRune - Spectre\nRune - Reaper\nJewel - Barrel Mimic\nRune - Book Mimic\nScroll - Candle Mimic\nRune - Trap Mimic\nRune - Sword Mimic\nRelic - Chest Mimic\nJewel - Apparition\nJewel - Skeleton Giant\nRelic - Skeleton Mage",
    "Droprate": "200.0%\n100.0%\n200.0%\n200.0%\n100.0%\n100.0%\n100.0%\n100.0%\n100.0%\n100.0%\n100.0%\n100.0%\n100.0%\n200.0%\n100.0%\n200.0%\n200.0%\n200.0%\n200.0%\n100.0%\n200.0%\n200.0%",
    "Location": "Abyss Castle Keep\nAbyss Castle Library\nAbyss Castle Keep\nAbyss Castle Keep\nAbyss Castle Crypt\nAbyss Castle Crypt\nAbyss Castle Crypt\nAbyss Castle Crypt\nAbyss Castle Library\nAbyss Castle Library\nAbyss Castle Library\nAbyss Castle Crypt\nAbyss Castle Crypt\nAbyss Castle Dungeon\nAbyss Castle Library\nAbyss Castle Dungeon\nAbyss Castle Dungeon\nAbyss Castle Keep\nAbyss Castle Dungeon\nAbyss Castle Library\nAbyss Castle Keep\nAbyss Castle Keep",
    "SpriteId": "T_Artifact_Starfire_0\nT_Artifact_Starfire_1\nT_Artifact_Starfire_2\nT_Artifact_Starfire_3",
    "SourceLevel": 106
  },
  {
    "SetName": "Steelheart",
    "SetId": "Melee",
    "IndividualBonus": null,
    "PerPieceBonus": "Melee Damage: <color=#AAFF00FF>+3% per level</color>",
    "PerRefineBonus": "Melee Damage: <color=#AAFF00FF>+0.125% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nMelee Damage: <color=#AAFF00FF>+3%</color>",
    "Source": "Scroll - Mandrake\nRune - Sewer Rat\nRelic - Sewer Rat\nJewel - Plague Rat\nScroll - Albino Rat\nRune - Maple Ancient\nJewel - Pine Ancient\nRune - Maple Sapling\nJewel - Pine Sapling\nScroll - Maple Treant\nRelic - Pine Treant",
    "Droprate": "500.0%\n500.0%\n500.0%\n500.0%\n500.0%\n500.0%\n500.0%\n500.0%\n500.0%\n500.0%\n500.0%",
    "Location": "Treant Trail\nNevaris Sewers\nNevaris Sewers\nNevaris Sewers\nNevaris Sewers\nTreant Trail\nTreant Trail\nTreant Trail\nTreant Trail\nTreant Trail\nTreant Trail",
    "SpriteId": "T_Artifact_Steelheart_0\nT_Artifact_Steelheart_1\nT_Artifact_Steelheart_2\nT_Artifact_Steelheart_3",
    "SourceLevel": 16
  },
  {
    "SetName": "Stormquiver",
    "SetId": "Ranged",
    "IndividualBonus": null,
    "PerPieceBonus": "Ranged Damage: <color=#AAFF00FF>+3% per level</color>",
    "PerRefineBonus": "Ranged Damage: <color=#AAFF00FF>+0.125% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nRanged Damage: <color=#AAFF00FF>+3%</color>",
    "Source": "Relic - Voltpaw\nRelic - Hellhound\nJewel - Lightning Glimmer\nJewel - Mole\nRune - Dire Mole\nScroll - Scorpion\nRune - Scorpling\nRune - Breeze\nScroll - Gale\nRune - Wind Mage",
    "Droprate": "400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%",
    "Location": "Windy Desert\nWindy Desert North\nWindy Desert\nWindy Desert North\nWindy Desert North\nWindy Desert North\nWindy Desert North\nWindy Desert\nWindy Desert\nWindy Desert",
    "SpriteId": "T_Artifact_Stormquiver_0\nT_Artifact_Stormquiver_1\nT_Artifact_Stormquiver_2\nT_Artifact_Stormquiver_3",
    "SourceLevel": 26
  },
  {
    "SetName": "Tempest Engine",
    "SetId": "Wizard_1",
    "IndividualBonus": "Tempest Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nChain Lightning Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nThunder Storm Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nCast Speed: <color=#AAFF00FF>+1% per level</color>",
    "PerPieceBonus": null,
    "PerRefineBonus": null,
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+3</color>\n<color=#B2B2B2FF>Tempest and Chain Lightning build Tempest Engine, increasing their power and MP cost. Chain Lightning also triggers Thunder Storm.</color>\nTempest applies <color=#AAFF00FF>Tempest Engine</color> for <color=#AAFF00FF>10 seconds</color>\nChain Lightning applies <color=#AAFF00FF>Tempest Engine</color> for <color=#AAFF00FF>10 seconds</color>\n<color=#AAFF00FF>30%</color> chance to Autocast <color=#AAFF00FF>Thunder Storm</color> with <color=#AAFF00FF>Chain Lightning</color> hits\n-----------------------------------------------------\n<color=#C37CFFFF>Tempest Engine</color>\n<color=#FF9700FF>Stackable (maximum 5 stacks)</color>\nChain Lightning Damage: <color=#AAFF00FF>+10%</color>\nChain Lightning Mana Cost: <color=#FF0073FF>+30%</color>\nTempest Damage: <color=#AAFF00FF>+10%</color>\nTempest Mana Cost: <color=#FF0073FF>+30%</color>\nDuration: <color=#AAFF00FF>10 seconds</color>\n-----------------------------------------------------\n<color=#00E2FFFF>Thunder Storm</color>\n<color=#B2B2B2FF>Call down a storm of lightning over an area, striking enemies and exposing them to Water damage.</color>\nType: <color=#00E2FFFF>Magic</color>\nElement: <sprite name=wind> <color=#FFC701FF>Wind</color>\nDamage: <color=#AAFF00FF>250% MATK per level</color>\nHits: <color=#AAFF00FF>1 per level</color>\nArea: <color=#AAFF00FF>5</color>\nCost: <color=#AAFF00FF>30 + 15 mana per level</color>\n-----------------------------------------------------\n<color=#FFD900FF>Status Effects</color>\n<color=#C37CFFFF>Water Exposure</color>\nWater Resistance: <color=#FF0073FF>-4% per level</color>\nDuration: <color=#AAFF00FF>10 seconds</color>\nStr:",
    "Source": "Crafted",
    "Droprate": null,
    "Location": "Mystic Lake 2",
    "SpriteId": "artifacts-wizard-1_0\nartifacts-wizard-1_1\nartifacts-wizard-1_2\nartifacts-wizard-1_3"
  },
  {
    "SetName": "Titanplate",
    "SetId": "Def",
    "IndividualBonus": null,
    "PerPieceBonus": "Def: <color=#AAFF00FF>+10 per level</color>",
    "PerRefineBonus": "Def: <color=#AAFF00FF>+1 per level</color>\nReflect Damage: <color=#AAFF00FF>+1% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nDEF: <color=#AAFF00FF>+5%</color>\nStr:\nReflect Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Rune - Cacti\nScroll - Cactus\nRune - Stone Golem\nRelic - Man-Eater\nJewel - Spore",
    "Droprate": "400.0%\n400.0%\n400.0%\n400.0%\n400.0%",
    "Location": "Windy Desert South\nWindy Desert South\nWindy Desert South\nWindy Desert South\nWindy Desert South",
    "SpriteId": "T_Artifact_Titanplate_0\nT_Artifact_Titanplate_1\nT_Artifact_Titanplate_2\nT_Artifact_Titanplate_3",
    "SourceLevel": 31
  },
  {
    "SetName": "Vampiric",
    "SetId": "Vampiric",
    "IndividualBonus": null,
    "PerPieceBonus": "Health Leech: <color=#AAFF00FF>+3% per level</color>",
    "PerRefineBonus": "Health Leech: <color=#AAFF00FF>+0.125% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nHealth Leech: <color=#AAFF00FF>+3%</color>",
    "Source": "Scroll - Abomination\nRune - Nightwing\nRelic - Nightwing\nRune - Nightlord\nRelic - Nightlord\nJewel - Zombie Orc\nJewel - Zombie Goblin\nScroll - Zombie Grunt",
    "Droprate": "400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%",
    "Location": "Goblin Cave 2\nGoblin Cave 1\nGoblin Cave 1\nGoblin Cave 2\nGoblin Cave 2\nGoblin Cave 2\nGoblin Cave 1\nGoblin Cave 1",
    "SpriteId": "T_Artifact_Vampiric_0\nT_Artifact_Vampiric_1\nT_Artifact_Vampiric_2\nT_Artifact_Vampiric_3",
    "SourceLevel": 51
  },
  {
    "SetName": "Veilward",
    "SetId": "Mdef",
    "IndividualBonus": null,
    "PerPieceBonus": "Mdef: <color=#AAFF00FF>+10 per level</color>",
    "PerRefineBonus": "Mdef: <color=#AAFF00FF>+1 per level</color>\nChance to reflect single-target magic.: <color=#AAFF00FF>+0.5% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nMDEF: <color=#AAFF00FF>+5%</color>\nStr:\nChance to reflect single-target magic.: <color=#AAFF00FF>+5%</color>",
    "Source": "Scroll - Cyclops\nJewel - Cyclops Titan\nRelic - Cyclopling\nRune - Frost Wyvern\nJewel - Rime Drake\nScroll - Aqua Drake\nRelic - Elder Frost\nScroll - Rime Golem\nRune - Ice\nRune - Icicle\nJewel - Snowball",
    "Droprate": "300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%",
    "Location": "Crystal Cave\nCrystal Cave\nCrystal Cave\nCrystal Cave\nCrystal Cave\nCrystal Cave\nCrystal Cave\nCrystal Cave\nCrystal Cave\nCrystal Cave\nCrystal Cave",
    "SpriteId": "T_Artifact_Veilward_0\nT_Artifact_Veilward_1\nT_Artifact_Veilward_2\nT_Artifact_Veilward_3",
    "SourceLevel": 71
  },
  {
    "SetName": "Vitalis",
    "SetId": "Hp",
    "IndividualBonus": null,
    "PerPieceBonus": "HP: <color=#AAFF00FF>+10% per level</color>",
    "PerRefineBonus": "HP: <color=#AAFF00FF>+0.25% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nHP:",
    "Source": "Jewel - Orc\nScroll - Orc Soldier\nRune - Orc Mage\nRelic - Orc Mage\nRune - Goblin\nRelic - Goblin Grunt\nScroll - Goblin Assassin\nJewel - Goblin Mage\nRune - Goblin Soldier",
    "Droprate": "400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%",
    "Location": "Goblin Village\nGoblin Village\nGoblin Village\nGoblin Village\nGoblin Field\nGoblin Field\nGoblin Field\nGoblin Field\nGoblin Field",
    "SpriteId": "T_Artifact_Vitalis_0\nT_Artifact_Vitalis_1\nT_Artifact_Vitalis_2\nT_Artifact_Vitalis_3",
    "SourceLevel": 41
  },
  {
    "SetName": "Warglyph",
    "SetId": "Atk",
    "IndividualBonus": null,
    "PerPieceBonus": "Atk: <color=#AAFF00FF>+5 per level</color>\nHP: <color=#AAFF00FF>+5% per level</color>\nMP: <color=#FF0073FF>-15% per level</color>",
    "PerRefineBonus": "ATK: <color=#AAFF00FF>+0.25% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nAtk: <color=#AAFF00FF>+10</color>\nHP: <color=#AAFF00FF>+5%</color>\nMP: <color=#FF0073FF>-15%</color>",
    "Source": "Jewel - Orc Reaver\nScroll - Orc Crusher\nRune - Orc Warlock\nRelic - Orc Warlock",
    "Droprate": "100.0%\n100.0%\n100.0%\n100.0%",
    "Location": "Goblin Warcamp\nGoblin Warcamp\nGoblin Warcamp\nGoblin Warcamp",
    "SpriteId": "T_Artifact_Warglyph_0\nT_Artifact_Warglyph_1\nT_Artifact_Warglyph_2\nT_Artifact_Warglyph_3",
    "SourceLevel": 121
  },
  {
    "SetName": "Windborne",
    "SetId": "Movespeed",
    "IndividualBonus": null,
    "PerPieceBonus": "Movement Speed: <color=#AAFF00FF>+5% per level</color>",
    "PerRefineBonus": "Movement Speed: <color=#AAFF00FF>+0.25% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nMovement Speed:",
    "Source": "Rune - Bunny\nRelic - Bunny\nJewel - Egglet\nScroll - Rabbit",
    "Droprate": "500.0%\n500.0%\n500.0%\n500.0%",
    "Location": "Bunny Woods\nBunny Woods\nBunny Woods\nBunny Woods",
    "SpriteId": "T_Artifact_Windbourne_0\nT_Artifact_Windbourne_1\nT_Artifact_Windbourne_2\nT_Artifact_Windbourne_3",
    "SourceLevel": 21
  }
];
