window.artifactData = [
  {
    "SetName": "Aegis Light",
    "SetId": "Paladin_1",
    "IndividualBonus": "Grand Cross Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nJudgement Blade Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nShield Throw Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nConsecration Healing: <color=#AAFF00FF>+5% + 2% per level</color>",
    "PerPieceBonus": null,
    "PerRefineBonus": null,
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+3</color>",
    "Source": "Crafted",
    "Droprate": null,
    "Location": null,
    "SpriteId": "artifacts-paladin-1_0\nartifacts-paladin-1_1\nartifacts-paladin-1_2\nartifacts-paladin-1_3"
  },
  {
    "SetName": "Aethercore",
    "SetId": "Mp",
    "IndividualBonus": null,
    "PerPieceBonus": "Mp: <color=#AAFF00FF>+10% per level</color>",
    "PerRefineBonus": "Mp: <color=#AAFF00FF>+0.25% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nMp:",
    "Source": "Scroll - Flora\nJewel - Fungi\nJewel - Glow Wisp Blue\nRune - Mushroom\nRelic - Mushroom\nRelic - Petal\nRune - Posy\nRune - Shell\nScroll - Shell\nJewel - Spike\nRelic - Spike\nScroll - Toadstool",
    "Droprate": "400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%",
    "Location": "Mystic Lake 1\nLake Field\nMystic Lake 1\nLake Field\nLake Field\nMystic Lake 1\nMystic Lake 1\nMystic Lake 2\nMystic Lake 2\nMystic Lake 2\nMystic Lake 2\nLake Field",
    "SpriteId": "T_Artifact_Aethercore_0\nT_Artifact_Aethercore_1\nT_Artifact_Aethercore_2\nT_Artifact_Aethercore_3"
  },
  {
    "SetName": "Arcane Elementalist",
    "SetId": "Wizard_4",
    "IndividualBonus": "<color=#FF9700FF>Cast cannot be interrupted</color>\nGrants <color=#AAFF00FF>Free Cast</color>\nCast Spd: <color=#AAFF00FF>+1% per level</color>\nMp Regen: <color=#AAFF00FF>+2% per level</color>",
    "PerPieceBonus": null,
    "PerRefineBonus": null,
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+3</color>\n<color=#B2B2B2FF>Four attunements share one page, arguing until they become a single harmony.</color>\n\n<color=#FF9700FF><color=#AAFF00FF>Elemental Attunement</color> replaces Fire Attunement</color>\n<color=#FF9700FF><color=#AAFF00FF>Elemental Attunement</color> replaces Water Attunement</color>\n<color=#FF9700FF><color=#AAFF00FF>Elemental Attunement</color> replaces Wind Attunement</color>\n<color=#FF9700FF><color=#AAFF00FF>Elemental Attunement</color> replaces Earth Attunement</color>\n-----------------------------------------------------\n<color=#C37CFFFF>Elemental Attunement</color>\nFire Damage: <color=#AAFF00FF>+5% per level</color>\nWater Damage: <color=#AAFF00FF>+5% per level</color>\nWind Damage: <color=#AAFF00FF>+5% per level</color>\nEarth Damage: <color=#AAFF00FF>+5% per level</color>\n<color=#B2B2B2FF>Elemental sigils raise matching barriers whenever avatar power gathers around the caster.</color>\n\nApply <color=#AAFF00FF>Arcane Barrier</color> for <color=#AAFF00FF>1 seconds</color> when applying <color=#AAFF00FF>Fire Barrier</color>\nApply <color=#AAFF00FF>Arcane Barrier</color> for <color=#AAFF00FF>1 seconds</color> when applying <color=#AAFF00FF>Water Barrier</color>\nApply <color=#AAFF00FF>Arcane Barrier</color> for <color=#AAFF00FF>1 seconds</color> when applying <color=#AAFF00FF>Wind Barrier</color>\nApply <color=#AAFF00FF>Arcane Barrier</color> for <color=#AAFF00FF>1 seconds</color> when applying <color=#AAFF00FF>Earth Barrier</color>\n-----------------------------------------------------\n<color=#C37CFFFF>Arcane Barrier</color>\nFire Damage: <color=#AAFF00FF>+10%</color>\nFire Resistance: <color=#AAFF00FF>+10%</color>\nDuration: <color=#AAFF00FF>1 seconds</color>\n-----------------------------------------------------\n<color=#C37CFFFF>Arcane Barrier</color>\nWater Damage: <color=#AAFF00FF>+10%</color>\nWater Resistance: <color=#AAFF00FF>+10%</color>\nDuration: <color=#AAFF00FF>1 seconds</color>\n-----------------------------------------------------\n<color=#C37CFFFF>Arcane Barrier</color>\nWind Damage: <color=#AAFF00FF>+10%</color>\nWind Resistance: <color=#AAFF00FF>+10%</color>\nDuration: <color=#AAFF00FF>1 seconds</color>\n-----------------------------------------------------\n<color=#C37CFFFF>Arcane Barrier</color>\nEarth Damage: <color=#AAFF00FF>+10%</color>\nEarth Resistance: <color=#AAFF00FF>+10%</color>\nDuration: <color=#AAFF00FF>1 seconds</color>\nStr:",
    "Source": "Crafted",
    "Droprate": null,
    "Location": null,
    "SpriteId": "artifacts-wizard-1_0\nartifacts-wizard-1_1\nartifacts-wizard-1_2\nartifacts-wizard-1_3"
  },
  {
    "SetName": "Arcane Origin",
    "SetId": "Mage",
    "IndividualBonus": "Fireball Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nIce Shard Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nEarth Spikes Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nThunder Storm Damage: <color=#AAFF00FF>+5% + 2% per level</color>",
    "PerPieceBonus": null,
    "PerRefineBonus": null,
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+3</color>",
    "Source": null,
    "Droprate": null,
    "Location": null,
    "SpriteId": "T_Artifact_ArcaneOrigin_0\nT_Artifact_ArcaneOrigin_1\nT_Artifact_ArcaneOrigin_5\nT_Artifact_ArcaneOrigin_6"
  },
  {
    "SetName": "Arcanum",
    "SetId": "Magic",
    "IndividualBonus": null,
    "PerPieceBonus": "Damage Magic: <color=#AAFF00FF>+3% per level</color>",
    "PerRefineBonus": "Damage Magic: <color=#AAFF00FF>+0.125% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nDamage Magic: <color=#AAFF00FF>+3%</color>",
    "Source": "Jewel - Burrow\nRune - Cat Meow\nRelic - Dog Bark\nScroll - Dog Pup\nRune - Wisp Blue\nJewel - Wisp Purple\nScroll - Wisp Red\nRelic - Wisp Yellow",
    "Droprate": "600.0%\n600.0%\n600.0%\n600.0%\n600.0%\n600.0%\n600.0%\n600.0%",
    "Location": "Forest Field 2\nForest Field 2\nForest Field 2\nForest Field 2\nForest Field 1\nForest Field 1\nForest Field 1\nForest Field 1",
    "SpriteId": "T_Artifact_Arcanum_0\nT_Artifact_Arcanum_1\nT_Artifact_Arcanum_2\nT_Artifact_Arcanum_3"
  },
  {
    "SetName": "Arcanum Verge",
    "SetId": "Cost",
    "IndividualBonus": null,
    "PerPieceBonus": "Mp Cost: <color=#AAFF00FF>-10% per level</color>",
    "PerRefineBonus": "Mp Cost: <color=#AAFF00FF>-0.25% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nStr:",
    "Source": "Rune - Bomb\nRelic - Dragon Darkness\nScroll - Phantom\nRune - Soul Mage\nJewel - Spook",
    "Droprate": "300.0%\n300.0%\n300.0%\n300.0%\n300.0%",
    "Location": "Sanctum of Light\nSanctum of Light\nSanctum of Light\nSanctum of Light\nSanctum of Light",
    "SpriteId": "T_Artifact_ArcanumVerge_0\nT_Artifact_ArcanumVerge_1\nT_Artifact_ArcanumVerge_2\nT_Artifact_ArcanumVerge_3"
  },
  {
    "SetName": "Bastion",
    "SetId": "Bastion",
    "IndividualBonus": "<color=#FF9700FF>Immune to Knockback</color>\n<color=#FF9700FF>Immune to Flinching from damage</color>\n<color=#FF9700FF>Cast cannot be interrupted</color>\n<color=#FF9700FF>Immune to Reflect damage</color>",
    "PerPieceBonus": null,
    "PerRefineBonus": null,
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+5</color>\nHp: <color=#AAFF00FF>+10%</color>\nMp: <color=#AAFF00FF>+10%</color>",
    "Source": "Rune - FIsh Blue\nRelic - Fish Man Blue\nRune - Fish Man Pink\nJewel - Fish Man Yellow\nScroll - Merman Blue\nRelic - Merman Pink\nRune - Merman Yellow\nJewel - Fish Pink\nScroll - Fish Yellow\nRune - Octopus Baby Blue\nJewel - Octopus Baby Orange\nScroll - Octopus Baby Purple\nScroll - Octopus Orange\nRelic - Octopus Purple\nRune - Octopus White\nJewel - Shark\nRelic - Squid Baby",
    "Droprate": "200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%",
    "Location": "Sunken Depths\nSunken Depths\nSunken Depths\nSunken Depths\nSunken Depths\nSunken Depths\nSunken Depths\nSunken Depths\nSunken Depths\nSunken Depths\nSunken Depths\nSunken Depths\nSunken Depths\nSunken Depths\nSunken Depths\nSunken Depths\nSunken Depths",
    "SpriteId": "T_Artifact_Bastion_0\nT_Artifact_Bastion_1\nT_Artifact_Bastion_2\nT_Artifact_Bastion_3"
  },
  {
    "SetName": "Blitzcore",
    "SetId": "Auto",
    "IndividualBonus": null,
    "PerPieceBonus": "Atk Spd: <color=#AAFF00FF>+3% per level</color>",
    "PerRefineBonus": "Atk Spd: <color=#AAFF00FF>+0.25% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nAuto attack chain: <color=#AAFF00FF>+2</color>\nAtk Spd: <color=#AAFF00FF>+3%</color>",
    "Source": "Rune - Bat\nJewel - Creeper\nRelic - Horror\nScroll - Lurker\nJewel - Snake\nRelic - Snakelet\nJewel - Spider\nScroll - Spider King\nRune - Spider Toxin\nRune - Vampire Bat",
    "Droprate": "400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%",
    "Location": "Forgotten Depths 1\nForgotten Depths 1\nForgotten Depths 2\nForgotten Depths 1\nForgotten Depths 2\nForgotten Depths 1\nForgotten Depths 1\nForgotten Depths 2\nForgotten Depths 1\nForgotten Depths 2",
    "SpriteId": "T_Artifact_Blitzcore_0\nT_Artifact_Blitzcore_1\nT_Artifact_Blitzcore_2\nT_Artifact_Blitzcore_3"
  },
  {
    "SetName": "Bloodbind",
    "SetId": "Leech",
    "IndividualBonus": null,
    "PerPieceBonus": "Health on kill: <color=#AAFF00FF>+25 per level</color>\nMana on kill: <color=#AAFF00FF>+5 per level</color>",
    "PerRefineBonus": "Health on kill: <color=#AAFF00FF>+5 per level</color>\nMana on kill: <color=#AAFF00FF>+1 per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nStr:\nStr:",
    "Source": "Rune - Eyeball Bat Blue\nJewel - Eyeball Bat Green\nScroll - Eyeball Bat Red\nRelic - Skeleton\nJewel - Wolf\nRelic - Wolf\nRune - Wolf Pup\nScroll - Wolf Pup",
    "Droprate": "600.0%\n600.0%\n600.0%\n600.0%\n400.0%\n400.0%\n400.0%\n400.0%",
    "Location": "Festering Woods 1\nFestering Woods 1\nFestering Woods 1\nFestering Woods 1\nFestering Woods 2\nFestering Woods 2\nFestering Woods 2\nFestering Woods 2",
    "SpriteId": "T_Artifact_Bloodbind_0\nT_Artifact_Bloodbind_1\nT_Artifact_Bloodbind_2\nT_Artifact_Bloodbind_3"
  },
  {
    "SetName": "Bloodfury",
    "SetId": "Berserker_1",
    "IndividualBonus": "Execute Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nCyclone Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nAxe Throw Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nDark Claw Damage: <color=#AAFF00FF>+5% + 2% per level</color>",
    "PerPieceBonus": null,
    "PerRefineBonus": null,
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+3</color>",
    "Source": "Crafted",
    "Droprate": null,
    "Location": null,
    "SpriteId": "artifacts-berserker-1_0\nartifacts-berserker-1_1\nartifacts-berserker-1_2\nartifacts-berserker-1_3"
  },
  {
    "SetName": "Corporeal",
    "SetId": "Corporeal",
    "IndividualBonus": null,
    "PerPieceBonus": "Poison Damage: <color=#AAFF00FF>+3% per level</color>\nUndead Damage: <color=#AAFF00FF>+3% per level</color>\nShadow Damage: <color=#AAFF00FF>+3% per level</color>\nHoly Damage: <color=#AAFF00FF>+3% per level</color>",
    "PerRefineBonus": "Poison Damage: <color=#AAFF00FF>+0.125% per level</color>\nUndead Damage: <color=#AAFF00FF>+0.125% per level</color>\nShadow Damage: <color=#AAFF00FF>+0.125% per level</color>\nHoly Damage: <color=#AAFF00FF>+0.125% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nPoison Damage: <color=#AAFF00FF>+3%</color>\nUndead Damage: <color=#AAFF00FF>+3%</color>\nShadow Damage: <color=#AAFF00FF>+3%</color>\nHoly Damage: <color=#AAFF00FF>+3%</color>",
    "Source": "Jewel - Boxy Robot\nRelic - Delivery Robot\nScroll - Gripper Robot\nJewel - Nose Robot\nRelic - Nozzle Robot\nRune - Razor Robot\nJewel - Shell Robot\nRune - Snout Robot\nScroll - Spider Robot\nRune - Spiderling Robot\nScroll - Spike Robot",
    "Droprate": "100.0%\n100.0%\n100.0%\n100.0%\n100.0%\n100.0%\n100.0%\n100.0%\n100.0%\n100.0%\n100.0%",
    "Location": "The Forge\nThe Forge\nThe Forge\nThe Forge\nThe Forge\nThe Forge\nThe Forge\nThe Forge\nThe Forge\nThe Forge\nThe Forge",
    "SpriteId": "T_Artifact_Corporeal_0\nT_Artifact_Corporeal_1\nT_Artifact_Corporeal_2\nT_Artifact_Corporeal_3"
  },
  {
    "SetName": "Deadeye",
    "SetId": "Gunslinger_1",
    "IndividualBonus": "Panic Burst Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nPoint Blank Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nSniper Shot Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nExplosive Grenade Damage: <color=#AAFF00FF>+5% + 2% per level</color>",
    "PerPieceBonus": null,
    "PerRefineBonus": null,
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+3</color>",
    "Source": null,
    "Droprate": null,
    "Location": null,
    "SpriteId": "artifacts-gunslinger-1_0\nartifacts-gunslinger-1_1\nartifacts-gunslinger-1_2\nartifacts-gunslinger-1_3"
  },
  {
    "SetName": "Eternis",
    "SetId": "Eternis",
    "IndividualBonus": null,
    "PerPieceBonus": null,
    "PerRefineBonus": null,
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+5</color>\nGrants <color=#AAFF00FF>Lv.5 Heal</color>\nGrants <color=#AAFF00FF>Lv.5 Haste</color>\nHp: <color=#AAFF00FF>+10%</color>\nMp: <color=#AAFF00FF>+10%</color>\nAtk: <color=#AAFF00FF>+5%</color>\nMatk: <color=#AAFF00FF>+5%</color>",
    "Source": "Rune - Voidgazer\nScroll - Bogbloom\nRelic - Ashrend\nJewel - Stormcoil",
    "Droprate": "100.0%\n100.0%\n100.0%\n100.0%",
    "Location": "Night Garden\nNight Garden\nNight Garden\nNight Garden",
    "SpriteId": "T_Artifact_Eternis_0\nT_Artifact_Eternis_1\nT_Artifact_Eternis_2\nT_Artifact_Eternis_3"
  },
  {
    "SetName": "Far Sight",
    "SetId": "Scout",
    "IndividualBonus": "Strafing Volley Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nForce Shot Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nVolatile Bolt Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nArrow Shower Damage: <color=#AAFF00FF>+5% + 2% per level</color>",
    "PerPieceBonus": null,
    "PerRefineBonus": null,
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+3</color>",
    "Source": null,
    "Droprate": null,
    "Location": null,
    "SpriteId": "T_Artifact_Farsight_0\nT_Artifact_Farsight_1\nT_Artifact_Farsight_2\nT_Artifact_Farsight_3"
  },
  {
    "SetName": "Fateweave",
    "SetId": "Weaver_1",
    "IndividualBonus": "Firebolt Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nIcebolt Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nThunderbolt Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nEarthbolt Damage: <color=#AAFF00FF>+5% + 2% per level</color>",
    "PerPieceBonus": null,
    "PerRefineBonus": null,
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+3</color>",
    "Source": "Crafted",
    "Droprate": null,
    "Location": null,
    "SpriteId": "artifacts-weaver-1_0\nartifacts-weaver-1_1\nartifacts-weaver-1_2\nartifacts-weaver-1_3"
  },
  {
    "SetName": "Frozen Dominion",
    "SetId": "Wizard_2",
    "IndividualBonus": "Blizzard Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nIce Shard Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nFrozen Ground Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nMp Regen: <color=#AAFF00FF>+2% per level</color>",
    "PerPieceBonus": null,
    "PerRefineBonus": null,
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+3</color>\n<color=#B2B2B2FF>Frozen lasts longer. Blizzard and Ice Shard can create Frozen Ground.</color>\n\nStatus Duration: <color=#AAFF00FF>+30%</color>\n<color=#FF9700FF>Blizzard: <color=#AAFF00FF>Remove Knockback</color></color>\n<color=#FF9700FF>Blizzard autocasts Frozen Ground</color>\nAutocast <color=#AAFF00FF>Frozen Ground</color> with <color=#AAFF00FF>Ice Shard</color> hits\n-----------------------------------------------------\n<color=#00E2FFFF>Frozen Ground</color>\n<color=#B2B2B2FF>Freeze the ground beneath enemies, damaging them repeatedly with a chance to leave them Frozen.</color>\n\nType: <color=#00E2FFFF>Magic</color>\nElement: <sprite name=Elements_6> <color=#79D7FDFF>Water</color>\nDamage: <color=#AAFF00FF>500% MATK</color>\nHits: <color=#AAFF00FF>2</color>\nDuration: <color=#AAFF00FF>2 seconds</color>\nMax Instances: <color=#AAFF00FF>3</color>\nCost: <color=#AAFF00FF>20 + 10 mana per level</color>\n-----------------------------------------------------\n<color=#FFD900FF>Status Effects</color>\n<color=#C37CFFFF>Frozen</color>\n<color=#FF0073FF>Cannot Attack or Move</color>\n<color=#FF0073FF>Flee Disabled</color>\n<color=#FF0073FF>Block Disabled</color>\nDuration: <color=#AAFF00FF>10 seconds</color>\nChance: <color=#AAFF00FF>5% per level</color>\nStr:",
    "Source": "Crafted",
    "Droprate": null,
    "Location": null,
    "SpriteId": "artifacts-wizard-1_0\nartifacts-wizard-1_1\nartifacts-wizard-1_2\nartifacts-wizard-1_3"
  },
  {
    "SetName": "Furybrand",
    "SetId": "Crit",
    "IndividualBonus": null,
    "PerPieceBonus": "Crit: <color=#AAFF00FF>+5 per level</color>",
    "PerRefineBonus": "Crit Damage: <color=#AAFF00FF>+0.25% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nCrit Damage: <color=#AAFF00FF>+5%</color>\nStr:",
    "Source": "Jewel - Dragon Fire\nJewel - Dragon Inferno\nScroll - Dragon Spark\nRelic - Elder Wisp Yellow\nRune - Fire\nRune - Fire Mage\nRelic - Flame\nRelic - Golem Fire\nRune - Imp Demon\nJewel - Imp Mischief\nScroll - Shade\nScroll - Shadow",
    "Droprate": "200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%",
    "Location": "Demon's Maw\nDemon's Maw\nDemon's Maw\nDemon's Maw\nDemon's Maw\nDemon's Maw\nDemon's Maw\nDemon's Maw\nDemon's Maw\nDemon's Maw\nDemon's Maw\nDemon's Maw",
    "SpriteId": "T_Artifact_Furybrand_0\nT_Artifact_Furybrand_1\nT_Artifact_Furybrand_2\nT_Artifact_Furybrand_3"
  },
  {
    "SetName": "Gravebound",
    "SetId": "Necromancer_1",
    "IndividualBonus": "Bone Spikes Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nDeath Spiral Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nDeath Nova Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nCorpse Explosion Damage: <color=#AAFF00FF>+5% + 2% per level</color>",
    "PerPieceBonus": null,
    "PerRefineBonus": null,
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+3</color>",
    "Source": null,
    "Droprate": null,
    "Location": null,
    "SpriteId": "artifacts-necromancer-1_0\nartifacts-necromancer-1_2\nartifacts-necromancer-1_3\nartifacts-necromancer-1_4"
  },
  {
    "SetName": "Hawkeye",
    "SetId": "Hit",
    "IndividualBonus": null,
    "PerPieceBonus": "Hit: <color=#AAFF00FF>+15 per level</color>",
    "PerRefineBonus": "Hit: <color=#AAFF00FF>+1 per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nTotal Hit: <color=#AAFF00FF>+10%</color>",
    "Source": "Jewel - Shark Baby\nJewel - Shark Pirate\nRune - Turtle Baby\nScroll - Turtle Blue\nRelic - Turtle Green\nRune - Turtle Red",
    "Droprate": "400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%",
    "Location": "Stormreef Isle\nStormreef Isle\nStormreef Isle\nStormreef Isle\nStormreef Isle\nStormreef Isle",
    "SpriteId": "T_Artifact_Hawkeye_0\nT_Artifact_Hawkeye_1\nT_Artifact_Hawkeye_2\nT_Artifact_Hawkeye_3"
  },
  {
    "SetName": "Hexbrand",
    "SetId": "Hexbrand",
    "IndividualBonus": null,
    "PerPieceBonus": "Damage Status: <color=#AAFF00FF>+5% per level</color>",
    "PerRefineBonus": "Damage Status: <color=#AAFF00FF>+0.25% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nDamage Status: <color=#AAFF00FF>+5%</color>",
    "Source": "Jewel - Fangroot\nRelic - Voidspawn\nJewel - Cinderspike\nScroll - Sporeling\nScroll - Blazewheel\nRune - Devil Bat\nRune - Devil Hades\nScroll - Devil Hell\nRune - Dragonfly Swift\nRune - Earthworm\nJewel - Housefly Junk\nRune - Stormjelly\nScroll - Mosquito Stinger\nJewel - Plant Monster\nRelic - Plant Worm\nScroll - Slime Jelly\nRune - Slime Monster\nRune - Stormstinger\nRelic - Worm",
    "Droprate": "300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n200.0%\n200.0%\n200.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%",
    "Location": "Dark Forest\nDark Forest\nDark Forest\nDark Forest\nDark Forest\n\n\n\nSwamp Wilderness\nSwamp Wilderness\nSwamp Wilderness\nDark Forest\nSwamp Wilderness\nSwamp Wilderness\nSwamp Wilderness\nSwamp Wilderness\nSwamp Wilderness\nDark Forest\nSwamp Wilderness",
    "SpriteId": "T_Artifact_Hexbrand_0\nT_Artifact_Hexbrand_1\nT_Artifact_Hexbrand_2\nT_Artifact_Hexbrand_3"
  },
  {
    "SetName": "Holy Vow",
    "SetId": "Acolyte",
    "IndividualBonus": "Holy Light Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nHeal Healing: <color=#AAFF00FF>+5% + 2% per level</color>\nTrue Sight Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nMp Cost: <color=#AAFF00FF>-2% per level</color>",
    "PerPieceBonus": null,
    "PerRefineBonus": null,
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+3</color>",
    "Source": null,
    "Droprate": null,
    "Location": null,
    "SpriteId": "T_Artifact_HolyVow_0\nT_Artifact_HolyVow_1\nT_Artifact_HolyVow_2\nT_Artifact_HolyVow_3"
  },
  {
    "SetName": "Honored Oath",
    "SetId": "Knight",
    "IndividualBonus": "Piercing Flurry Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nImpale Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nAir Cutter Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nWeapon Throw Damage: <color=#AAFF00FF>+5% + 2% per level</color>",
    "PerPieceBonus": null,
    "PerRefineBonus": null,
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+3</color>",
    "Source": null,
    "Droprate": null,
    "Location": null,
    "SpriteId": "T_Artifact_HonoredOath_0\nT_Artifact_HonoredOath_1\nT_Artifact_HonoredOath_2\nT_Artifact_HonoredOath_3"
  },
  {
    "SetName": "Iron Wake",
    "SetId": "Warrior",
    "IndividualBonus": "Bash Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nTwin Cleave Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nVortex Slash Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nStomp Damage: <color=#AAFF00FF>+5% + 2% per level</color>",
    "PerPieceBonus": null,
    "PerRefineBonus": null,
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+3</color>",
    "Source": null,
    "Droprate": null,
    "Location": null,
    "SpriteId": "T_Artifact_IronWake_0\nT_Artifact_IronWake_1\nT_Artifact_IronWake_2\nT_Artifact_IronWake_3"
  },
  {
    "SetName": "Lifebloom",
    "SetId": "Healing",
    "IndividualBonus": null,
    "PerPieceBonus": "Healing: <color=#AAFF00FF>+5% per level</color>",
    "PerRefineBonus": "Healing: <color=#AAFF00FF>+0.25% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nHealing:",
    "Source": "Rune - Angel\nRune - Archangel\nScroll - Dragon Dusk\nJewel - Dragon Nightfall\nJewel - Ghost\nScroll - Haunt\nRelic - Soul",
    "Droprate": "300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%",
    "Location": "Sanctum of Light\nSanctum of Light\nSanctum of Light\nSanctum of Light\nSanctum of Light\nSanctum of Light\nSanctum of Light",
    "SpriteId": "T_Artifact_LifeBloom_0\nT_Artifact_LifeBloom_1\nT_Artifact_LifeBloom_2\nT_Artifact_LifeBloom_3"
  },
  {
    "SetName": "Meteoric Cataclysm",
    "SetId": "Wizard_3",
    "IndividualBonus": "Meteor Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nFire Pillar Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nCombustion Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nMatk: <color=#AAFF00FF>+1% per level</color>",
    "PerPieceBonus": null,
    "PerRefineBonus": null,
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+3</color>\n<color=#B2B2B2FF>Burning or Stun triggers Combustion. Fire Pillar gains more instances, and Meteor becomes Meteor Storm.</color>\n\nAutocast <color=#AAFF00FF>Combustion</color> when applying <color=#AAFF00FF>Burning</color>\nAutocast <color=#AAFF00FF>Combustion</color> when applying <color=#AAFF00FF>Stun</color>\nFire Pillar max instances: <color=#AAFF00FF>+2</color>\n<color=#FF9700FF><color=#AAFF00FF>Meteor Storm</color> replaces Meteor</color>\n-----------------------------------------------------\n<color=#C37CFFFF>Burning</color>\n<color=#B2B2B2FF>Drains hp over time, scaled by STR, AGI and INT</color>\n<color=#B2B2B2FF>Drains 3% hp per second</color>\n<color=#B2B2B2FF>Stackable</color>\n-----------------------------------------------------\n<color=#C37CFFFF>Stun</color>\n<color=#FF0073FF>Cannot Attack or Move</color>\n<color=#FF0073FF>Flee Disabled</color>\n<color=#FF0073FF>Block Disabled</color>\n-----------------------------------------------------\n<color=#00E2FFFF>Meteor Storm</color>\n<color=#B2B2B2FF>Call down a lingering storm of meteors, raining Fire damage across the targeted area.</color>\n\nElement: <sprite name=Elements_5> <color=#FF7026FF>Fire</color>\nDuration: <color=#AAFF00FF>5 seconds</color>\nArea: <color=#AAFF00FF>7</color>\n-----------------------------------------------------\nCast Range: <color=#AAFF00FF>12</color>\nCast Time: <color=#AAFF00FF>1 seconds per level</color>\nCooldown: <color=#AAFF00FF>7 seconds</color>\nCost: <color=#AAFF00FF>80 + 40 mana per level</color>",
    "Source": "Crafted",
    "Droprate": null,
    "Location": null,
    "SpriteId": "artifacts-wizard-1_0\nartifacts-wizard-1_1\nartifacts-wizard-1_2\nartifacts-wizard-1_3"
  },
  {
    "SetName": "Nullmark",
    "SetId": "Immune",
    "IndividualBonus": "Resistance to Blind: <color=#AAFF00FF>+50%</color>\nResistance to Silence: <color=#AAFF00FF>+50%</color>\nResistance to Poison: <color=#AAFF00FF>+50%</color>\nResistance to Bleeding: <color=#AAFF00FF>+50%</color>",
    "PerPieceBonus": null,
    "PerRefineBonus": "Resistance to Stun: <color=#AAFF00FF>+2.5% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nResistance to Slow: <color=#AAFF00FF>+50%</color>",
    "Source": "Rune - Bloom\nScroll - Blossom\nRune - Bud\nJewel - Elder Wisp Purple\nJewel - Poison Bomb\nRelic - Worm Rot\nScroll - Worm Stink",
    "Droprate": "300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%",
    "Location": "Underground Cavern\nUnderground Cavern\nUnderground Cavern\nUnderground Cavern\nUnderground Cavern\nUnderground Cavern\nUnderground Cavern",
    "SpriteId": "T_Artifact_Nullmark_0\nT_Artifact_Nullmark_1\nT_Artifact_Nullmark_4\nT_Artifact_Nullmark_5"
  },
  {
    "SetName": "Oathbound",
    "SetId": "Oathbound",
    "IndividualBonus": null,
    "PerPieceBonus": "Buff Duration: <color=#AAFF00FF>+10% per level</color>",
    "PerRefineBonus": "Buff Duration: <color=#AAFF00FF>+0.25% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nBuff Duration:",
    "Source": "Rune - Little Star\nJewel - Starry\nRune - Twinkle\nScroll - Ice Bear\nRelic - Festive Bear\nJewel - Ice Golem\nScroll - Shadow Golem\nRelic - Starflake\nRune - Vanilla Ice\nJewel - Shadow Ice\nJewel - Ice Baby\nScroll - Festive Baby\nRelic - Ice Cube\nRune - Shadow Cube",
    "Droprate": "100.0%\n200.0%\n100.0%\n100.0%\n100.0%\n200.0%\n200.0%\n100.0%\n100.0%\n100.0%\n100.0%\n100.0%\n200.0%\n200.0%",
    "Location": "Starfall Tundra\nAncient Ruins\nStarfall Tundra\nStarfall Tundra\nStarfall Tundra\nAncient Ruins\nAncient Ruins\nStarfall Tundra\nStarfall Tundra\nStarfall Tundra\nStarfall Tundra\nStarfall Tundra\nAncient Ruins\nAncient Ruins",
    "SpriteId": "T_Artifact_Oathbound_0\nT_Artifact_Oathbound_1\nT_Artifact_Oathbound_2\nT_Artifact_Oathbound_3"
  },
  {
    "SetName": "Pioneer",
    "SetId": "Novice",
    "IndividualBonus": null,
    "PerPieceBonus": "Hp: <color=#AAFF00FF>+20 per level</color>\nMp: <color=#AAFF00FF>+10 per level</color>",
    "PerRefineBonus": null,
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nHp Regen: <color=#AAFF00FF>+5</color>\nMp Regen: <color=#AAFF00FF>+2</color>\nAtk: <color=#AAFF00FF>+3</color>\nMatk: <color=#AAFF00FF>+3</color>",
    "Source": "Rune - Bee\nRune - Bird\nJewel - Bumble\nJewel - Chick\nScroll - Egg\nScroll - Fledgling\nRune - Pollen\nRelic - Seed\nRelic - Sprout",
    "Droprate": "900.0%\n900.0%\n900.0%\n900.0%\n900.0%\n900.0%\n900.0%\n900.0%\n900.0%",
    "Location": "Sunny Meadows 2\nSunny Meadows 2\nSunny Meadows 2\nSunny Meadows 1\nSunny Meadows 1\nSunny Meadows 2\nSunny Meadows 1\nSunny Meadows 1\nSunny Meadows 2",
    "SpriteId": "T_Artifact_Pioneer_0\nT_Artifact_Pioneer_1\nT_Artifact_Pioneer_2\nT_Artifact_Pioneer_3"
  },
  {
    "SetName": "Primordial",
    "SetId": "Primordial",
    "IndividualBonus": null,
    "PerPieceBonus": "Fire Damage: <color=#AAFF00FF>+3% per level</color>\nWater Damage: <color=#AAFF00FF>+3% per level</color>\nWind Damage: <color=#AAFF00FF>+3% per level</color>\nEarth Damage: <color=#AAFF00FF>+3% per level</color>",
    "PerRefineBonus": "Fire Damage: <color=#AAFF00FF>+0.125% per level</color>\nWater Damage: <color=#AAFF00FF>+0.125% per level</color>\nWind Damage: <color=#AAFF00FF>+0.125% per level</color>\nEarth Damage: <color=#AAFF00FF>+0.125% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nFire Damage: <color=#AAFF00FF>+3%</color>\nWater Damage: <color=#AAFF00FF>+3%</color>\nWind Damage: <color=#AAFF00FF>+3%</color>\nEarth Damage: <color=#AAFF00FF>+3%</color>",
    "Source": "Jewel - Octopus King Blue\nScroll - Octopus King Orange\nRelic - Octopus King Purple\nRune - Hydro Turtle\nRune - Solar Turtle\nJewel - Storm Turtle",
    "Droprate": "100.0%\n100.0%\n100.0%\n100.0%\n100.0%\n100.0%",
    "Location": "Turtle Nexus\nTurtle Nexus\nTurtle Nexus\nTurtle Nexus\nTurtle Nexus\nTurtle Nexus",
    "SpriteId": "T_Artifact_Primordial_0\nT_Artifact_Primordial_1\nT_Artifact_Primordial_2\nT_Artifact_Primordial_3"
  },
  {
    "SetName": "Sanctum Grace",
    "SetId": "Priest_1",
    "IndividualBonus": "Exorcism Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nHoly Wrath Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nTurn Undead Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nSmite Damage: <color=#AAFF00FF>+5% + 2% per level</color>",
    "PerPieceBonus": null,
    "PerRefineBonus": null,
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+3</color>",
    "Source": "Crafted",
    "Droprate": null,
    "Location": null,
    "SpriteId": "artifacts-priest-1_0\nartifacts-priest-1_1\nartifacts-priest-1_2\nartifacts-priest-1_3"
  },
  {
    "SetName": "Shadebound",
    "SetId": "Flee",
    "IndividualBonus": null,
    "PerPieceBonus": "Flee: <color=#AAFF00FF>+15 per level</color>",
    "PerRefineBonus": "Flee: <color=#AAFF00FF>+1 per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nPerfect Dodge: <color=#AAFF00FF>+10%</color>\nStr:",
    "Source": "Rune - Dragonfly Arrow\nJewel - Dragonfly Darner\nJewel - Housefly Icky\nScroll - Housefly Nom\nScroll - Mosquito Bug\nRelic - Mosquito Pester\nRelic - Plant Shooter\nRune - Slime",
    "Droprate": "400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%",
    "Location": "Swamp\nSwamp\nSwamp\nSwamp\nSwamp\nSwamp\nSwamp\nSwamp",
    "SpriteId": "T_Artifact_Shadebound_0\nT_Artifact_Shadebound_1\nT_Artifact_Shadebound_2\nT_Artifact_Shadebound_3"
  },
  {
    "SetName": "Silent Death",
    "SetId": "Rogue",
    "IndividualBonus": "Venom Strike Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nShadow Step Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nBlade Dance Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nDamage Status: <color=#AAFF00FF>+2% per level</color>",
    "PerPieceBonus": null,
    "PerRefineBonus": null,
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+3</color>",
    "Source": null,
    "Droprate": null,
    "Location": null,
    "SpriteId": "T_Artifact_SilentDeath_0\nT_Artifact_SilentDeath_1\nT_Artifact_SilentDeath_2\nT_Artifact_SilentDeath_3"
  },
  {
    "SetName": "Spellweaver",
    "SetId": "Cast",
    "IndividualBonus": null,
    "PerPieceBonus": "Cast Spd: <color=#AAFF00FF>+10% per level</color>",
    "PerRefineBonus": "Cast Spd: <color=#AAFF00FF>+0.25% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nCast Spd:",
    "Source": "Relic - Butterfly Fairy\nRune - Butterfly Hue\nRelic - Butterfly Pixie\nRune - Glow Wisp Yellow\nRune - Moth Celestial\nJewel - Moth Luna\nJewel - Moth Moon\nScroll - Sun Blossom\nScroll - Sunflower Fairy",
    "Droprate": "400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%",
    "Location": "Fairy Glen\nFairy Glen\nFairy Glen\nFairy Glen\nFairy Glen\nFairy Glen\nFairy Glen\nFairy Glen\nFairy Glen",
    "SpriteId": "T_Artifact_Spellweaver_0\nT_Artifact_Spellweaver_1\nT_Artifact_Spellweaver_2\nT_Artifact_Spellweaver_3"
  },
  {
    "SetName": "Spirit Pact",
    "SetId": "Summoner",
    "IndividualBonus": "Soul Strike Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nBanishment Field Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nResonance Well Healing: <color=#AAFF00FF>+5% + 2% per level</color>\nDissonance Well Damage: <color=#AAFF00FF>+5% + 2% per level</color>",
    "PerPieceBonus": null,
    "PerRefineBonus": null,
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+3</color>",
    "Source": null,
    "Droprate": null,
    "Location": null,
    "SpriteId": "T_Artifact_SpiritPact_0\nT_Artifact_SpiritPact_1\nT_Artifact_SpiritPact_2\nT_Artifact_SpiritPact_3"
  },
  {
    "SetName": "Starfire",
    "SetId": "Matk",
    "IndividualBonus": null,
    "PerPieceBonus": "Matk: <color=#AAFF00FF>+5 per level</color>\nMp: <color=#AAFF00FF>+5% per level</color>\nHp: <color=#FF0073FF>-10% per level</color>",
    "PerRefineBonus": "Matk: <color=#AAFF00FF>+0.25% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nMatk: <color=#AAFF00FF>+10</color>\nMp: <color=#AAFF00FF>+5%</color>\nHp: <color=#FF0073FF>-10%</color>\nEnergy Shield Level: <color=#AAFF00FF>+2</color>",
    "Source": "Rune - Cyclops Bat\nJewel - Cyclops Bat Mage\nScroll - Cyclops Bat Wizard\nJewel - Death\nJewel - Direwolf\nJewel - Eyeball Creep Blue\nScroll - Eyeball Creep Green\nRelic - Eyeball Creep Red\nScroll - Eyeball Mage Blue\nRelic - Eyeball Mage Green\nRune - Eyeball Mage Red\nRune - Gloom\nRune - Grim Reaper\nScroll - Mimic Barrel\nRune - Mimic Book\nRelic - Mimic Candle\nJewel - Mimic Living Trap\nRune - Mimic Sword\nJewel - Mimic Treasure Chest\nRune - Nightmare\nRune - Skeleton Giant\nRelic - Skeleton Mage",
    "Droprate": "200.0%\n100.0%\n200.0%\n200.0%\n100.0%\n100.0%\n100.0%\n100.0%\n100.0%\n100.0%\n100.0%\n100.0%\n100.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n200.0%\n100.0%\n200.0%\n200.0%",
    "Location": "Abyss Castle Keep\nAbyss Castle Library\nAbyss Castle Keep\nAbyss Castle Keep\nAbyss Castle Crypt\nAbyss Castle Crypt\nAbyss Castle Crypt\nAbyss Castle Crypt\nAbyss Castle Library\nAbyss Castle Library\nAbyss Castle Library\nAbyss Castle Crypt\nAbyss Castle Crypt\nAbyss Castle Dungeon\nAbyss Castle Dungeon\nAbyss Castle Dungeon\nAbyss Castle Dungeon\nAbyss Castle Dungeon\nAbyss Castle Dungeon\nAbyss Castle Library\nAbyss Castle Keep\nAbyss Castle Keep",
    "SpriteId": "T_Artifact_Starfire_0\nT_Artifact_Starfire_1\nT_Artifact_Starfire_2\nT_Artifact_Starfire_3"
  },
  {
    "SetName": "Steelheart",
    "SetId": "Melee",
    "IndividualBonus": null,
    "PerPieceBonus": "Damage Melee: <color=#AAFF00FF>+3% per level</color>",
    "PerRefineBonus": "Damage Melee: <color=#AAFF00FF>+0.125% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nDamage Melee: <color=#AAFF00FF>+3%</color>",
    "Source": "Scroll - Flower Pot Monster\nRune - Rat Dark\nRelic - Rat Dark\nJewel - Rat Grey\nScroll - Rat White\nRune - Treant Forest Autumn\nJewel - Treant Forest Evergreen\nRune - Treant Minion Autumn\nJewel - Treant Minion Evergreen\nScroll - Treant Tree Autumn\nRelic - Treant Tree Evergreen",
    "Droprate": "600.0%\n600.0%\n600.0%\n600.0%\n600.0%\n600.0%\n600.0%\n600.0%\n600.0%\n600.0%\n600.0%",
    "Location": "Treant Trail\nNevaris Sewers\nNevaris Sewers\nNevaris Sewers\nNevaris Sewers\nTreant Trail\nTreant Trail\nTreant Trail\nTreant Trail\nTreant Trail\nTreant Trail",
    "SpriteId": "T_Artifact_Steelheart_0\nT_Artifact_Steelheart_1\nT_Artifact_Steelheart_2\nT_Artifact_Steelheart_3"
  },
  {
    "SetName": "Stormquiver",
    "SetId": "Ranged",
    "IndividualBonus": null,
    "PerPieceBonus": "Damage Ranged: <color=#AAFF00FF>+3% per level</color>",
    "PerRefineBonus": "Damage Ranged: <color=#AAFF00FF>+0.125% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nDamage Ranged: <color=#AAFF00FF>+3%</color>",
    "Source": "Relic - Cat Lightning\nRelic - Dog Bowwow\nJewel - Glow Wisp Purple\nJewel - Mole Rat\nRune - Mole Rat King\nScroll - Scorpion\nRune - Scorpling\nRune - Whirlwind\nScroll - Wind\nRune - Wind Mage",
    "Droprate": "400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%",
    "Location": "Windy Desert\nWindy Desert North\nWindy Desert\nWindy Desert North\nWindy Desert North\nWindy Desert North\nWindy Desert North\nWindy Desert\nWindy Desert\nWindy Desert",
    "SpriteId": "T_Artifact_Stormquiver_0\nT_Artifact_Stormquiver_1\nT_Artifact_Stormquiver_2\nT_Artifact_Stormquiver_3"
  },
  {
    "SetName": "Tempest Engine",
    "SetId": "Wizard_1",
    "IndividualBonus": "Tempest Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nChain Lightning Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nThunder Storm Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nCast Spd: <color=#AAFF00FF>+1% per level</color>",
    "PerPieceBonus": null,
    "PerRefineBonus": null,
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+3</color>\n<color=#B2B2B2FF>Tempest and Chain Lightning build Tempest Engine, increasing their power and MP cost. Chain Lightning also triggers Thunder Storm.</color>\n\nTempest applies <color=#AAFF00FF>Tempest Engine</color> for <color=#AAFF00FF>10 seconds</color>\nChain Lightning applies <color=#AAFF00FF>Tempest Engine</color> for <color=#AAFF00FF>10 seconds</color>\n<color=#AAFF00FF>30%</color> chance to Autocast <color=#AAFF00FF>Thunder Storm</color> with <color=#AAFF00FF>Chain Lightning</color> hits\n-----------------------------------------------------\n<color=#C37CFFFF>Tempest Engine</color>\n<color=#B2B2B2FF>Stackable (max 5 stacks)</color>\nChain Lightning Damage: <color=#AAFF00FF>+10%</color>\nChain Lightning Mana Cost: <color=#FF0073FF>+30%</color>\nTempest Damage: <color=#AAFF00FF>+10%</color>\nTempest Mana Cost: <color=#FF0073FF>+30%</color>\nDuration: <color=#AAFF00FF>10 seconds</color>\n-----------------------------------------------------\n<color=#00E2FFFF>Thunder Storm</color>\n<color=#B2B2B2FF>Call down a storm of lightning over an area, striking enemies and exposing them to Water damage.</color>\n\nType: <color=#00E2FFFF>Magic</color>\nElement: <sprite name=Elements_7> <color=#FFC701FF>Wind</color>\nDamage: <color=#AAFF00FF>250% MATK per level</color>\nHits: <color=#AAFF00FF>1 per level</color>\nArea: <color=#AAFF00FF>5</color>\nCost: <color=#AAFF00FF>30 + 15 mana per level</color>\n-----------------------------------------------------\n<color=#FFD900FF>Status Effects</color>\n<color=#C37CFFFF>Water Exposure</color>\nWater Resistance: <color=#FF0073FF>-4% per level</color>\nDuration: <color=#AAFF00FF>10 seconds</color>\nStr:",
    "Source": "Crafted",
    "Droprate": null,
    "Location": null,
    "SpriteId": "artifacts-wizard-1_0\nartifacts-wizard-1_1\nartifacts-wizard-1_2\nartifacts-wizard-1_3"
  },
  {
    "SetName": "Titanplate",
    "SetId": "Def",
    "IndividualBonus": null,
    "PerPieceBonus": "Def: <color=#AAFF00FF>+15 per level</color>",
    "PerRefineBonus": "Def: <color=#AAFF00FF>+1 per level</color>\nReflect Damage: <color=#AAFF00FF>+1% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nDef: <color=#AAFF00FF>+5%</color>\nStr:\nReflect Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Rune - Cacti\nScroll - Cactus\nRune - Golem Earth\nRelic - Plant Chewer\nJewel - Spore",
    "Droprate": "400.0%\n400.0%\n400.0%\n400.0%\n400.0%",
    "Location": "Windy Desert South\nWindy Desert South\nWindy Desert South\nWindy Desert South\nWindy Desert South",
    "SpriteId": "T_Artifact_Titanplate_0\nT_Artifact_Titanplate_1\nT_Artifact_Titanplate_2\nT_Artifact_Titanplate_3"
  },
  {
    "SetName": "Umbral Veil",
    "SetId": "Shinobi_1",
    "IndividualBonus": "Flame Orb Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nBinding Spiral Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nFlash Step Damage: <color=#AAFF00FF>+5% + 2% per level</color>\nBlack Blade Damage: <color=#AAFF00FF>+5% + 2% per level</color>",
    "PerPieceBonus": null,
    "PerRefineBonus": null,
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+3</color>\nStr:",
    "Source": "Crafted",
    "Droprate": null,
    "Location": null,
    "SpriteId": "artifacts-shinobi-1_0\nartifacts-shinobi-1_1\nartifacts-shinobi-1_3\nartifacts-shinobi-1_4"
  },
  {
    "SetName": "Vampiric",
    "SetId": "Vampiric",
    "IndividualBonus": null,
    "PerPieceBonus": "Health leech: <color=#AAFF00FF>+3% per level</color>",
    "PerRefineBonus": "Health leech: <color=#AAFF00FF>+0.125% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nHealth leech: <color=#AAFF00FF>+3%</color>",
    "Source": "Scroll - Abomination\nRune - Monster Bat\nRelic - Monster Bat\nRune - Monster Bat King\nRelic - Monster Bat King\nJewel - Zombie Goblin Giant\nJewel - Zombie Goblin Minion\nScroll - Zombie Goblin Soldier",
    "Droprate": "400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%",
    "Location": "Goblin Cave 2\nGoblin Cave 1\nGoblin Cave 1\nGoblin Cave 2\nGoblin Cave 2\nGoblin Cave 2\nGoblin Cave 1\nGoblin Cave 1",
    "SpriteId": "T_Artifact_Vampiric_0\nT_Artifact_Vampiric_1\nT_Artifact_Vampiric_2\nT_Artifact_Vampiric_3"
  },
  {
    "SetName": "Veilward",
    "SetId": "Mdef",
    "IndividualBonus": null,
    "PerPieceBonus": "Mdef: <color=#AAFF00FF>+15 per level</color>",
    "PerRefineBonus": "Mdef: <color=#AAFF00FF>+1 per level</color>\nChance to reflect single target magic: <color=#AAFF00FF>+0.5% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nMdef: <color=#AAFF00FF>+5%</color>\nStr:\nChance to reflect single target magic: <color=#AAFF00FF>+5%</color>",
    "Source": "Scroll - Cyclops\nJewel - Cyclops Giant\nRelic - Cyclops Minion\nRune - Dragon Blizzard\nJewel - Dragon Ice\nScroll - Dragon Water\nRelic - Elder Wisp Blue\nScroll - Golem Ice\nRune - Ice\nRune - Icicle\nJewel - Snow Bomb",
    "Droprate": "300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%\n300.0%",
    "Location": "Crystal Cave\nCrystal Cave\nCrystal Cave\nCrystal Cave\nCrystal Cave\nCrystal Cave\nCrystal Cave\nCrystal Cave\nCrystal Cave\nCrystal Cave\nCrystal Cave",
    "SpriteId": "T_Artifact_Veilward_0\nT_Artifact_Veilward_1\nT_Artifact_Veilward_2\nT_Artifact_Veilward_3"
  },
  {
    "SetName": "Vitalis",
    "SetId": "Hp",
    "IndividualBonus": null,
    "PerPieceBonus": "Hp: <color=#AAFF00FF>+10% per level</color>",
    "PerRefineBonus": "Hp: <color=#AAFF00FF>+0.25% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nHp:",
    "Source": "Jewel - Goblin Giant\nScroll - Goblin Giant Devil\nRune - Goblin Giant Mage\nRelic - Goblin Giant Mage\nRune - Goblin Minion\nRelic - Goblin Trooper\nScroll - Goblin Trooper Assassin\nJewel - Goblin Trooper Mage\nRune - Goblin Trooper Soldier",
    "Droprate": "400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%\n400.0%",
    "Location": "Goblin Village\nGoblin Village\nGoblin Village\nGoblin Village\nGoblin Field\nGoblin Field\nGoblin Field\nGoblin Field\nGoblin Field",
    "SpriteId": "T_Artifact_Vitalis_0\nT_Artifact_Vitalis_1\nT_Artifact_Vitalis_2\nT_Artifact_Vitalis_3"
  },
  {
    "SetName": "Warglyph",
    "SetId": "Atk",
    "IndividualBonus": null,
    "PerPieceBonus": "Atk: <color=#AAFF00FF>+5 per level</color>\nHp: <color=#AAFF00FF>+5% per level</color>\nMp: <color=#FF0073FF>-15% per level</color>",
    "PerRefineBonus": "Atk: <color=#AAFF00FF>+0.25% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nAtk: <color=#AAFF00FF>+10</color>\nHp: <color=#AAFF00FF>+5%</color>\nMp: <color=#FF0073FF>-15%</color>",
    "Source": "Jewel - Goblin Warblade\nScroll - Goblin Warcrusher\nRune - Goblin Warlock\nRelic - Goblin Warlock",
    "Droprate": "100.0%\n100.0%\n100.0%\n100.0%",
    "Location": "Goblin Warcamp\nGoblin Warcamp\nGoblin Warcamp\nGoblin Warcamp",
    "SpriteId": "T_Artifact_Warglyph_0\nT_Artifact_Warglyph_1\nT_Artifact_Warglyph_2\nT_Artifact_Warglyph_3"
  },
  {
    "SetName": "Windborne",
    "SetId": "Movespeed",
    "IndividualBonus": null,
    "PerPieceBonus": "Move Spd: <color=#AAFF00FF>+5% per level</color>",
    "PerRefineBonus": "Move Spd: <color=#AAFF00FF>+0.25% per level</color>",
    "FullSetBonus": "All Stats: <color=#AAFF00FF>+1</color>\nMove Spd:",
    "Source": "Rune - Bunny\nRelic - Bunny\nJewel - Egglet\nScroll - Rabbit",
    "Droprate": "600.0%\n600.0%\n600.0%\n600.0%",
    "Location": "Bunny Woods\nBunny Woods\nBunny Woods\nBunny Woods",
    "SpriteId": "T_Artifact_Windbourne_0\nT_Artifact_Windbourne_1\nT_Artifact_Windbourne_2\nT_Artifact_Windbourne_3"
  }
];
