const cardData = [
    {
        "Name": "Angel Card",
        "CardId": "Angel",
        "Affix": "Blessed",
        "Slot": "Weapon",
        "Stats": "Healing: <color=#AAFF00FF>+10%</color>",
        "Source": "Angel",
        "Droprate": "100%",
        "Location": "Sanctum of Light",
        "SpriteId": "card"
    },
    {
        "Name": "Angel Mage Card",
        "CardId": "Angel Mage",
        "Affix": "Pure",
        "Slot": "Chest",
        "Stats": "<color=#FFFFFFFF>Convert to <sprite name=Elements_2> <color=#FCE9EBFF>Holy</color> element</color>",
        "Source": "Angel Mage",
        "Droprate": "300%",
        "Location": "Sanctum of Light",
        "SpriteId": "card_gold"
    },
    {
        "Name": "Archangel Card",
        "CardId": "Archangel",
        "Affix": "Pure",
        "Slot": "Weapon",
        "Stats": "<color=#FFFFFFFF>Enchant weapon with <sprite name=Elements_2> <color=#FCE9EBFF>Holy</color> element</color>",
        "Source": "Archangel",
        "Droprate": "100%",
        "Location": "Sanctum of Light",
        "SpriteId": "card"
    },
    {
        "Name": "Bat Card",
        "CardId": "Bat",
        "Affix": "Leeching",
        "Slot": "Accessory",
        "Stats": "Mana on kill: <color=#AAFF00FF>+20</color>",
        "Source": "Bat",
        "Droprate": "100%",
        "Location": "Forgotten Depths",
        "SpriteId": "card"
    },
    {
        "Name": "Bat Lord Card",
        "CardId": "Bat Lord",
        "Affix": "Siphoning",
        "Slot": "Accessory",
        "Stats": "Mana on hit: <color=#AAFF00FF>+3</color>",
        "Source": "Bat Lord",
        "Droprate": "300%",
        "Location": "Forgotten Depths",
        "SpriteId": "card_gold"
    },
    {
        "Name": "Bee Card",
        "CardId": "Bee",
        "Affix": "Accurate",
        "Slot": "Weapon",
        "Stats": "Hit: <color=#AAFF00FF>+25</color>",
        "Source": "Bee",
        "Droprate": "100%",
        "Location": "Forest Labyrinth",
        "SpriteId": "card"
    },
    {
        "Name": "Bird Card",
        "CardId": "Bird",
        "Affix": "Lancer",
        "Slot": "Weapon",
        "Stats": "Weapon Throw Damage: <color=#AAFF00FF>+12%</color>",
        "Source": "Bird",
        "Droprate": "100%",
        "Location": "Forest Labyrinth",
        "SpriteId": "card"
    },
    {
        "Name": "Bloom Card",
        "CardId": "Bloom",
        "Affix": "Volley",
        "Slot": "Weapon",
        "Stats": "Strafing Volley Damage: <color=#AAFF00FF>+12%</color>",
        "Source": "Bloom",
        "Droprate": "100%",
        "Location": "Underground Cavern",
        "SpriteId": "card"
    },
    {
        "Name": "Blossom Card",
        "CardId": "Blossom",
        "Affix": "Volatile",
        "Slot": "Legs",
        "Stats": "Volatile Bolt Damage: <color=#AAFF00FF>+12%</color>",
        "Source": "Blossom",
        "Droprate": "100%",
        "Location": "Underground Cavern",
        "SpriteId": "card"
    },
    {
        "Name": "Bomb Card",
        "CardId": "Bomb",
        "Affix": "Power",
        "Slot": "Weapon",
        "Stats": "Atk: <color=#AAFF00FF>+5%</color>",
        "Source": "Bomb",
        "Droprate": "100%",
        "Location": "Sanctum of Light",
        "SpriteId": "card"
    },
    {
        "Name": "Bud Card",
        "CardId": "Bud",
        "Affix": "Light",
        "Slot": "Legs",
        "Stats": "Weight Limit: <color=#AAFF00FF>+1000</color>",
        "Source": "Bud",
        "Droprate": "100%",
        "Location": "Underground Cavern",
        "SpriteId": "card"
    },
    {
        "Name": "Bumble Card",
        "CardId": "Bumble",
        "Affix": "Sniper",
        "Slot": "Back",
        "Stats": "Total Hit: <color=#AAFF00FF>+10%</color>",
        "Source": "Bumble",
        "Droprate": "100%",
        "Location": "Forest Labyrinth",
        "SpriteId": "card"
    },
    {
        "Name": "Bunny Card",
        "CardId": "Bunny",
        "Affix": "Rapid",
        "Slot": "Accessory",
        "Stats": "Atk Spd: <color=#AAFF00FF>+5%</color>",
        "Source": "Bunny",
        "Droprate": "100%",
        "Location": "Sunny Meadows",
        "SpriteId": "card"
    },
    {
        "Name": "Burrow Card",
        "CardId": "Burrow",
        "Affix": "Steadfast",
        "Slot": "Back",
        "Stats": "Mp: <color=#FF0073FF>-25%</color>\nResistance to Stun: <color=#AAFF00FF>+100%</color>",
        "Source": "Burrow",
        "Droprate": "100%",
        "Location": "Forest Labyrinth",
        "SpriteId": "card"
    },
    {
        "Name": "Butterfly Fairy Card",
        "CardId": "Butterfly Fairy",
        "Affix": "Wizardry",
        "Slot": "Chest",
        "Stats": "Cast Spd: <color=#AAFF00FF>+15%</color>",
        "Source": "Butterfly Fairy",
        "Droprate": "100%",
        "Location": "Fairy Glen",
        "SpriteId": "card"
    },
    {
        "Name": "Butterfly Hue Card",
        "CardId": "Butterfly Hue",
        "Affix": "Wizardry",
        "Slot": "Weapon",
        "Stats": "Cast Spd: <color=#AAFF00FF>+10%</color>",
        "Source": "Butterfly Hue",
        "Droprate": "100%",
        "Location": "Forest Labyrinth",
        "SpriteId": "card"
    },
    {
        "Name": "Butterfly Pixie Card",
        "CardId": "Butterfly Pixie",
        "Affix": "Wizardry",
        "Slot": "Head",
        "Stats": "Cast Spd: <color=#AAFF00FF>+15%</color>",
        "Source": "Butterfly Pixie",
        "Droprate": "100%",
        "Location": "Fairy Glen",
        "SpriteId": "card"
    },
    {
        "Name": "Cacti Card",
        "CardId": "Cacti",
        "Affix": "Spiked",
        "Slot": "Shield",
        "Stats": "Reflect Damage: <color=#AAFF00FF>+2% per level</color>",
        "Source": "Cacti",
        "Droprate": "100%",
        "Location": "Windy Desert",
        "SpriteId": "card"
    },
    {
        "Name": "Cactus Boss Card",
        "CardId": "Cactus Boss",
        "Affix": "Counter",
        "Slot": "Shield",
        "Stats": "<color=#FFFFFFFF>Grants <color=#AAFF00FF>Lv.1 Counter Stance</color></color>",
        "Source": "Cactus Boss",
        "Droprate": "300%",
        "Location": "Windy Desert",
        "SpriteId": "card_gold"
    },
    {
        "Name": "Cactus Card",
        "CardId": "Cactus",
        "Affix": "Mudproof",
        "Slot": "Shield",
        "Stats": "Earth Resistance: <color=#AAFF00FF>+25%</color>",
        "Source": "Cactus",
        "Droprate": "100%",
        "Location": "Windy Desert",
        "SpriteId": "card"
    },
    {
        "Name": "Cat Bolt Card",
        "CardId": "Cat Bolt",
        "Affix": "Spark",
        "Slot": "Chest",
        "Stats": "<color=#FFFFFFFF>Convert to <sprite name=Elements_7> <color=#FFC701FF>Wind</color> element</color>",
        "Source": "Cat Bolt",
        "Droprate": "300%",
        "Location": "Windy Desert",
        "SpriteId": "card_gold"
    },
    {
        "Name": "Cat Lightning Card",
        "CardId": "Cat Lightning",
        "Affix": "Windproof",
        "Slot": "Shield",
        "Stats": "Wind Resistance: <color=#AAFF00FF>+25%</color>",
        "Source": "Cat Lightning",
        "Droprate": "100%",
        "Location": "Windy Desert",
        "SpriteId": "card"
    },
    {
        "Name": "Cat Meow Card",
        "CardId": "Cat Meow",
        "Affix": "Shocking",
        "Slot": "Weapon",
        "Stats": "<color=#FFFFFFFF>Grants <color=#AAFF00FF>Lv.3 Thunderbolt</color></color>\nChance to autocast Thunderbolt when attacking: <color=#AAFF00FF>+10%</color>",
        "Source": "Cat Meow",
        "Droprate": "100%",
        "Location": "Forest Labyrinth",
        "SpriteId": "card"
    },
    {
        "Name": "Chick Card",
        "CardId": "Chick",
        "Affix": "Sharp",
        "Slot": "Weapon",
        "Stats": "Atk: <color=#AAFF00FF>+5</color>",
        "Source": "Chick",
        "Droprate": "100%",
        "Location": "Sunny Meadows",
        "SpriteId": "card"
    },
    {
        "Name": "Creeper Card",
        "CardId": "Creeper",
        "Affix": "Savage",
        "Slot": "Weapon",
        "Stats": "Crit Damage: <color=#AAFF00FF>+8%</color>",
        "Source": "Creeper",
        "Droprate": "100%",
        "Location": "Forgotten Depths",
        "SpriteId": "card"
    },
    {
        "Name": "Cyclops Bat Card",
        "CardId": "Cyclops Bat",
        "Affix": "Melee",
        "Slot": "Weapon",
        "Stats": "Damage Melee: <color=#AAFF00FF>+6%</color>",
        "Source": "Cyclops Bat",
        "Droprate": "100%",
        "Location": "Abyss Castle Keep",
        "SpriteId": "card"
    },
    {
        "Name": "Cyclops Bat Mage Card",
        "CardId": "Cyclops Bat Mage",
        "Affix": "Magic",
        "Slot": "Weapon",
        "Stats": "Damage Magic: <color=#AAFF00FF>+6%</color>",
        "Source": "Cyclops Bat Mage",
        "Droprate": "100%",
        "Location": "Abyss Castle Library",
        "SpriteId": "card"
    },
    {
        "Name": "Cyclops Bat Wizard Card",
        "CardId": "Cyclops Bat Wizard",
        "Affix": "Ranged",
        "Slot": "Weapon",
        "Stats": "Damage Ranged: <color=#AAFF00FF>+6%</color>",
        "Source": "Cyclops Bat Wizard",
        "Droprate": "100%",
        "Location": "Abyss Castle Keep",
        "SpriteId": "card"
    },
    {
        "Name": "Cyclops Card",
        "CardId": "Cyclops",
        "Affix": "Warding",
        "Slot": "Head",
        "Stats": "Mdef: <color=#AAFF00FF>+15%</color>",
        "Source": "Cyclops",
        "Droprate": "100%",
        "Location": "Crystal Cave",
        "SpriteId": "card"
    },
    {
        "Name": "Cyclops Giant Card",
        "CardId": "Cyclops Giant",
        "Affix": "Warding",
        "Slot": "Shield",
        "Stats": "Mdef: <color=#AAFF00FF>+3% per level</color>",
        "Source": "Cyclops Giant",
        "Droprate": "100%",
        "Location": "Crystal Cave",
        "SpriteId": "card"
    },
    {
        "Name": "Cyclops Minion Card",
        "CardId": "Cyclops Minion",
        "Affix": "Warding",
        "Slot": "Chest",
        "Stats": "Mdef: <color=#AAFF00FF>+15%</color>",
        "Source": "Cyclops Minion",
        "Droprate": "100%",
        "Location": "Crystal Cave",
        "SpriteId": "card"
    },
    {
        "Name": "Death Card",
        "CardId": "Death",
        "Affix": "Darkproof",
        "Slot": "Legs",
        "Stats": "Shadow Resistance: <color=#AAFF00FF>+15%</color>",
        "Source": "Death",
        "Droprate": "100%",
        "Location": "Abyss Castle Keep",
        "SpriteId": "card"
    },
    {
        "Name": "Death Mage Card",
        "CardId": "Death Mage",
        "Affix": "Cloaking",
        "Slot": "Back",
        "Stats": "<color=#FFFFFFFF>Grants <color=#AAFF00FF>Lv.1 Cloaking</color></color>",
        "Source": "Death Mage",
        "Droprate": "300%",
        "Location": "Abyss Castle Library",
        "SpriteId": "card_gold"
    },
    {
        "Name": "Direwolf Card",
        "CardId": "Direwolf",
        "Affix": "Cloaking",
        "Slot": "Accessory",
        "Stats": "<color=#FFFFFFFF>Become undetectable even by shadow monsters when invisible</color>",
        "Source": "Direwolf",
        "Droprate": "100%",
        "Location": "Abyss Castle Crypt",
        "SpriteId": "card"
    },
    {
        "Name": "Dog Bark Card",
        "CardId": "Dog Bark",
        "Affix": "Flaming",
        "Slot": "Back",
        "Stats": "<color=#FFFFFFFF>Grants <color=#AAFF00FF>Lv.3 Fireball</color></color>",
        "Source": "Dog Bark",
        "Droprate": "100%",
        "Location": "Forest Labyrinth",
        "SpriteId": "card"
    },
    {
        "Name": "Dog Bowwow Card",
        "CardId": "Dog Bowwow",
        "Affix": "Blazing",
        "Slot": "Weapon",
        "Stats": "<color=#FFFFFFFF>Enchant weapon with <sprite name=Elements_5> <color=#FF7026FF>Fire</color> element</color>",
        "Source": "Dog Bowwow",
        "Droprate": "100%",
        "Location": "Windy Desert",
        "SpriteId": "card"
    },
    {
        "Name": "Dog Pup Card",
        "CardId": "Dog Pup",
        "Affix": "Flaming",
        "Slot": "Weapon",
        "Stats": "<color=#FFFFFFFF>Grants <color=#AAFF00FF>Lv.3 Firebolt</color></color>\nChance to autocast Firebolt when attacking: <color=#AAFF00FF>+10%</color>",
        "Source": "Dog Pup",
        "Droprate": "100%",
        "Location": "Forest Labyrinth",
        "SpriteId": "card"
    },
    {
        "Name": "Dragon Blizzard Card",
        "CardId": "Dragon Blizzard",
        "Affix": "Diamond",
        "Slot": "Chest",
        "Stats": "Resistance to Frozen: <color=#AAFF00FF>+100%</color>",
        "Source": "Dragon Blizzard",
        "Droprate": "100%",
        "Location": "Crystal Cave",
        "SpriteId": "card"
    },
    {
        "Name": "Dragon Darkness Card",
        "CardId": "Dragon Darkness",
        "Affix": "Tainted",
        "Slot": "Weapon",
        "Stats": "<color=#FFFFFFFF>Enchant weapon with <sprite name=Elements_3> <color=#755E94FF>Shadow</color> element</color>",
        "Source": "Dragon Darkness",
        "Droprate": "100%",
        "Location": "Sanctum of Light",
        "SpriteId": "card"
    },
    {
        "Name": "Dragon Dusk Card",
        "CardId": "Dragon Dusk",
        "Affix": "Exorcist's",
        "Slot": "Weapon",
        "Stats": "Damage vs Shadow Enemies: <color=#AAFF00FF>+10%</color>",
        "Source": "Dragon Dusk",
        "Droprate": "100%",
        "Location": "Sanctum of Light",
        "SpriteId": "card"
    },
    {
        "Name": "Dragon Fire Card",
        "CardId": "Dragon Fire",
        "Affix": "Fireproof",
        "Slot": "Legs",
        "Stats": "Fire Resistance: <color=#AAFF00FF>+15%</color>",
        "Source": "Dragon Fire",
        "Droprate": "100%",
        "Location": "Demon's Maw",
        "SpriteId": "card"
    },
    {
        "Name": "Dragon Ice Card",
        "CardId": "Dragon Ice",
        "Affix": "Icy",
        "Slot": "Legs",
        "Stats": "Ice Shard Damage: <color=#AAFF00FF>+12%</color>",
        "Source": "Dragon Ice",
        "Droprate": "100%",
        "Location": "Crystal Cave",
        "SpriteId": "card"
    },
    {
        "Name": "Dragon Inferno Card",
        "CardId": "Dragon Inferno",
        "Affix": "Power",
        "Slot": "Accessory",
        "Stats": "Atk: <color=#AAFF00FF>+5%</color>",
        "Source": "Dragon Inferno",
        "Droprate": "100%",
        "Location": "Demon's Maw",
        "SpriteId": "card"
    },
    {
        "Name": "Dragon Nightfall Card",
        "CardId": "Dragon Nightfall",
        "Affix": "Purifying",
        "Slot": "Head",
        "Stats": "Resistance to Curse: <color=#AAFF00FF>+100%</color>",
        "Source": "Dragon Nightfall",
        "Droprate": "100%",
        "Location": "Sanctum of Light",
        "SpriteId": "card"
    },
    {
        "Name": "Dragon Water Card",
        "CardId": "Dragon Water",
        "Affix": "Waterproof",
        "Slot": "Legs",
        "Stats": "Water Resistance: <color=#AAFF00FF>+15%</color>",
        "Source": "Dragon Water",
        "Droprate": "100%",
        "Location": "Crystal Cave",
        "SpriteId": "card"
    },
    {
        "Name": "Dragonfly Arrow Card",
        "CardId": "Dragonfly Arrow",
        "Affix": "Nimble",
        "Slot": "Feet",
        "Stats": "Agi: <color=#AAFF00FF>+1</color>\nFlee: <color=#AAFF00FF>+10</color>",
        "Source": "Dragonfly Arrow",
        "Droprate": "100%",
        "Location": "Swamp",
        "SpriteId": "card"
    },
    {
        "Name": "Dragonfly Darner Card",
        "CardId": "Dragonfly Darner",
        "Affix": "Elusive",
        "Slot": "Legs",
        "Stats": "Flee: <color=#AAFF00FF>+15</color>",
        "Source": "Dragonfly Darner",
        "Droprate": "100%",
        "Location": "Swamp",
        "SpriteId": "card"
    },
    {
        "Name": "Dragonfly Swift Card",
        "CardId": "Dragonfly Swift",
        "Affix": "Elusive",
        "Slot": "Shield",
        "Stats": "Flee: <color=#AAFF00FF>+25</color>",
        "Source": "Dragonfly Swift",
        "Droprate": "100%",
        "Location": "Swamp",
        "SpriteId": "card"
    },
    {
        "Name": "Earthworm Card",
        "CardId": "Earthworm",
        "Affix": "Anti-Venom",
        "Slot": "Back",
        "Stats": "Resistance to Poison: <color=#AAFF00FF>+100%</color>",
        "Source": "Earthworm",
        "Droprate": "100%",
        "Location": "Swamp",
        "SpriteId": "card"
    },
    {
        "Name": "Egg Card",
        "CardId": "Egg",
        "Affix": "Vital",
        "Slot": "Head",
        "Stats": "Hp: <color=#AAFF00FF>+100</color>",
        "Source": "Egg",
        "Droprate": "100%",
        "Location": "Sunny Meadows",
        "SpriteId": "card"
    },
    {
        "Name": "Egglet Card",
        "CardId": "Egglet",
        "Affix": "Rapid",
        "Slot": "Weapon",
        "Stats": "Atk Spd: <color=#AAFF00FF>+5%</color>\nStr: <color=#AAFF00FF>+1</color>",
        "Source": "Egglet",
        "Droprate": "100%",
        "Location": "Forest Labyrinth",
        "SpriteId": "card"
    },
    {
        "Name": "Elder Wisp Blue Card",
        "CardId": "Elder Wisp Blue",
        "Affix": "Glacial",
        "Slot": "Accessory",
        "Stats": "Water Damage: <color=#AAFF00FF>+8%</color>",
        "Source": "Elder Wisp Blue",
        "Droprate": "100%",
        "Location": "Crystal Cave",
        "SpriteId": "card"
    },
    {
        "Name": "Elder Wisp Purple Card",
        "CardId": "Elder Wisp Purple",
        "Affix": "Tempest",
        "Slot": "Accessory",
        "Stats": "Wind Damage: <color=#AAFF00FF>+8%</color>",
        "Source": "Elder Wisp Purple",
        "Droprate": "100%",
        "Location": "Underground Cavern",
        "SpriteId": "card"
    },
    {
        "Name": "Elder Wisp Yellow Card",
        "CardId": "Elder Wisp Yellow",
        "Affix": "Pyre",
        "Slot": "Accessory",
        "Stats": "Fire Damage: <color=#AAFF00FF>+8%</color>",
        "Source": "Elder Wisp Yellow",
        "Droprate": "100%",
        "Location": "Demon's Maw",
        "SpriteId": "card"
    },
    {
        "Name": "Eyeball Bat Blue Card",
        "CardId": "Eyeball Bat Blue",
        "Affix": "Radiant",
        "Slot": "Weapon",
        "Stats": "Holy Light Damage: <color=#AAFF00FF>+12%</color>",
        "Source": "Eyeball Bat Blue",
        "Droprate": "100%",
        "Location": "Festering Woods",
        "SpriteId": "card"
    },
    {
        "Name": "Eyeball Bat Green Card",
        "CardId": "Eyeball Bat Green",
        "Affix": "Purity",
        "Slot": "Shield",
        "Stats": "Undead Resistance: <color=#AAFF00FF>+25%</color>",
        "Source": "Eyeball Bat Green",
        "Droprate": "100%",
        "Location": "Festering Woods",
        "SpriteId": "card"
    },
    {
        "Name": "Eyeball Bat Red Card",
        "CardId": "Eyeball Bat Red",
        "Affix": "Vampiric",
        "Slot": "Shield",
        "Stats": "Chance to autocast Life Drain when hit: <color=#AAFF00FF>+1% per level</color>",
        "Source": "Eyeball Bat Red",
        "Droprate": "100%",
        "Location": "Festering Woods",
        "SpriteId": "card"
    },
    {
        "Name": "Eyeball Creep Blue Card",
        "CardId": "Eyeball Creep Blue",
        "Affix": "Focus",
        "Slot": "Head",
        "Stats": "Mp: <color=#AAFF00FF>+10%</color>",
        "Source": "Eyeball Creep Blue",
        "Droprate": "100%",
        "Location": "Abyss Castle Crypt",
        "SpriteId": "card"
    },
    {
        "Name": "Eyeball Creep Green Card",
        "CardId": "Eyeball Creep Green",
        "Affix": "Focus",
        "Slot": "Accessory",
        "Stats": "Mp: <color=#AAFF00FF>+10%</color>",
        "Source": "Eyeball Creep Green",
        "Droprate": "100%",
        "Location": "Abyss Castle Crypt",
        "SpriteId": "card"
    },
    {
        "Name": "Eyeball Creep Red Card",
        "CardId": "Eyeball Creep Red",
        "Affix": "Focus",
        "Slot": "Feet",
        "Stats": "Mp: <color=#AAFF00FF>+10%</color>",
        "Source": "Eyeball Creep Red",
        "Droprate": "100%",
        "Location": "Abyss Castle Crypt",
        "SpriteId": "card"
    },
    {
        "Name": "Eyeball Mage Blue Card",
        "CardId": "Eyeball Mage Blue",
        "Affix": "Mana Burn",
        "Slot": "Back",
        "Stats": "Mana on hit: <color=#AAFF00FF>+3</color>\nMp: <color=#FF0073FF>-50%</color>",
        "Source": "Eyeball Mage Blue",
        "Droprate": "100%",
        "Location": "Abyss Castle Library",
        "SpriteId": "card"
    },
    {
        "Name": "Eyeball Mage Green Card",
        "CardId": "Eyeball Mage Green",
        "Affix": "Radiant",
        "Slot": "Legs",
        "Stats": "Exorcism Damage: <color=#AAFF00FF>+12%</color>",
        "Source": "Eyeball Mage Green",
        "Droprate": "100%",
        "Location": "Abyss Castle Library",
        "SpriteId": "card"
    },
    {
        "Name": "Eyeball Mage Red Card",
        "CardId": "Eyeball Mage Red",
        "Affix": "Vampiric",
        "Slot": "Shield",
        "Stats": "Health leech chance: <color=#AAFF00FF>+10%</color>\nHealth leech power: <color=#AAFF00FF>+5%</color>",
        "Source": "Eyeball Mage Red",
        "Droprate": "100%",
        "Location": "Abyss Castle Library",
        "SpriteId": "card"
    },
    {
        "Name": "Fire Card",
        "CardId": "Fire",
        "Affix": "Light",
        "Slot": "Head",
        "Stats": "Weight Limit: <color=#AAFF00FF>+1000</color>",
        "Source": "Fire",
        "Droprate": "100%",
        "Location": "Demon's Maw",
        "SpriteId": "card"
    },
    {
        "Name": "Fire Mage Card",
        "CardId": "Fire Mage",
        "Affix": "Magic",
        "Slot": "Accessory",
        "Stats": "Matk: <color=#AAFF00FF>+5%</color>",
        "Source": "Fire Mage",
        "Droprate": "100%",
        "Location": "Demon's Maw",
        "SpriteId": "card"
    },
    {
        "Name": "Flame Card",
        "CardId": "Flame",
        "Affix": "Flaming",
        "Slot": "Legs",
        "Stats": "Fireball Damage: <color=#AAFF00FF>+12%</color>",
        "Source": "Flame",
        "Droprate": "100%",
        "Location": "Demon's Maw",
        "SpriteId": "card"
    },
    {
        "Name": "Fledgling Card",
        "CardId": "Fledgling",
        "Affix": "Impaling",
        "Slot": "Weapon",
        "Stats": "Impale Damage: <color=#AAFF00FF>+12%</color>",
        "Source": "Fledgling",
        "Droprate": "100%",
        "Location": "Forest Labyrinth",
        "SpriteId": "card"
    },
    {
        "Name": "Flora Card",
        "CardId": "Flora",
        "Affix": "Hoarfrost",
        "Slot": "Weapon",
        "Stats": "Damage vs Water Enemies: <color=#AAFF00FF>+10%</color>",
        "Source": "Flora",
        "Droprate": "100%",
        "Location": "Mystic Lake",
        "SpriteId": "card"
    },
    {
        "Name": "Flower Pot Monster Card",
        "CardId": "Flower Pot Monster",
        "Affix": "Quagmire",
        "Slot": "Back",
        "Stats": "<color=#FFFFFFFF>Grants <color=#AAFF00FF>Lv.3 Earth Spikes</color></color>",
        "Source": "Flower Pot Monster",
        "Droprate": "100%",
        "Location": "Forest Labyrinth",
        "SpriteId": "card"
    },
    {
        "Name": "Fungi Card",
        "CardId": "Fungi",
        "Affix": "Heal",
        "Slot": "Accessory",
        "Stats": "<color=#FFFFFFFF>Grants <color=#AAFF00FF>Lv.5 Heal</color></color>",
        "Source": "Fungi",
        "Droprate": "100%",
        "Location": "Mystic Lake",
        "SpriteId": "card"
    },
    {
        "Name": "Ghost Card",
        "CardId": "Ghost",
        "Affix": "Dissonance",
        "Slot": "Legs",
        "Stats": "Dissonance Well Damage: <color=#AAFF00FF>+12%</color>",
        "Source": "Ghost",
        "Droprate": "100%",
        "Location": "Sanctum of Light",
        "SpriteId": "card"
    },
    {
        "Name": "Glow Wisp Blue Card",
        "CardId": "Glow Wisp Blue",
        "Affix": "Glacial",
        "Slot": "Weapon",
        "Stats": "Water Damage: <color=#AAFF00FF>+8%</color>",
        "Source": "Glow Wisp Blue",
        "Droprate": "100%",
        "Location": "Mystic Lake",
        "SpriteId": "card"
    },
    {
        "Name": "Glow Wisp Purple Card",
        "CardId": "Glow Wisp Purple",
        "Affix": "Tempest",
        "Slot": "Weapon",
        "Stats": "Wind Damage: <color=#AAFF00FF>+8%</color>",
        "Source": "Glow Wisp Purple",
        "Droprate": "100%",
        "Location": "Windy Desert",
        "SpriteId": "card"
    },
    {
        "Name": "Glow Wisp Yellow Card",
        "CardId": "Glow Wisp Yellow",
        "Affix": "Pyre",
        "Slot": "Weapon",
        "Stats": "Fire Damage: <color=#AAFF00FF>+8%</color>",
        "Source": "Glow Wisp Yellow",
        "Droprate": "100%",
        "Location": "Fairy Glen",
        "SpriteId": "card"
    },
    {
        "Name": "Goblin Giant Devil Card",
        "CardId": "Goblin Giant Devil",
        "Affix": "Quaking",
        "Slot": "Weapon",
        "Stats": "Damage vs Earth Enemies: <color=#AAFF00FF>+10%</color>",
        "Source": "Goblin Giant Devil",
        "Droprate": "100%",
        "Location": "Goblin Village",
        "SpriteId": "card"
    },
    {
        "Name": "Goblin Giant Gold Card",
        "CardId": "Goblin Giant Gold",
        "Affix": "Earthen",
        "Slot": "Chest",
        "Stats": "<color=#FFFFFFFF>Convert to <sprite name=Elements_8> <color=#BB7B2FFF>Earth</color> element</color>",
        "Source": "Goblin Giant Gold",
        "Droprate": "300%",
        "Location": "Goblin Village",
        "SpriteId": "card_gold"
    },
    {
        "Name": "Goblin Giant Mage Card",
        "CardId": "Goblin Giant Mage",
        "Affix": "Quaking",
        "Slot": "Weapon",
        "Stats": "<color=#FFFFFFFF>Enchant weapon with <sprite name=Elements_8> <color=#BB7B2FFF>Earth</color> element</color>",
        "Source": "Goblin Giant Mage",
        "Droprate": "100%",
        "Location": "Goblin Village",
        "SpriteId": "card"
    },
    {
        "Name": "Goblin Minion Card",
        "CardId": "Goblin Minion",
        "Affix": "Bashing",
        "Slot": "Weapon",
        "Stats": "Bash Damage: <color=#AAFF00FF>+12%</color>",
        "Source": "Goblin Minion",
        "Droprate": "100%",
        "Location": "Goblin Village",
        "SpriteId": "card"
    },
    {
        "Name": "Goblin Trooper Assassin Card",
        "CardId": "Goblin Trooper Assassin",
        "Affix": "Mobile",
        "Slot": "Back",
        "Stats": "<color=#FFFFFFFF>Grants <color=#AAFF00FF>Lv.3 Shadow Step</color></color>",
        "Source": "Goblin Trooper Assassin",
        "Droprate": "100%",
        "Location": "Goblin Village",
        "SpriteId": "card"
    },
    {
        "Name": "Goblin Trooper Card",
        "CardId": "Goblin Trooper",
        "Affix": "Mudproof",
        "Slot": "Legs",
        "Stats": "Earth Resistance: <color=#AAFF00FF>+15%</color>",
        "Source": "Goblin Trooper",
        "Droprate": "100%",
        "Location": "Goblin Village",
        "SpriteId": "card"
    },
    {
        "Name": "Goblin Trooper Mage Card",
        "CardId": "Goblin Trooper Mage",
        "Affix": "Free",
        "Slot": "Head",
        "Stats": "<color=#FFFFFFFF>Grants <color=#AAFF00FF>Lv.5 Free Cast</color></color>",
        "Source": "Goblin Trooper Mage",
        "Droprate": "100%",
        "Location": "Goblin Village",
        "SpriteId": "card"
    },
    {
        "Name": "Goblin Trooper Soldier Card",
        "CardId": "Goblin Trooper Soldier",
        "Affix": "Slashing",
        "Slot": "Legs",
        "Stats": "Twin Cleave Damage: <color=#AAFF00FF>+12%</color>",
        "Source": "Goblin Trooper Soldier",
        "Droprate": "100%",
        "Location": "Goblin Village",
        "SpriteId": "card"
    },
    {
        "Name": "Golem Earth Card",
        "CardId": "Golem Earth",
        "Affix": "Stone",
        "Slot": "Chest",
        "Stats": "Def: <color=#AAFF00FF>+15%</color>",
        "Source": "Golem Earth",
        "Droprate": "100%",
        "Location": "Windy Desert",
        "SpriteId": "card"
    },
    {
        "Name": "Golem Fire Card",
        "CardId": "Golem Fire",
        "Affix": "Stone",
        "Slot": "Eyewear",
        "Stats": "Def: <color=#AAFF00FF>+10%</color>",
        "Source": "Golem Fire",
        "Droprate": "100%",
        "Location": "Demon's Maw",
        "SpriteId": "card"
    },
    {
        "Name": "Golem Ice Card",
        "CardId": "Golem Ice",
        "Affix": "Stone",
        "Slot": "Shield",
        "Stats": "Def: <color=#AAFF00FF>+3% per level</color>",
        "Source": "Golem Ice",
        "Droprate": "100%",
        "Location": "Crystal Cave",
        "SpriteId": "card"
    },
    {
        "Name": "Hare Card",
        "CardId": "Hare",
        "Affix": "Fleet",
        "Slot": "Feet",
        "Stats": "Move Spd: <color=#AAFF00FF>+20%</color>",
        "Source": "Hare",
        "Droprate": "300%",
        "Location": "Sunny Meadows",
        "SpriteId": "card_gold"
    },
    {
        "Name": "Haunt Card",
        "CardId": "Haunt",
        "Affix": "Lightproof",
        "Slot": "Legs",
        "Stats": "Holy Resistance: <color=#AAFF00FF>+15%</color>",
        "Source": "Haunt",
        "Droprate": "100%",
        "Location": "Sanctum of Light",
        "SpriteId": "card"
    },
    {
        "Name": "Hermit King Card",
        "CardId": "Hermit King",
        "Affix": "Hydro",
        "Slot": "Eyewear",
        "Stats": "<color=#FFFFFFFF>Grants <color=#AAFF00FF>Lv.1 Hydro Vortex</color></color>",
        "Source": "Hermit King",
        "Droprate": "300%",
        "Location": "Mystic Lake",
        "SpriteId": "card_gold"
    },
    {
        "Name": "Horror Card",
        "CardId": "Horror",
        "Affix": "Savage",
        "Slot": "Head",
        "Stats": "Crit Damage: <color=#AAFF00FF>+8%</color>",
        "Source": "Horror",
        "Droprate": "100%",
        "Location": "Forgotten Depths",
        "SpriteId": "card"
    },
    {
        "Name": "Housefly Icky Card",
        "CardId": "Housefly Icky",
        "Affix": "Assassin's",
        "Slot": "Accessory",
        "Stats": "Crit: <color=#AAFF00FF>+5</color>",
        "Source": "Housefly Icky",
        "Droprate": "100%",
        "Location": "Swamp",
        "SpriteId": "card"
    },
    {
        "Name": "Housefly Junk Card",
        "CardId": "Housefly Junk",
        "Affix": "Assassin's",
        "Slot": "Head",
        "Stats": "Total Critical Rate: <color=#AAFF00FF>+15%</color>",
        "Source": "Housefly Junk",
        "Droprate": "100%",
        "Location": "Swamp",
        "SpriteId": "card"
    },
    {
        "Name": "Housefly Nom Card",
        "CardId": "Housefly Nom",
        "Affix": "Assassin's",
        "Slot": "Weapon",
        "Stats": "Crit: <color=#AAFF00FF>+10</color>",
        "Source": "Housefly Nom",
        "Droprate": "100%",
        "Location": "Swamp",
        "SpriteId": "card"
    },
    {
        "Name": "Ice Card",
        "CardId": "Ice",
        "Affix": "Icepick",
        "Slot": "Accessory",
        "Stats": "<color=#FFFFFFFF>Immune to Reflect damage</color>",
        "Source": "Ice",
        "Droprate": "100%",
        "Location": "Crystal Cave",
        "SpriteId": "card"
    },
    {
        "Name": "Ice Mage Card",
        "CardId": "Ice Mage",
        "Affix": "Tidal",
        "Slot": "Chest",
        "Stats": "<color=#FFFFFFFF>Convert to <sprite name=Elements_6> <color=#79D7FDFF>Water</color> element</color>\nResistance to Frozen: <color=#AAFF00FF>+100%</color>",
        "Source": "Ice Mage",
        "Droprate": "300%",
        "Location": "Crystal Cave",
        "SpriteId": "card_gold"
    },
    {
        "Name": "Icicle Card",
        "CardId": "Icicle",
        "Affix": "Thawing",
        "Slot": "Feet",
        "Stats": "Resistance to Slow: <color=#AAFF00FF>+100%</color>",
        "Source": "Icicle",
        "Droprate": "100%",
        "Location": "Crystal Cave",
        "SpriteId": "card"
    },
    {
        "Name": "Imp Devil Card",
        "CardId": "Imp Devil",
        "Affix": "Meteoric",
        "Slot": "Eyewear",
        "Stats": "<color=#FFFFFFFF>Grants <color=#AAFF00FF>Lv.5 Meteor</color></color>",
        "Source": "Imp Devil",
        "Droprate": "300%",
        "Location": "Demon's Maw",
        "SpriteId": "card_gold"
    },
    {
        "Name": "Imp Mischief Card",
        "CardId": "Imp Mischief",
        "Affix": "Mischief",
        "Slot": "Shield",
        "Stats": "Chance to reflect single target magic: <color=#AAFF00FF>+2% per level</color>",
        "Source": "Imp Mischief",
        "Droprate": "100%",
        "Location": "Demon's Maw",
        "SpriteId": "card"
    },
    {
        "Name": "Lurker Card",
        "CardId": "Lurker",
        "Affix": "Savage",
        "Slot": "Accessory",
        "Stats": "Crit Damage: <color=#AAFF00FF>+8%</color>",
        "Source": "Lurker",
        "Droprate": "100%",
        "Location": "Forgotten Depths",
        "SpriteId": "card"
    },
    {
        "Name": "Mole Rat Card",
        "CardId": "Mole Rat",
        "Affix": "Steadfast",
        "Slot": "Feet",
        "Stats": "<color=#FFFFFFFF>Immune to Flinching from damage</color>\nHp: <color=#FF0073FF>-25%</color>",
        "Source": "Mole Rat",
        "Droprate": "100%",
        "Location": "Windy Desert",
        "SpriteId": "card"
    },
    {
        "Name": "Mole Rat King Card",
        "CardId": "Mole Rat King",
        "Affix": "Stomping",
        "Slot": "Back",
        "Stats": "<color=#FFFFFFFF>Grants <color=#AAFF00FF>Lv.3 Stomp</color></color>",
        "Source": "Mole Rat King",
        "Droprate": "100%",
        "Location": "Windy Desert",
        "SpriteId": "card"
    },
    {
        "Name": "Mosquito Bug Card",
        "CardId": "Mosquito Bug",
        "Affix": "Vampiric",
        "Slot": "Accessory",
        "Stats": "Health on hit: <color=#AAFF00FF>+10</color>",
        "Source": "Mosquito Bug",
        "Droprate": "100%",
        "Location": "Swamp",
        "SpriteId": "card"
    },
    {
        "Name": "Mosquito Pester Card",
        "CardId": "Mosquito Pester",
        "Affix": "Windproof",
        "Slot": "Legs",
        "Stats": "Wind Resistance: <color=#AAFF00FF>+15%</color>",
        "Source": "Mosquito Pester",
        "Droprate": "100%",
        "Location": "Swamp",
        "SpriteId": "card"
    },
    {
        "Name": "Mosquito Stinger Card",
        "CardId": "Mosquito Stinger",
        "Affix": "Haste",
        "Slot": "Accessory",
        "Stats": "<color=#FFFFFFFF>Grants <color=#AAFF00FF>Lv.5 Haste</color></color>",
        "Source": "Mosquito Stinger",
        "Droprate": "100%",
        "Location": "Swamp",
        "SpriteId": "card"
    },
    {
        "Name": "Moth Celestial Card",
        "CardId": "Moth Celestial",
        "Affix": "Lightproof",
        "Slot": "Shield",
        "Stats": "Holy Resistance: <color=#AAFF00FF>+25%</color>",
        "Source": "Moth Celestial",
        "Droprate": "100%",
        "Location": "Fairy Glen",
        "SpriteId": "card"
    },
    {
        "Name": "Moth Luna Card",
        "CardId": "Moth Luna",
        "Affix": "Unholy",
        "Slot": "Weapon",
        "Stats": "Damage vs Holy Enemies: <color=#AAFF00FF>+10%</color>",
        "Source": "Moth Luna",
        "Droprate": "100%",
        "Location": "Fairy Glen",
        "SpriteId": "card"
    },
    {
        "Name": "Moth Moon Card",
        "CardId": "Moth Moon",
        "Affix": "Cleric's",
        "Slot": "Accessory",
        "Stats": "Healing: <color=#AAFF00FF>+10%</color>",
        "Source": "Moth Moon",
        "Droprate": "100%",
        "Location": "Fairy Glen",
        "SpriteId": "card"
    },
    {
        "Name": "Mushroom Card",
        "CardId": "Mushroom",
        "Affix": "Occult",
        "Slot": "Weapon",
        "Stats": "Matk: <color=#AAFF00FF>+5</color>",
        "Source": "Mushroom",
        "Droprate": "100%",
        "Location": "Mystic Lake",
        "SpriteId": "card"
    },
    {
        "Name": "Nightmare Card",
        "CardId": "Nightmare",
        "Affix": "Darkproof",
        "Slot": "Shield",
        "Stats": "Shadow Resistance: <color=#AAFF00FF>+25%</color>",
        "Source": "Nightmare",
        "Droprate": "100%",
        "Location": "Abyss Castle Library",
        "SpriteId": "card"
    },
    {
        "Name": "Petal Card",
        "CardId": "Petal",
        "Affix": "Tidal",
        "Slot": "Weapon",
        "Stats": "<color=#FFFFFFFF>Enchant weapon with <sprite name=Elements_6> <color=#79D7FDFF>Water</color> element</color>",
        "Source": "Petal",
        "Droprate": "100%",
        "Location": "Mystic Lake",
        "SpriteId": "card"
    },
    {
        "Name": "Phantom Card",
        "CardId": "Phantom",
        "Affix": "Arcanum",
        "Slot": "Head",
        "Stats": "Mp Cost: <color=#AAFF00FF>-15%</color>",
        "Source": "Phantom",
        "Droprate": "100%",
        "Location": "Sanctum of Light",
        "SpriteId": "card"
    },
    {
        "Name": "Plant Chewer Card",
        "CardId": "Plant Chewer",
        "Affix": "Immune",
        "Slot": "Shield",
        "Stats": "Neutral Resistance: <color=#AAFF00FF>+25%</color>",
        "Source": "Plant Chewer",
        "Droprate": "100%",
        "Location": "Windy Desert",
        "SpriteId": "card"
    },
    {
        "Name": "Poison Bomb Card",
        "CardId": "Poison Bomb",
        "Affix": "Mystery",
        "Slot": "Weapon",
        "Stats": "All Stats: <color=#AAFF00FF>+1</color>",
        "Source": "Poison Bomb",
        "Droprate": "100%",
        "Location": "Underground Cavern",
        "SpriteId": "card"
    },
    {
        "Name": "Pollen Card",
        "CardId": "Pollen",
        "Affix": "Elusive",
        "Slot": "Chest",
        "Stats": "Flee: <color=#AAFF00FF>+15</color>",
        "Source": "Pollen",
        "Droprate": "100%",
        "Location": "Sunny Meadows",
        "SpriteId": "card"
    },
    {
        "Name": "Posy Card",
        "CardId": "Posy",
        "Affix": "Icy",
        "Slot": "Weapon",
        "Stats": "<color=#FFFFFFFF>Grants <color=#AAFF00FF>Lv.3 Icebolt</color></color>\nChance to autocast Icebolt when attacking: <color=#AAFF00FF>+10%</color>",
        "Source": "Posy",
        "Droprate": "100%",
        "Location": "Mystic Lake",
        "SpriteId": "card"
    },
    {
        "Name": "Queen Worm Card",
        "CardId": "Queen Worm",
        "Affix": "Venomous",
        "Slot": "Eyewear",
        "Stats": "<color=#FFFFFFFF>Grants <color=#AAFF00FF>Lv.5 Enchant Poison</color></color>",
        "Source": "Queen Worm",
        "Droprate": "300%",
        "Location": "Swamp",
        "SpriteId": "card_gold"
    },
    {
        "Name": "Rabbit Card",
        "CardId": "Rabbit",
        "Affix": "Swift",
        "Slot": "Feet",
        "Stats": "Move Spd: <color=#AAFF00FF>+10%</color>",
        "Source": "Rabbit",
        "Droprate": "100%",
        "Location": "Forest Labyrinth",
        "SpriteId": "card"
    },
    {
        "Name": "Scorpion Card",
        "CardId": "Scorpion",
        "Affix": "Fireproof",
        "Slot": "Shield",
        "Stats": "Fire Resistance: <color=#AAFF00FF>+25%</color>",
        "Source": "Scorpion",
        "Droprate": "100%",
        "Location": "Windy Desert",
        "SpriteId": "card"
    },
    {
        "Name": "Scorpion King Card",
        "CardId": "Scorpion King",
        "Affix": "Blazing",
        "Slot": "Chest",
        "Stats": "<color=#FFFFFFFF>Convert to <sprite name=Elements_5> <color=#FF7026FF>Fire</color> element</color>",
        "Source": "Scorpion King",
        "Droprate": "300%",
        "Location": "Windy Desert",
        "SpriteId": "card_gold"
    },
    {
        "Name": "Scorpling Card",
        "CardId": "Scorpling",
        "Affix": "Ashen",
        "Slot": "Weapon",
        "Stats": "Damage vs Fire Enemies: <color=#AAFF00FF>+10%</color>",
        "Source": "Scorpling",
        "Droprate": "100%",
        "Location": "Windy Desert",
        "SpriteId": "card"
    },
    {
        "Name": "Seed Card",
        "CardId": "Seed",
        "Affix": "Flurry",
        "Slot": "Weapon",
        "Stats": "Piercing Flurry Damage: <color=#AAFF00FF>+12%</color>",
        "Source": "Seed",
        "Droprate": "100%",
        "Location": "Forest Labyrinth",
        "SpriteId": "card"
    },
    {
        "Name": "Shade Card",
        "CardId": "Shade",
        "Affix": "Mystery",
        "Slot": "Back",
        "Stats": "All Stats: <color=#AAFF00FF>+1</color>",
        "Source": "Shade",
        "Droprate": "100%",
        "Location": "Demon's Maw",
        "SpriteId": "card"
    },
    {
        "Name": "Shadow Card",
        "CardId": "Shadow",
        "Affix": "Mystery",
        "Slot": "Accessory",
        "Stats": "All Stats: <color=#AAFF00FF>+1</color>",
        "Source": "Shadow",
        "Droprate": "100%",
        "Location": "Demon's Maw",
        "SpriteId": "card"
    },
    {
        "Name": "Shell Card",
        "CardId": "Shell",
        "Affix": "Immune",
        "Slot": "Legs",
        "Stats": "Neutral Resistance: <color=#AAFF00FF>+10%</color>",
        "Source": "Shell",
        "Droprate": "100%",
        "Location": "Mystic Lake",
        "SpriteId": "card"
    },
    {
        "Name": "Skeleton Card",
        "CardId": "Skeleton",
        "Affix": "Sanctified",
        "Slot": "Weapon",
        "Stats": "Holy Damage: <color=#AAFF00FF>+8%</color>",
        "Source": "Skeleton",
        "Droprate": "100%",
        "Location": "Festering Woods",
        "SpriteId": "card"
    },
    {
        "Name": "Skeleton Giant Card",
        "CardId": "Skeleton Giant",
        "Affix": "Sanctified",
        "Slot": "Accessory",
        "Stats": "Holy Damage: <color=#AAFF00FF>+8%</color>",
        "Source": "Skeleton Giant",
        "Droprate": "100%",
        "Location": "Abyss Castle Keep",
        "SpriteId": "card"
    },
    {
        "Name": "Skeleton Mage Card",
        "CardId": "Skeleton Mage",
        "Affix": "Grave",
        "Slot": "Weapon",
        "Stats": "Damage vs Undead Enemies: <color=#AAFF00FF>+10%</color>",
        "Source": "Skeleton Mage",
        "Droprate": "100%",
        "Location": "Abyss Castle Keep",
        "SpriteId": "card"
    },
    {
        "Name": "Snake Card",
        "CardId": "Snake",
        "Affix": "Venomous",
        "Slot": "Weapon",
        "Stats": "<color=#FFFFFFFF>Grants <color=#AAFF00FF>Lv.3 Venom Strike</color></color>\nChance to autocast Venom Strike when attacking: <color=#AAFF00FF>+10%</color>",
        "Source": "Snake",
        "Droprate": "100%",
        "Location": "Forgotten Depths",
        "SpriteId": "card"
    },
    {
        "Name": "Snake Naga Card",
        "CardId": "Snake Naga",
        "Affix": "Twinfang",
        "Slot": "Weapon",
        "Stats": "Double Attack: <color=#AAFF00FF>+30%</color>",
        "Source": "Snake Naga",
        "Droprate": "300%",
        "Location": "Forgotten Depths",
        "SpriteId": "card_gold"
    },
    {
        "Name": "Snakelet Card",
        "CardId": "Snakelet",
        "Affix": "Venomous",
        "Slot": "Weapon",
        "Stats": "Venom Strike Damage: <color=#AAFF00FF>+12%</color>",
        "Source": "Snakelet",
        "Droprate": "100%",
        "Location": "Forgotten Depths",
        "SpriteId": "card"
    },
    {
        "Name": "Snow Bomb Card",
        "CardId": "Snow Bomb",
        "Affix": "Magic",
        "Slot": "Weapon",
        "Stats": "Matk: <color=#AAFF00FF>+5%</color>",
        "Source": "Snow Bomb",
        "Droprate": "100%",
        "Location": "Crystal Cave",
        "SpriteId": "card"
    },
    {
        "Name": "Soul Card",
        "CardId": "Soul",
        "Affix": "Soul",
        "Slot": "Weapon",
        "Stats": "Soul Strike Damage: <color=#AAFF00FF>+12%</color>",
        "Source": "Soul",
        "Droprate": "100%",
        "Location": "Sanctum of Light",
        "SpriteId": "card"
    },
    {
        "Name": "Soul Mage Card",
        "CardId": "Soul Mage",
        "Affix": "Wizardry",
        "Slot": "Accessory",
        "Stats": "Cast Spd: <color=#AAFF00FF>+10%</color>",
        "Source": "Soul Mage",
        "Droprate": "100%",
        "Location": "Sanctum of Light",
        "SpriteId": "card"
    },
    {
        "Name": "Spider Card",
        "CardId": "Spider",
        "Affix": "Shadow",
        "Slot": "Weapon",
        "Stats": "Shadow Step Damage: <color=#AAFF00FF>+12%</color>",
        "Source": "Spider",
        "Droprate": "100%",
        "Location": "Forgotten Depths",
        "SpriteId": "card"
    },
    {
        "Name": "Spider King Card",
        "CardId": "Spider King",
        "Affix": "Poisonous",
        "Slot": "Weapon",
        "Stats": "<color=#FFFFFFFF>Enchant weapon with <sprite name=Elements_1> <color=#8CD470FF>Poison</color> element</color>",
        "Source": "Spider King",
        "Droprate": "100%",
        "Location": "Forgotten Depths",
        "SpriteId": "card"
    },
    {
        "Name": "Spider Toxin Card",
        "CardId": "Spider Toxin",
        "Affix": "Dancing",
        "Slot": "Legs",
        "Stats": "Blade Dance Damage: <color=#AAFF00FF>+12%</color>",
        "Source": "Spider Toxin",
        "Droprate": "100%",
        "Location": "Forgotten Depths",
        "SpriteId": "card"
    },
    {
        "Name": "Spike Card",
        "CardId": "Spike",
        "Affix": "Frosty",
        "Slot": "Back",
        "Stats": "<color=#FFFFFFFF>Grants <color=#AAFF00FF>Lv.3 Ice Shard</color></color>",
        "Source": "Spike",
        "Droprate": "100%",
        "Location": "Mystic Lake",
        "SpriteId": "card"
    },
    {
        "Name": "Spook Card",
        "CardId": "Spook",
        "Affix": "Unbreaking",
        "Slot": "Feet",
        "Stats": "<color=#FFFFFFFF>Cast cannot be interrupted</color>",
        "Source": "Spook",
        "Droprate": "100%",
        "Location": "Sanctum of Light",
        "SpriteId": "card"
    },
    {
        "Name": "Spore Card",
        "CardId": "Spore",
        "Affix": "Vital",
        "Slot": "Weapon",
        "Stats": "Hp: <color=#AAFF00FF>+100</color>\nVit: <color=#AAFF00FF>+1</color>",
        "Source": "Spore",
        "Droprate": "100%",
        "Location": "Windy Desert",
        "SpriteId": "card"
    },
    {
        "Name": "Sprout Card",
        "CardId": "Sprout",
        "Affix": "Impaling",
        "Slot": "Legs",
        "Stats": "Impale Damage: <color=#AAFF00FF>+12%</color>",
        "Source": "Sprout",
        "Droprate": "100%",
        "Location": "Forest Labyrinth",
        "SpriteId": "card"
    },
    {
        "Name": "Sting Card",
        "CardId": "Sting",
        "Affix": "Sniper",
        "Slot": "Weapon",
        "Stats": "Total Hit: <color=#AAFF00FF>+30%</color>",
        "Source": "Sting",
        "Droprate": "300%",
        "Location": "Forest Labyrinth",
        "SpriteId": "card_gold"
    },
    {
        "Name": "Sun Blossom Card",
        "CardId": "Sun Blossom",
        "Affix": "Enchanted",
        "Slot": "Shield",
        "Stats": "Healing: <color=#AAFF00FF>+15%</color>",
        "Source": "Sun Blossom",
        "Droprate": "100%",
        "Location": "Fairy Glen",
        "SpriteId": "card"
    },
    {
        "Name": "Sunflora Pixie Card",
        "CardId": "Sunflora Pixie",
        "Affix": "Vocal",
        "Slot": "Back",
        "Stats": "Resistance to Silence: <color=#AAFF00FF>+100%</color>",
        "Source": "Sunflora Pixie",
        "Droprate": "300%",
        "Location": "Fairy Glen",
        "SpriteId": "card_gold"
    },
    {
        "Name": "Sunflower Fairy Card",
        "CardId": "Sunflower Fairy",
        "Affix": "Blessed",
        "Slot": "Legs",
        "Stats": "Healing: <color=#AAFF00FF>+15%</color>",
        "Source": "Sunflower Fairy",
        "Droprate": "100%",
        "Location": "Fairy Glen",
        "SpriteId": "card"
    },
    {
        "Name": "Toadstool Card",
        "CardId": "Toadstool",
        "Affix": "Waterproof",
        "Slot": "Shield",
        "Stats": "Water Resistance: <color=#AAFF00FF>+25%</color>",
        "Source": "Toadstool",
        "Droprate": "100%",
        "Location": "Mystic Lake",
        "SpriteId": "card"
    },
    {
        "Name": "Treant Forest Autumn Card",
        "CardId": "Treant Forest Autumn",
        "Affix": "Autumn",
        "Slot": "Shield",
        "Stats": "Hp Regen: <color=#FF0073FF>-50%</color>\nMax mp recovered per second: <color=#AAFF00FF>+1%</color>",
        "Source": "Treant Forest Autumn",
        "Droprate": "100%",
        "Location": "Treant Trail",
        "SpriteId": "card"
    },
    {
        "Name": "Treant Forest Evergreen Card",
        "CardId": "Treant Forest Evergreen",
        "Affix": "Evergreen",
        "Slot": "Shield",
        "Stats": "Hp Regen: <color=#AAFF00FF>+10% per level</color>",
        "Source": "Treant Forest Evergreen",
        "Droprate": "100%",
        "Location": "Treant Trail",
        "SpriteId": "card"
    },
    {
        "Name": "Treant Minion Autumn Card",
        "CardId": "Treant Minion Autumn",
        "Affix": "Autumn",
        "Slot": "Feet",
        "Stats": "Mp Regen: <color=#AAFF00FF>+15%</color>\nMp: <color=#AAFF00FF>+20</color>",
        "Source": "Treant Minion Autumn",
        "Droprate": "100%",
        "Location": "Treant Trail",
        "SpriteId": "card"
    },
    {
        "Name": "Treant Minion Evergreen Card",
        "CardId": "Treant Minion Evergreen",
        "Affix": "Evergreen",
        "Slot": "Legs",
        "Stats": "Hp Regen: <color=#AAFF00FF>+25%</color>\nHp: <color=#AAFF00FF>+100</color>",
        "Source": "Treant Minion Evergreen",
        "Droprate": "100%",
        "Location": "Treant Trail",
        "SpriteId": "card"
    },
    {
        "Name": "Treant Tree Autumn Card",
        "CardId": "Treant Tree Autumn",
        "Affix": "Autumn",
        "Slot": "Chest",
        "Stats": "Mp: <color=#AAFF00FF>+20%</color>",
        "Source": "Treant Tree Autumn",
        "Droprate": "100%",
        "Location": "Treant Trail",
        "SpriteId": "card"
    },
    {
        "Name": "Treant Tree Evergreen Card",
        "CardId": "Treant Tree Evergreen",
        "Affix": "Evergreen",
        "Slot": "Chest",
        "Stats": "Hp: <color=#AAFF00FF>+20%</color>",
        "Source": "Treant Tree Evergreen",
        "Droprate": "100%",
        "Location": "Treant Trail",
        "SpriteId": "card"
    },
    {
        "Name": "Vampire Bat Card",
        "CardId": "Vampire Bat",
        "Affix": "Leeching",
        "Slot": "Accessory",
        "Stats": "Health on kill: <color=#AAFF00FF>+100</color>",
        "Source": "Vampire Bat",
        "Droprate": "100%",
        "Location": "Forgotten Depths",
        "SpriteId": "card"
    },
    {
        "Name": "Werewolf Card",
        "CardId": "Werewolf",
        "Affix": "Tainted",
        "Slot": "Chest",
        "Stats": "<color=#FFFFFFFF>Convert to <sprite name=Elements_3> <color=#755E94FF>Shadow</color> element</color>",
        "Source": "Werewolf",
        "Droprate": "300%",
        "Location": "Festering Woods",
        "SpriteId": "card_gold"
    },
    {
        "Name": "Whirlwind Card",
        "CardId": "Whirlwind",
        "Affix": "Grounding",
        "Slot": "Weapon",
        "Stats": "Damage vs Wind Enemies: <color=#AAFF00FF>+10%</color>",
        "Source": "Whirlwind",
        "Droprate": "100%",
        "Location": "Windy Desert",
        "SpriteId": "card"
    },
    {
        "Name": "Wind Card",
        "CardId": "Wind",
        "Affix": "Storm",
        "Slot": "Legs",
        "Stats": "Thunder Storm Damage: <color=#AAFF00FF>+12%</color>",
        "Source": "Wind",
        "Droprate": "100%",
        "Location": "Windy Desert",
        "SpriteId": "card"
    },
    {
        "Name": "Wind Mage Card",
        "CardId": "Wind Mage",
        "Affix": "Spark",
        "Slot": "Weapon",
        "Stats": "<color=#FFFFFFFF>Enchant weapon with <sprite name=Elements_7> <color=#FFC701FF>Wind</color> element</color>",
        "Source": "Wind Mage",
        "Droprate": "100%",
        "Location": "Windy Desert",
        "SpriteId": "card"
    },
    {
        "Name": "Wisp Blue Card",
        "CardId": "Wisp Blue",
        "Affix": "Freezing",
        "Slot": "Weapon",
        "Stats": "Icebolt Damage: <color=#AAFF00FF>+12%</color>",
        "Source": "Wisp Blue",
        "Droprate": "100%",
        "Location": "Forest Labyrinth",
        "SpriteId": "card"
    },
    {
        "Name": "Wisp Purple Card",
        "CardId": "Wisp Purple",
        "Affix": "Shocking",
        "Slot": "Weapon",
        "Stats": "Thunderbolt Damage: <color=#AAFF00FF>+12%</color>",
        "Source": "Wisp Purple",
        "Droprate": "100%",
        "Location": "Forest Labyrinth",
        "SpriteId": "card"
    },
    {
        "Name": "Wisp Red Card",
        "CardId": "Wisp Red",
        "Affix": "Flaming",
        "Slot": "Weapon",
        "Stats": "Firebolt Damage: <color=#AAFF00FF>+12%</color>",
        "Source": "Wisp Red",
        "Droprate": "100%",
        "Location": "Treant Trail",
        "SpriteId": "card"
    },
    {
        "Name": "Wisp Yellow Card",
        "CardId": "Wisp Yellow",
        "Affix": "Splintering",
        "Slot": "Weapon",
        "Stats": "Earthbolt Damage: <color=#AAFF00FF>+12%</color>",
        "Source": "Wisp Yellow",
        "Droprate": "100%",
        "Location": "Sunny Meadows",
        "SpriteId": "card"
    },
    {
        "Name": "Wolf Card",
        "CardId": "Wolf",
        "Affix": "Umbral",
        "Slot": "Accessory",
        "Stats": "Shadow Damage: <color=#AAFF00FF>+8%</color>",
        "Source": "Wolf",
        "Droprate": "100%",
        "Location": "Festering Woods",
        "SpriteId": "card"
    },
    {
        "Name": "Wolf Pup Card",
        "CardId": "Wolf Pup",
        "Affix": "Umbral",
        "Slot": "Weapon",
        "Stats": "Shadow Damage: <color=#AAFF00FF>+8%</color>",
        "Source": "Wolf Pup",
        "Droprate": "100%",
        "Location": "Festering Woods",
        "SpriteId": "card"
    },
    {
        "Name": "Worm Card",
        "CardId": "Worm",
        "Affix": "Toxinproof",
        "Slot": "Shield",
        "Stats": "Poison Resistance: <color=#AAFF00FF>+25%</color>",
        "Source": "Worm",
        "Droprate": "100%",
        "Location": "Swamp",
        "SpriteId": "card"
    },
    {
        "Name": "Worm Creep Card",
        "CardId": "Worm Creep",
        "Affix": "Poisonous",
        "Slot": "Chest",
        "Stats": "<color=#FFFFFFFF>Convert to <sprite name=Elements_1> <color=#8CD470FF>Poison</color> element</color>",
        "Source": "Worm Creep",
        "Droprate": "300%",
        "Location": "Underground Cavern",
        "SpriteId": "card_gold"
    },
    {
        "Name": "Worm Rot Card",
        "CardId": "Worm Rot",
        "Affix": "Toxinproof",
        "Slot": "Legs",
        "Stats": "Poison Resistance: <color=#AAFF00FF>+15%</color>",
        "Source": "Worm Rot",
        "Droprate": "100%",
        "Location": "Underground Cavern",
        "SpriteId": "card"
    },
    {
        "Name": "Worm Stink Card",
        "CardId": "Worm Stink",
        "Affix": "Purging",
        "Slot": "Weapon",
        "Stats": "Damage vs Poison Enemies: <color=#AAFF00FF>+10%</color>",
        "Source": "Worm Stink",
        "Droprate": "100%",
        "Location": "Underground Cavern",
        "SpriteId": "card"
    },
    {
        "Name": "Zombie Goblin Giant Card",
        "CardId": "Zombie Goblin Giant",
        "Affix": "Undead",
        "Slot": "Weapon",
        "Stats": "<color=#FFFFFFFF>Enchant weapon with <sprite name=Undead> <color=#C85AE0FF>Undead</color> element</color>",
        "Source": "Zombie Goblin Giant",
        "Droprate": "100%",
        "Location": "Goblin Cave",
        "SpriteId": "card"
    },
    {
        "Name": "Zombie Goblin King Card",
        "CardId": "Zombie Goblin King",
        "Affix": "Undead",
        "Slot": "Chest",
        "Stats": "<color=#FFFFFFFF>Convert to <sprite name=Undead> <color=#C85AE0FF>Undead</color> element</color>",
        "Source": "Zombie Goblin King",
        "Droprate": "300%",
        "Location": "Goblin Cave",
        "SpriteId": "card_gold"
    },
    {
        "Name": "Zombie Goblin Minion Card",
        "CardId": "Zombie Goblin Minion",
        "Affix": "Purity",
        "Slot": "Legs",
        "Stats": "Undead Resistance: <color=#AAFF00FF>+15%</color>",
        "Source": "Zombie Goblin Minion",
        "Droprate": "100%",
        "Location": "Goblin Cave",
        "SpriteId": "card"
    },
    {
        "Name": "Zombie Goblin Soldier Card",
        "CardId": "Zombie Goblin Soldier",
        "Affix": "Undead",
        "Slot": "Shield",
        "Stats": "Healing Received: <color=#FF0073FF>-50%</color>\nHp: <color=#AAFF00FF>+25%</color>",
        "Source": "Zombie Goblin Soldier",
        "Droprate": "100%",
        "Location": "Goblin Cave",
        "SpriteId": "card"
    }
];