window.cardData = [
  {
    "Name": "Angel Card",
    "CardId": "Angel",
    "Affix": "Blessed",
    "Slot": "Weapon",
    "Stats": "Healing: <color=#AAFF00FF>+10%</color>",
    "Source": "Angel",
    "Droprate": "50%",
    "Location": "Sanctum of Light",
    "SpriteId": "card"
  },
  {
    "Name": "Angel Mage Card",
    "CardId": "Angel Mage",
    "Affix": "Pure",
    "Slot": "Chest",
    "Stats": "<color=#FF9700FF>Convert to <sprite name=Elements_2> <color=#FCE9EBFF>Holy</color> element</color>",
    "Source": "Angel Mage",
    "Droprate": "300%",
    "Location": "Sanctum of Light",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Archangel Card",
    "CardId": "Archangel",
    "Affix": "Pure",
    "Slot": "Weapon",
    "Stats": "<color=#FF9700FF>Enchant weapon with <sprite name=Elements_2> <color=#FCE9EBFF>Holy</color> element</color>",
    "Source": "Archangel",
    "Droprate": "50%",
    "Location": "Sanctum of Light",
    "SpriteId": "card"
  },
  {
    "Name": "Ashrend Card",
    "CardId": "Alien Wreck",
    "Affix": "Titan",
    "Slot": "Chest",
    "Stats": "<color=#FF9700FF>Immune to Knockback</color>",
    "Source": "Ashrend",
    "Droprate": "50%",
    "Location": "Night Garden",
    "SpriteId": "card"
  },
  {
    "Name": "Bat Card",
    "CardId": "Bat",
    "Affix": "Leeching",
    "Slot": "Accessory",
    "Stats": "Mana on kill: <color=#AAFF00FF>+10</color>",
    "Source": "Bat",
    "Droprate": "50%",
    "Location": "Forgotten Depths 1",
    "SpriteId": "card"
  },
  {
    "Name": "Bat Lord Card",
    "CardId": "Bat Lord",
    "Affix": "Siphoning",
    "Slot": "Accessory",
    "Stats": "Siphon Mp: <color=#AAFF00FF>+3</color>",
    "Source": "Bat Lord",
    "Droprate": "300%",
    "Location": "Forgotten Depths 2",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Bee Card",
    "CardId": "Bee",
    "Affix": "Accurate",
    "Slot": "Weapon",
    "Stats": "Hit: <color=#AAFF00FF>+25</color>",
    "Source": "Bee",
    "Droprate": "50%",
    "Location": "Sunny Meadows 2",
    "SpriteId": "card"
  },
  {
    "Name": "Bird Card",
    "CardId": "Bird",
    "Affix": "Lancer",
    "Slot": "Weapon",
    "Stats": "Weapon Throw Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Bird",
    "Droprate": "50%",
    "Location": "Sunny Meadows 2",
    "SpriteId": "card"
  },
  {
    "Name": "Blazewheel Card",
    "CardId": "Alien Wheel",
    "Affix": "Spiked",
    "Slot": "Weapon",
    "Stats": "Reflect Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Blazewheel",
    "Droprate": "50%",
    "Location": "Dark Forest",
    "SpriteId": "card"
  },
  {
    "Name": "Bloom Card",
    "CardId": "Bloom",
    "Affix": "Volley",
    "Slot": "Weapon",
    "Stats": "Strafing Volley Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Bloom",
    "Droprate": "50%",
    "Location": "Underground Cavern",
    "SpriteId": "card"
  },
  {
    "Name": "Blossom Card",
    "CardId": "Blossom",
    "Affix": "Volatile",
    "Slot": "Weapon",
    "Stats": "Volatile Bolt Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Blossom",
    "Droprate": "50%",
    "Location": "Underground Cavern",
    "SpriteId": "card"
  },
  {
    "Name": "Bogbloom Card",
    "CardId": "Alien Plant",
    "Affix": "Resistance",
    "Slot": "Shield",
    "Stats": "Resistance to Slow: <color=#AAFF00FF>+50%</color>\nResistance to Bleeding: <color=#AAFF00FF>+50%</color>",
    "Source": "Bogbloom",
    "Droprate": "50%",
    "Location": "Night Garden",
    "SpriteId": "card"
  },
  {
    "Name": "Bomb Card",
    "CardId": "Bomb",
    "Affix": "Power",
    "Slot": "Weapon",
    "Stats": "Atk: <color=#AAFF00FF>+4%</color>",
    "Source": "Bomb",
    "Droprate": "50%",
    "Location": "Sanctum of Light",
    "SpriteId": "card"
  },
  {
    "Name": "Boxy Robot Card",
    "CardId": "Boxy Robot",
    "Affix": "Energy",
    "Slot": "Head",
    "Stats": "Hp Regen: <color=#AAFF00FF>+25%</color>\nMp Regen: <color=#AAFF00FF>+25%</color>",
    "Source": "Boxy Robot",
    "Droprate": "50%",
    "Location": "The Forge",
    "SpriteId": "card"
  },
  {
    "Name": "Bud Card",
    "CardId": "Bud",
    "Affix": "Light",
    "Slot": "Legs",
    "Stats": "Weight Limit: <color=#AAFF00FF>+100 per level</color>",
    "Source": "Bud",
    "Droprate": "50%",
    "Location": "Underground Cavern",
    "SpriteId": "card"
  },
  {
    "Name": "Bumble Card",
    "CardId": "Bumble",
    "Affix": "Sniper",
    "Slot": "Head",
    "Stats": "Total Hit: <color=#AAFF00FF>+10%</color>",
    "Source": "Bumble",
    "Droprate": "50%",
    "Location": "Sunny Meadows 2",
    "SpriteId": "card"
  },
  {
    "Name": "Bunny Card",
    "CardId": "Bunny",
    "Affix": "Rapid",
    "Slot": "Accessory",
    "Stats": "Atk Spd: <color=#AAFF00FF>+5%</color>",
    "Source": "Bunny",
    "Droprate": "50%",
    "Location": "Bunny Woods",
    "SpriteId": "card"
  },
  {
    "Name": "Burrow Card",
    "CardId": "Burrow",
    "Affix": "Steadfast",
    "Slot": "Head",
    "Stats": "Resistance to Stun: <color=#AAFF00FF>+50%</color>\nMp: <color=#FF0073FF>-25%</color>",
    "Source": "Burrow",
    "Droprate": "50%",
    "Location": "Forest Field 2",
    "SpriteId": "card"
  },
  {
    "Name": "Butterfly Fairy Card",
    "CardId": "Butterfly Fairy",
    "Affix": "Wizardry",
    "Slot": "Chest",
    "Stats": "Cast Spd: <color=#AAFF00FF>+15%</color>",
    "Source": "Butterfly Fairy",
    "Droprate": "50%",
    "Location": "Fairy Glen",
    "SpriteId": "card"
  },
  {
    "Name": "Butterfly Hue Card",
    "CardId": "Butterfly Hue",
    "Affix": "Wizardry",
    "Slot": "Weapon",
    "Stats": "Cast Spd: <color=#AAFF00FF>+10%</color>",
    "Source": "Butterfly Hue",
    "Droprate": "50%",
    "Location": "Fairy Glen",
    "SpriteId": "card"
  },
  {
    "Name": "Butterfly Pixie Card",
    "CardId": "Butterfly Pixie",
    "Affix": "Wizardry",
    "Slot": "Head",
    "Stats": "Cast Spd: <color=#AAFF00FF>+15%</color>",
    "Source": "Butterfly Pixie",
    "Droprate": "50%",
    "Location": "Fairy Glen",
    "SpriteId": "card"
  },
  {
    "Name": "Cacti Card",
    "CardId": "Cacti",
    "Affix": "Spiked",
    "Slot": "Shield",
    "Stats": "Reflect Damage: <color=#AAFF00FF>+2% per level</color>",
    "Source": "Cacti",
    "Droprate": "50%",
    "Location": "Windy Desert South",
    "SpriteId": "card"
  },
  {
    "Name": "Cactus Card",
    "CardId": "Cactus",
    "Affix": "Mudproof",
    "Slot": "Shield",
    "Stats": "Earth Resistance: <color=#AAFF00FF>+25%</color>",
    "Source": "Cactus",
    "Droprate": "50%",
    "Location": "Windy Desert South",
    "SpriteId": "card"
  },
  {
    "Name": "Cactus King Card",
    "CardId": "Cactus Boss",
    "Affix": "Steadfast",
    "Slot": "Feet",
    "Stats": "Grants <color=#AAFF00FF>Lv.5 Endure</color>",
    "Source": "Cactus King",
    "Droprate": "300%",
    "Location": "Windy Desert South",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Cat Bolt Card",
    "CardId": "Cat Bolt",
    "Affix": "Gale",
    "Slot": "Chest",
    "Stats": "<color=#FF9700FF>Convert to <sprite name=Elements_7> <color=#FFC701FF>Wind</color> element</color>",
    "Source": "Cat Bolt",
    "Droprate": "300%",
    "Location": "Windy Desert",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Cat Lightning Card",
    "CardId": "Cat Lightning",
    "Affix": "Windproof",
    "Slot": "Shield",
    "Stats": "Wind Resistance: <color=#AAFF00FF>+25%</color>",
    "Source": "Cat Lightning",
    "Droprate": "50%",
    "Location": "Windy Desert",
    "SpriteId": "card"
  },
  {
    "Name": "Cat Meow Card",
    "CardId": "Cat Meow",
    "Affix": "Shocking",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.2 Thunderbolt</color>\nChance to autocast Lv.2 Thunderbolt when attacking: <color=#AAFF00FF>+10%</color>",
    "Source": "Cat Meow",
    "Droprate": "50%",
    "Location": "Forest Field 2",
    "SpriteId": "card"
  },
  {
    "Name": "Chick Card",
    "CardId": "Chick",
    "Affix": "Sharp",
    "Slot": "Weapon",
    "Stats": "Atk: <color=#AAFF00FF>+5</color>",
    "Source": "Chick",
    "Droprate": "50%",
    "Location": "Sunny Meadows 1",
    "SpriteId": "card"
  },
  {
    "Name": "Cinderspike Card",
    "CardId": "Alien Spike",
    "Affix": "Swift",
    "Slot": "Legs",
    "Stats": "Move Spd: <color=#AAFF00FF>+10%</color>",
    "Source": "Cinderspike",
    "Droprate": "50%",
    "Location": "Dark Forest",
    "SpriteId": "card"
  },
  {
    "Name": "Cosmic Entity Card",
    "CardId": "Alien Big Blink",
    "Affix": "Cosmic",
    "Slot": "Head",
    "Stats": "Matk: <color=#AAFF00FF>+10%</color>\nAtk: <color=#AAFF00FF>+10%</color>\nHp: <color=#FF0073FF>-25%</color>\nMp: <color=#FF0073FF>-25%</color>",
    "Source": "Cosmic Entity",
    "Droprate": "300%",
    "Location": "Night Garden",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Creeper Card",
    "CardId": "Creeper",
    "Affix": "Savage",
    "Slot": "Weapon",
    "Stats": "Crit Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Creeper",
    "Droprate": "50%",
    "Location": "Forgotten Depths 1",
    "SpriteId": "card"
  },
  {
    "Name": "Cyclops Bat Card",
    "CardId": "Cyclops Bat",
    "Affix": "Melee",
    "Slot": "Weapon",
    "Stats": "Damage Melee: <color=#AAFF00FF>+5%</color>",
    "Source": "Cyclops Bat",
    "Droprate": "50%",
    "Location": "Abyss Castle Keep",
    "SpriteId": "card"
  },
  {
    "Name": "Cyclops Bat Mage Card",
    "CardId": "Cyclops Bat Mage",
    "Affix": "Magic",
    "Slot": "Weapon",
    "Stats": "Damage Magic: <color=#AAFF00FF>+5%</color>",
    "Source": "Cyclops Bat Mage",
    "Droprate": "50%",
    "Location": "Abyss Castle Library",
    "SpriteId": "card"
  },
  {
    "Name": "Cyclops Bat Wizard Card",
    "CardId": "Cyclops Bat Wizard",
    "Affix": "Ranged",
    "Slot": "Weapon",
    "Stats": "Damage Ranged: <color=#AAFF00FF>+5%</color>",
    "Source": "Cyclops Bat Wizard",
    "Droprate": "50%",
    "Location": "Abyss Castle Keep",
    "SpriteId": "card"
  },
  {
    "Name": "Cyclops Card",
    "CardId": "Cyclops",
    "Affix": "Warding",
    "Slot": "Head",
    "Stats": "Mdef: <color=#AAFF00FF>+10%</color>",
    "Source": "Cyclops",
    "Droprate": "50%",
    "Location": "Crystal Cave",
    "SpriteId": "card"
  },
  {
    "Name": "Cyclops Giant Card",
    "CardId": "Cyclops Giant",
    "Affix": "Warding",
    "Slot": "Shield",
    "Stats": "Mdef: <color=#AAFF00FF>+3% per level</color>",
    "Source": "Cyclops Giant",
    "Droprate": "50%",
    "Location": "Crystal Cave",
    "SpriteId": "card"
  },
  {
    "Name": "Cyclops Minion Card",
    "CardId": "Cyclops Minion",
    "Affix": "Warding",
    "Slot": "Chest",
    "Stats": "Mdef: <color=#AAFF00FF>+15%</color>",
    "Source": "Cyclops Minion",
    "Droprate": "50%",
    "Location": "Crystal Cave",
    "SpriteId": "card"
  },
  {
    "Name": "Death Card",
    "CardId": "Death",
    "Affix": "Darkproof",
    "Slot": "Legs",
    "Stats": "Shadow Resistance: <color=#AAFF00FF>+15%</color>",
    "Source": "Death",
    "Droprate": "50%",
    "Location": "Abyss Castle Keep",
    "SpriteId": "card"
  },
  {
    "Name": "Death Mage Card",
    "CardId": "Death Mage",
    "Affix": "Cloaking",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.1 Cloaking</color>",
    "Source": "Death Mage",
    "Droprate": "300%",
    "Location": "Abyss Castle Library",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Delivery Robot Card",
    "CardId": "Delivery Robot",
    "Affix": "Fleet",
    "Slot": "Head",
    "Stats": "Move Spd: <color=#AAFF00FF>+10%</color>\nHp: <color=#FF0073FF>-5%</color>\nMp: <color=#FF0073FF>-5%</color>",
    "Source": "Delivery Robot",
    "Droprate": "50%",
    "Location": "The Forge",
    "SpriteId": "card"
  },
  {
    "Name": "Direwolf Card",
    "CardId": "Direwolf",
    "Affix": "Cloaking",
    "Slot": "Accessory",
    "Stats": "Perfect Cloaking: <color=#FF9700FF>undetectable by shadow monsters when invisible</color>",
    "Source": "Direwolf",
    "Droprate": "50%",
    "Location": "Abyss Castle Crypt",
    "SpriteId": "card"
  },
  {
    "Name": "Dog Bark Card",
    "CardId": "Dog Bark",
    "Affix": "Flaming",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.2 Fireball</color>",
    "Source": "Dog Bark",
    "Droprate": "50%",
    "Location": "Forest Field 2",
    "SpriteId": "card"
  },
  {
    "Name": "Dog Bowwow Card",
    "CardId": "Dog Bowwow",
    "Affix": "Blazing",
    "Slot": "Weapon",
    "Stats": "<color=#FF9700FF>Enchant weapon with <sprite name=Elements_5> <color=#FF7026FF>Fire</color> element</color>",
    "Source": "Dog Bowwow",
    "Droprate": "50%",
    "Location": "Windy Desert North",
    "SpriteId": "card"
  },
  {
    "Name": "Dog Pup Card",
    "CardId": "Dog Pup",
    "Affix": "Flaming",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.2 Firebolt</color>\nChance to autocast Lv.2 Firebolt when attacking: <color=#AAFF00FF>+10%</color>",
    "Source": "Dog Pup",
    "Droprate": "50%",
    "Location": "Forest Field 2",
    "SpriteId": "card"
  },
  {
    "Name": "Dragon Blizzard Card",
    "CardId": "Dragon Blizzard",
    "Affix": "Diamond",
    "Slot": "Chest",
    "Stats": "Resistance to Frozen: <color=#AAFF00FF>+50%</color>",
    "Source": "Dragon Blizzard",
    "Droprate": "50%",
    "Location": "Crystal Cave",
    "SpriteId": "card"
  },
  {
    "Name": "Dragon Darkness Card",
    "CardId": "Dragon Darkness",
    "Affix": "Tainted",
    "Slot": "Weapon",
    "Stats": "<color=#FF9700FF>Enchant weapon with <sprite name=Elements_3> <color=#755E94FF>Shadow</color> element</color>",
    "Source": "Dragon Darkness",
    "Droprate": "50%",
    "Location": "Sanctum of Light",
    "SpriteId": "card"
  },
  {
    "Name": "Dragon Dusk Card",
    "CardId": "Dragon Dusk",
    "Affix": "Exorcist's",
    "Slot": "Weapon",
    "Stats": "Damage vs Shadow Enemies: <color=#AAFF00FF>+10%</color>",
    "Source": "Dragon Dusk",
    "Droprate": "50%",
    "Location": "Sanctum of Light",
    "SpriteId": "card"
  },
  {
    "Name": "Dragon Fire Card",
    "CardId": "Dragon Fire",
    "Affix": "Fireproof",
    "Slot": "Legs",
    "Stats": "Fire Resistance: <color=#AAFF00FF>+15%</color>",
    "Source": "Dragon Fire",
    "Droprate": "50%",
    "Location": "Demon's Maw",
    "SpriteId": "card"
  },
  {
    "Name": "Dragon Ice Card",
    "CardId": "Dragon Ice",
    "Affix": "Freezing",
    "Slot": "Weapon",
    "Stats": "Ice Shard Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Dragon Ice",
    "Droprate": "50%",
    "Location": "Crystal Cave",
    "SpriteId": "card"
  },
  {
    "Name": "Dragon Inferno Card",
    "CardId": "Dragon Inferno",
    "Affix": "Power",
    "Slot": "Accessory",
    "Stats": "Atk: <color=#AAFF00FF>+4%</color>",
    "Source": "Dragon Inferno",
    "Droprate": "50%",
    "Location": "Demon's Maw",
    "SpriteId": "card"
  },
  {
    "Name": "Dragon Nightfall Card",
    "CardId": "Dragon Nightfall",
    "Affix": "Purifying",
    "Slot": "Head",
    "Stats": "Resistance to Curse: <color=#AAFF00FF>+50%</color>",
    "Source": "Dragon Nightfall",
    "Droprate": "50%",
    "Location": "Sanctum of Light",
    "SpriteId": "card"
  },
  {
    "Name": "Dragon Spark Card",
    "CardId": "Dragon Spark",
    "Affix": "Power",
    "Slot": "Head",
    "Stats": "Atk: <color=#AAFF00FF>+4%</color>",
    "Source": "Dragon Spark",
    "Droprate": "50%",
    "Location": "Demon's Maw",
    "SpriteId": "card"
  },
  {
    "Name": "Dragon Water Card",
    "CardId": "Dragon Water",
    "Affix": "Waterproof",
    "Slot": "Legs",
    "Stats": "Water Resistance: <color=#AAFF00FF>+15%</color>",
    "Source": "Dragon Water",
    "Droprate": "50%",
    "Location": "Crystal Cave",
    "SpriteId": "card"
  },
  {
    "Name": "Dragonfly Arrow Card",
    "CardId": "Dragonfly Arrow",
    "Affix": "Nimble",
    "Slot": "Feet",
    "Stats": "Flee: <color=#AAFF00FF>+10</color>\nAgi: <color=#AAFF00FF>+1</color>",
    "Source": "Dragonfly Arrow",
    "Droprate": "50%",
    "Location": "Swamp",
    "SpriteId": "card"
  },
  {
    "Name": "Dragonfly Darner Card",
    "CardId": "Dragonfly Darner",
    "Affix": "Elusive",
    "Slot": "Legs",
    "Stats": "Flee: <color=#AAFF00FF>+20</color>",
    "Source": "Dragonfly Darner",
    "Droprate": "50%",
    "Location": "Swamp",
    "SpriteId": "card"
  },
  {
    "Name": "Dragonfly Swift Card",
    "CardId": "Dragonfly Swift",
    "Affix": "Elusive",
    "Slot": "Shield",
    "Stats": "Flee: <color=#AAFF00FF>+25</color>",
    "Source": "Dragonfly Swift",
    "Droprate": "50%",
    "Location": "Swamp Wilderness",
    "SpriteId": "card"
  },
  {
    "Name": "Earthworm Card",
    "CardId": "Earthworm",
    "Affix": "Anti-Venom",
    "Slot": "Head",
    "Stats": "Resistance to Poison: <color=#AAFF00FF>+50%</color>",
    "Source": "Earthworm",
    "Droprate": "50%",
    "Location": "Swamp Wilderness",
    "SpriteId": "card"
  },
  {
    "Name": "Echo Acolyte Card",
    "CardId": "NightmareAcolyte",
    "Affix": "Acolyte",
    "Slot": "Accessory",
    "Stats": "Status Duration: <color=#AAFF00FF>+10%</color>",
    "Source": "Echo Acolyte",
    "Droprate": "50%",
    "Location": "Dark Fortress Lv1",
    "SpriteId": "card"
  },
  {
    "Name": "Echo Berserker Card",
    "CardId": "NightmareBerserker",
    "Affix": "Berserker",
    "Slot": "Head",
    "Stats": "Def Pierce: <color=#AAFF00FF>+2% per level</color>",
    "Source": "Echo Berserker",
    "Droprate": "300%",
    "Location": "Dark Fortress Lv2",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Echo Gunslinger Card",
    "CardId": "NightmareGunslinger",
    "Affix": "Gunslinger",
    "Slot": "Head",
    "Stats": "Perfect Hit: <color=#AAFF00FF>+3% per level</color>\nDamage Ranged: <color=#AAFF00FF>+1% per level</color>\nRange: <color=#AAFF00FF>+1</color>",
    "Source": "Echo Gunslinger",
    "Droprate": "300%",
    "Location": "Dark Fortress Lv2",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Echo Knight Card",
    "CardId": "NightmareKnight",
    "Affix": "Knight",
    "Slot": "Accessory",
    "Stats": "Threat Generation: <color=#AAFF00FF>+25% per level</color>",
    "Source": "Echo Knight",
    "Droprate": "50%",
    "Location": "Dark Fortress Lv1",
    "SpriteId": "card"
  },
  {
    "Name": "Echo Mage Card",
    "CardId": "NightmareMage",
    "Affix": "Mage",
    "Slot": "Accessory",
    "Stats": "Matk: <color=#AAFF00FF>+5</color>\nMdef Pierce: <color=#AAFF00FF>+5%</color>",
    "Source": "Echo Mage",
    "Droprate": "50%",
    "Location": "Dark Fortress Lv1",
    "SpriteId": "card"
  },
  {
    "Name": "Echo Necromancer Card",
    "CardId": "NightmareNecromancer",
    "Affix": "Necromancer",
    "Slot": "Head",
    "Stats": "Mdef Pierce: <color=#AAFF00FF>+2% per level</color>",
    "Source": "Echo Necromancer",
    "Droprate": "300%",
    "Location": "Dark Fortress Lv2",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Echo Paladin Card",
    "CardId": "NightmarePaladin",
    "Affix": "Paladin",
    "Slot": "Head",
    "Stats": "Final Damage Reduction: <color=#AAFF00FF>+1% per level</color>\nMp: <color=#FF0073FF>-2% per level</color>",
    "Source": "Echo Paladin",
    "Droprate": "300%",
    "Location": "Dark Fortress Lv2",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Echo Priest Card",
    "CardId": "NightmarePriest",
    "Affix": "Priest",
    "Slot": "Head",
    "Stats": "Healing: <color=#AAFF00FF>+2% per level</color>\nMp Cost: <color=#AAFF00FF>-2% per level</color>",
    "Source": "Echo Priest",
    "Droprate": "300%",
    "Location": "Dark Fortress Lv2",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Echo Rogue Card",
    "CardId": "NightmareRogue",
    "Affix": "Rogue",
    "Slot": "Accessory",
    "Stats": "Atk Spd: <color=#AAFF00FF>+5%</color>\nTotal Flee: <color=#AAFF00FF>+5%</color>",
    "Source": "Echo Rogue",
    "Droprate": "50%",
    "Location": "Dark Fortress Lv1",
    "SpriteId": "card"
  },
  {
    "Name": "Echo Scout Card",
    "CardId": "NightmareScout",
    "Affix": "Scout",
    "Slot": "Accessory",
    "Stats": "Atk: <color=#AAFF00FF>+5</color>\nTotal Hit: <color=#AAFF00FF>+5%</color>",
    "Source": "Echo Scout",
    "Droprate": "50%",
    "Location": "Dark Fortress Lv1",
    "SpriteId": "card"
  },
  {
    "Name": "Echo Shinobi Card",
    "CardId": "NightmareShinobi",
    "Affix": "Shinobi",
    "Slot": "Head",
    "Stats": "Cooldown Recovery: <color=#AAFF00FF>+1% per level</color>\nMp Cost: <color=#FF0073FF>+2% per level</color>",
    "Source": "Echo Shinobi",
    "Droprate": "300%",
    "Location": "Dark Fortress Lv2",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Echo Summoner Card",
    "CardId": "NightmareSummoner",
    "Affix": "Summoner",
    "Slot": "Accessory",
    "Stats": "Summon All Stats: <color=#AAFF00FF>+5</color>",
    "Source": "Echo Summoner",
    "Droprate": "50%",
    "Location": "Dark Fortress Lv1",
    "SpriteId": "card"
  },
  {
    "Name": "Echo Warrior Card",
    "CardId": "NightmareWarrior",
    "Affix": "Warrior",
    "Slot": "Accessory",
    "Stats": "Crit Damage: <color=#AAFF00FF>+5%</color>\nDef Pierce: <color=#AAFF00FF>+5%</color>",
    "Source": "Echo Warrior",
    "Droprate": "50%",
    "Location": "Dark Fortress Lv1",
    "SpriteId": "card"
  },
  {
    "Name": "Echo Wizard Card",
    "CardId": "NightmareWizard",
    "Affix": "Wizard",
    "Slot": "Head",
    "Stats": "Damage Magic: <color=#AAFF00FF>+1% per level</color>\nCast Range: <color=#AAFF00FF>+2</color>",
    "Source": "Echo Wizard",
    "Droprate": "300%",
    "Location": "Dark Fortress Lv2",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Egg Card",
    "CardId": "Egg",
    "Affix": "Vital",
    "Slot": "Head",
    "Stats": "Hp: <color=#AAFF00FF>+100</color>",
    "Source": "Egg",
    "Droprate": "50%",
    "Location": "Sunny Meadows 1",
    "SpriteId": "card"
  },
  {
    "Name": "Egglet Card",
    "CardId": "Egglet",
    "Affix": "Rapid",
    "Slot": "Weapon",
    "Stats": "Atk Spd: <color=#AAFF00FF>+10%</color>\nAgi: <color=#AAFF00FF>+1</color>",
    "Source": "Egglet",
    "Droprate": "50%",
    "Location": "Bunny Woods",
    "SpriteId": "card"
  },
  {
    "Name": "Elder Wisp Blue Card",
    "CardId": "Elder Wisp Blue",
    "Affix": "Glacial",
    "Slot": "Accessory",
    "Stats": "Water Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Elder Wisp Blue",
    "Droprate": "50%",
    "Location": "Crystal Cave",
    "SpriteId": "card"
  },
  {
    "Name": "Elder Wisp Purple Card",
    "CardId": "Elder Wisp Purple",
    "Affix": "Spark",
    "Slot": "Accessory",
    "Stats": "Wind Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Elder Wisp Purple",
    "Droprate": "50%",
    "Location": "Underground Cavern",
    "SpriteId": "card"
  },
  {
    "Name": "Elder Wisp Yellow Card",
    "CardId": "Elder Wisp Yellow",
    "Affix": "Pyre",
    "Slot": "Accessory",
    "Stats": "Fire Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Elder Wisp Yellow",
    "Droprate": "50%",
    "Location": "Demon's Maw",
    "SpriteId": "card"
  },
  {
    "Name": "Eyeball Bat Blue Card",
    "CardId": "Eyeball Bat Blue",
    "Affix": "Radiant",
    "Slot": "Weapon",
    "Stats": "Holy Light Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Eyeball Bat Blue",
    "Droprate": "50%",
    "Location": "Festering Woods 1",
    "SpriteId": "card"
  },
  {
    "Name": "Eyeball Bat Green Card",
    "CardId": "Eyeball Bat Green",
    "Affix": "Purity",
    "Slot": "Shield",
    "Stats": "Undead Resistance: <color=#AAFF00FF>+25%</color>",
    "Source": "Eyeball Bat Green",
    "Droprate": "50%",
    "Location": "Festering Woods 1",
    "SpriteId": "card"
  },
  {
    "Name": "Eyeball Bat Red Card",
    "CardId": "Eyeball Bat Red",
    "Affix": "Vampiric",
    "Slot": "Shield",
    "Stats": "Chance to autocast Lv.2 Life Drain when hit: <color=#AAFF00FF>+1% per level</color>",
    "Source": "Eyeball Bat Red",
    "Droprate": "50%",
    "Location": "Festering Woods 1",
    "SpriteId": "card"
  },
  {
    "Name": "Eyeball Creep Blue Card",
    "CardId": "Eyeball Creep Blue",
    "Affix": "Focus",
    "Slot": "Head",
    "Stats": "Mp: <color=#AAFF00FF>+10%</color>",
    "Source": "Eyeball Creep Blue",
    "Droprate": "50%",
    "Location": "Abyss Castle Crypt",
    "SpriteId": "card"
  },
  {
    "Name": "Eyeball Creep Green Card",
    "CardId": "Eyeball Creep Green",
    "Affix": "Focus",
    "Slot": "Accessory",
    "Stats": "Mp: <color=#AAFF00FF>+10%</color>",
    "Source": "Eyeball Creep Green",
    "Droprate": "50%",
    "Location": "Abyss Castle Crypt",
    "SpriteId": "card"
  },
  {
    "Name": "Eyeball Creep Red Card",
    "CardId": "Eyeball Creep Red",
    "Affix": "Focus",
    "Slot": "Feet",
    "Stats": "Mp: <color=#AAFF00FF>+10%</color>",
    "Source": "Eyeball Creep Red",
    "Droprate": "50%",
    "Location": "Abyss Castle Crypt",
    "SpriteId": "card"
  },
  {
    "Name": "Eyeball Mage Blue Card",
    "CardId": "Eyeball Mage Blue",
    "Affix": "Mana Burn",
    "Slot": "Head",
    "Stats": "Siphon Mp: <color=#AAFF00FF>+3</color>\nMp: <color=#FF0073FF>-50%</color>",
    "Source": "Eyeball Mage Blue",
    "Droprate": "50%",
    "Location": "Abyss Castle Library",
    "SpriteId": "card"
  },
  {
    "Name": "Eyeball Mage Green Card",
    "CardId": "Eyeball Mage Green",
    "Affix": "Radiant",
    "Slot": "Weapon",
    "Stats": "Exorcism Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Eyeball Mage Green",
    "Droprate": "50%",
    "Location": "Abyss Castle Library",
    "SpriteId": "card"
  },
  {
    "Name": "Eyeball Mage Red Card",
    "CardId": "Eyeball Mage Red",
    "Affix": "Vampiric",
    "Slot": "Shield",
    "Stats": "Health leech: <color=#AAFF00FF>+5%</color>",
    "Source": "Eyeball Mage Red",
    "Droprate": "50%",
    "Location": "Abyss Castle Library",
    "SpriteId": "card"
  },
  {
    "Name": "Fangroot Card",
    "CardId": "Alien Biteroot",
    "Affix": "Resistance",
    "Slot": "Feet",
    "Stats": "Resistance to Bleeding: <color=#AAFF00FF>+50%</color>",
    "Source": "Fangroot",
    "Droprate": "50%",
    "Location": "Dark Forest",
    "SpriteId": "card"
  },
  {
    "Name": "Festive Baby Card",
    "CardId": "Mini Ice Bear B",
    "Affix": "Healthy",
    "Slot": "Legs",
    "Stats": "Hp: <color=#AAFF00FF>+10%</color>",
    "Source": "Festive Baby",
    "Droprate": "50%",
    "Location": "Starfall Tundra",
    "SpriteId": "card"
  },
  {
    "Name": "Festive Bear Card",
    "CardId": "Ice Bear B",
    "Affix": "Focus",
    "Slot": "Legs",
    "Stats": "Mp: <color=#AAFF00FF>+10%</color>",
    "Source": "Festive Bear",
    "Droprate": "50%",
    "Location": "Starfall Tundra",
    "SpriteId": "card"
  },
  {
    "Name": "Fire Card",
    "CardId": "Fire",
    "Affix": "Light",
    "Slot": "Head",
    "Stats": "Weight Limit: <color=#AAFF00FF>+100 per level</color>",
    "Source": "Fire",
    "Droprate": "50%",
    "Location": "Demon's Maw",
    "SpriteId": "card"
  },
  {
    "Name": "Fire Mage Card",
    "CardId": "Fire Mage",
    "Affix": "Mind",
    "Slot": "Accessory",
    "Stats": "Matk: <color=#AAFF00FF>+4%</color>",
    "Source": "Fire Mage",
    "Droprate": "50%",
    "Location": "Demon's Maw",
    "SpriteId": "card"
  },
  {
    "Name": "FIsh Blue Card",
    "CardId": "FIsh Blue",
    "Affix": "Fading",
    "Slot": "Legs",
    "Stats": "Threat Generation: <color=#FF0073FF>-25%</color>",
    "Source": "FIsh Blue",
    "Droprate": "50%",
    "Location": "Sunken Depths",
    "SpriteId": "card"
  },
  {
    "Name": "Fish Man Blue Card",
    "CardId": "Fish Man Blue",
    "Affix": "Mind",
    "Slot": "Legs",
    "Stats": "Matk: <color=#AAFF00FF>+10</color>",
    "Source": "Fish Man Blue",
    "Droprate": "50%",
    "Location": "Sunken Depths",
    "SpriteId": "card"
  },
  {
    "Name": "Fish Man Pink Card",
    "CardId": "Fish Man Pink",
    "Affix": "Power",
    "Slot": "Legs",
    "Stats": "Atk: <color=#AAFF00FF>+10</color>",
    "Source": "Fish Man Pink",
    "Droprate": "50%",
    "Location": "Sunken Depths",
    "SpriteId": "card"
  },
  {
    "Name": "Fish Man Yellow Card",
    "CardId": "Fish Man Yellow",
    "Affix": "Precision",
    "Slot": "Legs",
    "Stats": "Crit: <color=#AAFF00FF>+5</color>\nCrit Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Fish Man Yellow",
    "Droprate": "50%",
    "Location": "Sunken Depths",
    "SpriteId": "card"
  },
  {
    "Name": "Fish Pink Card",
    "CardId": "Fish Pink",
    "Affix": "Violent",
    "Slot": "Legs",
    "Stats": "Atk: <color=#AAFF00FF>+5</color>\nMatk: <color=#AAFF00FF>+5</color>",
    "Source": "Fish Pink",
    "Droprate": "50%",
    "Location": "Sunken Depths",
    "SpriteId": "card"
  },
  {
    "Name": "Fish Yellow Card",
    "CardId": "Fish Yellow",
    "Affix": "Perfect",
    "Slot": "Legs",
    "Stats": "Perfect Dodge: <color=#AAFF00FF>+5%</color>",
    "Source": "Fish Yellow",
    "Droprate": "50%",
    "Location": "Sunken Depths",
    "SpriteId": "card"
  },
  {
    "Name": "Flame Card",
    "CardId": "Flame",
    "Affix": "Flaming",
    "Slot": "Weapon",
    "Stats": "Fireball Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Flame",
    "Droprate": "50%",
    "Location": "Demon's Maw",
    "SpriteId": "card"
  },
  {
    "Name": "Fledgling Card",
    "CardId": "Fledgling",
    "Affix": "Impaling",
    "Slot": "Weapon",
    "Stats": "Impale Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Fledgling",
    "Droprate": "50%",
    "Location": "Sunny Meadows 2",
    "SpriteId": "card"
  },
  {
    "Name": "Flora Card",
    "CardId": "Flora",
    "Affix": "Hoarfrost",
    "Slot": "Weapon",
    "Stats": "Damage vs Water Enemies: <color=#AAFF00FF>+10%</color>",
    "Source": "Flora",
    "Droprate": "50%",
    "Location": "Mystic Lake 1",
    "SpriteId": "card"
  },
  {
    "Name": "Flower Pot Monster Card",
    "CardId": "Flower Pot Monster",
    "Affix": "Quagmire",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.2 Earth Spikes</color>",
    "Source": "Flower Pot Monster",
    "Droprate": "50%",
    "Location": "Treant Trail",
    "SpriteId": "card"
  },
  {
    "Name": "Fungi Card",
    "CardId": "Fungi",
    "Affix": "Heal",
    "Slot": "Accessory",
    "Stats": "Grants <color=#AAFF00FF>Lv.5 Heal</color>",
    "Source": "Fungi",
    "Droprate": "50%",
    "Location": "Lake Field",
    "SpriteId": "card"
  },
  {
    "Name": "Ghost Card",
    "CardId": "Ghost",
    "Affix": "Dissonance",
    "Slot": "Weapon",
    "Stats": "Dissonance Well Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Ghost",
    "Droprate": "50%",
    "Location": "Sanctum of Light",
    "SpriteId": "card"
  },
  {
    "Name": "Gloom Card",
    "CardId": "Gloom",
    "Affix": "Undead",
    "Slot": "Weapon",
    "Stats": "Undead Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Gloom",
    "Droprate": "50%",
    "Location": "Abyss Castle Crypt",
    "SpriteId": "card"
  },
  {
    "Name": "Glow Wisp Blue Card",
    "CardId": "Glow Wisp Blue",
    "Affix": "Glacial",
    "Slot": "Weapon",
    "Stats": "Water Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Glow Wisp Blue",
    "Droprate": "50%",
    "Location": "Mystic Lake 1",
    "SpriteId": "card"
  },
  {
    "Name": "Glow Wisp Purple Card",
    "CardId": "Glow Wisp Purple",
    "Affix": "Spark",
    "Slot": "Weapon",
    "Stats": "Wind Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Glow Wisp Purple",
    "Droprate": "50%",
    "Location": "Windy Desert",
    "SpriteId": "card"
  },
  {
    "Name": "Glow Wisp Yellow Card",
    "CardId": "Glow Wisp Yellow",
    "Affix": "Pyre",
    "Slot": "Weapon",
    "Stats": "Fire Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Glow Wisp Yellow",
    "Droprate": "50%",
    "Location": "Fairy Glen",
    "SpriteId": "card"
  },
  {
    "Name": "Goblin Giant Devil Card",
    "CardId": "Goblin Giant Devil",
    "Affix": "Quaking",
    "Slot": "Weapon",
    "Stats": "Damage vs Earth Enemies: <color=#AAFF00FF>+10%</color>",
    "Source": "Goblin Giant Devil",
    "Droprate": "50%",
    "Location": "Goblin Village",
    "SpriteId": "card"
  },
  {
    "Name": "Goblin Giant Mage Card",
    "CardId": "Goblin Giant Mage",
    "Affix": "Earthen",
    "Slot": "Weapon",
    "Stats": "<color=#FF9700FF>Enchant weapon with <sprite name=Elements_8> <color=#BB7B2FFF>Earth</color> element</color>",
    "Source": "Goblin Giant Mage",
    "Droprate": "50%",
    "Location": "Goblin Village",
    "SpriteId": "card"
  },
  {
    "Name": "Goblin King Card",
    "CardId": "Goblin Giant Gold",
    "Affix": "Earthen",
    "Slot": "Chest",
    "Stats": "<color=#FF9700FF>Convert to <sprite name=Elements_8> <color=#BB7B2FFF>Earth</color> element</color>",
    "Source": "Goblin King",
    "Droprate": "300%",
    "Location": "Goblin Village",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Goblin Minion Card",
    "CardId": "Goblin Minion",
    "Affix": "Bashing",
    "Slot": "Weapon",
    "Stats": "Bash Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Goblin Minion",
    "Droprate": "50%",
    "Location": "Goblin Field",
    "SpriteId": "card"
  },
  {
    "Name": "Goblin Trooper Assassin Card",
    "CardId": "Goblin Trooper Assassin",
    "Affix": "Mobile",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.1 Shadow Step</color>",
    "Source": "Goblin Trooper Assassin",
    "Droprate": "50%",
    "Location": "Goblin Field",
    "SpriteId": "card"
  },
  {
    "Name": "Goblin Trooper Card",
    "CardId": "Goblin Trooper",
    "Affix": "Mudproof",
    "Slot": "Legs",
    "Stats": "Earth Resistance: <color=#AAFF00FF>+15%</color>",
    "Source": "Goblin Trooper",
    "Droprate": "50%",
    "Location": "Goblin Field",
    "SpriteId": "card"
  },
  {
    "Name": "Goblin Trooper Mage Card",
    "CardId": "Goblin Trooper Mage",
    "Affix": "Free",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.3 Free Cast</color>",
    "Source": "Goblin Trooper Mage",
    "Droprate": "50%",
    "Location": "Goblin Field",
    "SpriteId": "card"
  },
  {
    "Name": "Goblin Trooper Soldier Card",
    "CardId": "Goblin Trooper Soldier",
    "Affix": "Slashing",
    "Slot": "Weapon",
    "Stats": "Twin Cleave Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Goblin Trooper Soldier",
    "Droprate": "50%",
    "Location": "Goblin Field",
    "SpriteId": "card"
  },
  {
    "Name": "Goblin Warblade Card",
    "CardId": "Goblin Warblade",
    "Affix": "Spiked",
    "Slot": "Chest",
    "Stats": "Reflect Damage: <color=#AAFF00FF>+30%</color>",
    "Source": "Goblin Warblade",
    "Droprate": "50%",
    "Location": "Goblin Warcamp",
    "SpriteId": "card"
  },
  {
    "Name": "Goblin Warchief Card",
    "CardId": "Goblin Warchief",
    "Affix": "Elemental",
    "Slot": "Weapon",
    "Stats": "Fire Damage: <color=#AAFF00FF>+5%</color>\nWater Damage: <color=#AAFF00FF>+5%</color>\nWind Damage: <color=#AAFF00FF>+5%</color>\nEarth Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Goblin Warchief",
    "Droprate": "300%",
    "Location": "Goblin Warcamp",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Goblin Warcrusher Card",
    "CardId": "Goblin Warcrusher",
    "Affix": "Seismic",
    "Slot": "Accessory",
    "Stats": "Earth Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Goblin Warcrusher",
    "Droprate": "50%",
    "Location": "Goblin Warcamp",
    "SpriteId": "card"
  },
  {
    "Name": "Goblin Warlock Card",
    "CardId": "Goblin Warlock",
    "Affix": "Mind",
    "Slot": "Head",
    "Stats": "Matk: <color=#AAFF00FF>+4%</color>",
    "Source": "Goblin Warlock",
    "Droprate": "50%",
    "Location": "Goblin Warcamp",
    "SpriteId": "card"
  },
  {
    "Name": "Golem Earth Card",
    "CardId": "Golem Earth",
    "Affix": "Stone",
    "Slot": "Chest",
    "Stats": "Def: <color=#AAFF00FF>+15%</color>",
    "Source": "Golem Earth",
    "Droprate": "50%",
    "Location": "Windy Desert South",
    "SpriteId": "card"
  },
  {
    "Name": "Golem Fire Card",
    "CardId": "Golem Fire",
    "Affix": "Stone",
    "Slot": "Head",
    "Stats": "Def: <color=#AAFF00FF>+10%</color>",
    "Source": "Golem Fire",
    "Droprate": "50%",
    "Location": "Demon's Maw",
    "SpriteId": "card"
  },
  {
    "Name": "Golem Ice Card",
    "CardId": "Golem Ice",
    "Affix": "Stone",
    "Slot": "Shield",
    "Stats": "Def: <color=#AAFF00FF>+3% per level</color>",
    "Source": "Golem Ice",
    "Droprate": "50%",
    "Location": "Crystal Cave",
    "SpriteId": "card"
  },
  {
    "Name": "Grim Reaper Card",
    "CardId": "Grim Reaper",
    "Affix": "Undead",
    "Slot": "Accessory",
    "Stats": "Undead Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Grim Reaper",
    "Droprate": "50%",
    "Location": "Abyss Castle Crypt",
    "SpriteId": "card"
  },
  {
    "Name": "Gripper Robot Card",
    "CardId": "Gripper Robot",
    "Affix": "Immune",
    "Slot": "Chest",
    "Stats": "Neutral Resistance: <color=#AAFF00FF>+10%</color>\nHp: <color=#AAFF00FF>+10%</color>",
    "Source": "Gripper Robot",
    "Droprate": "50%",
    "Location": "The Forge",
    "SpriteId": "card"
  },
  {
    "Name": "Hare Card",
    "CardId": "Hare",
    "Affix": "Fleet",
    "Slot": "Feet",
    "Stats": "Move Spd: <color=#AAFF00FF>+20%</color>",
    "Source": "Hare",
    "Droprate": "300%",
    "Location": "Bunny Woods",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Haunt Card",
    "CardId": "Haunt",
    "Affix": "Lightproof",
    "Slot": "Legs",
    "Stats": "Holy Resistance: <color=#AAFF00FF>+15%</color>",
    "Source": "Haunt",
    "Droprate": "50%",
    "Location": "Sanctum of Light",
    "SpriteId": "card"
  },
  {
    "Name": "Hermit King Card",
    "CardId": "Hermit King",
    "Affix": "Hydro",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.1 Hydro Vortex</color>",
    "Source": "Hermit King",
    "Droprate": "300%",
    "Location": "Mystic Lake 2",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Horror Card",
    "CardId": "Horror",
    "Affix": "Savage",
    "Slot": "Head",
    "Stats": "Crit Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Horror",
    "Droprate": "50%",
    "Location": "Forgotten Depths 2",
    "SpriteId": "card"
  },
  {
    "Name": "Housefly Icky Card",
    "CardId": "Housefly Icky",
    "Affix": "Assassin's",
    "Slot": "Accessory",
    "Stats": "Crit: <color=#AAFF00FF>+5</color>",
    "Source": "Housefly Icky",
    "Droprate": "50%",
    "Location": "Swamp",
    "SpriteId": "card"
  },
  {
    "Name": "Housefly Junk Card",
    "CardId": "Housefly Junk",
    "Affix": "Assassin's",
    "Slot": "Head",
    "Stats": "Total Critical Rate: <color=#AAFF00FF>+15%</color>",
    "Source": "Housefly Junk",
    "Droprate": "50%",
    "Location": "Swamp Wilderness",
    "SpriteId": "card"
  },
  {
    "Name": "Housefly Nom Card",
    "CardId": "Housefly Nom",
    "Affix": "Assassin's",
    "Slot": "Weapon",
    "Stats": "Crit: <color=#AAFF00FF>+10</color>",
    "Source": "Housefly Nom",
    "Droprate": "50%",
    "Location": "Swamp",
    "SpriteId": "card"
  },
  {
    "Name": "Hydro Turtle Card",
    "CardId": "Titan Turtle Sci Blue",
    "Affix": "Freezing",
    "Slot": "Weapon",
    "Stats": "Blizzard Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Hydro Turtle",
    "Droprate": "50%",
    "Location": "Turtle Nexus",
    "SpriteId": "card"
  },
  {
    "Name": "Ice Baby Card",
    "CardId": "Mini Ice Bear A",
    "Affix": "Thawing",
    "Slot": "Legs",
    "Stats": "Resistance to Frozen: <color=#AAFF00FF>+50%</color>",
    "Source": "Ice Baby",
    "Droprate": "50%",
    "Location": "Starfall Tundra",
    "SpriteId": "card"
  },
  {
    "Name": "Ice Card",
    "CardId": "Ice",
    "Affix": "Icepick",
    "Slot": "Accessory",
    "Stats": "<color=#FF9700FF>Immune to Reflect damage</color>",
    "Source": "Ice",
    "Droprate": "50%",
    "Location": "Crystal Cave",
    "SpriteId": "card"
  },
  {
    "Name": "Ice Mage Card",
    "CardId": "Ice Mage",
    "Affix": "Thawing",
    "Slot": "Chest",
    "Stats": "<color=#FF9700FF>Convert to <sprite name=Elements_6> <color=#79D7FDFF>Water</color> element</color>\nResistance to Frozen: <color=#AAFF00FF>+50%</color>",
    "Source": "Ice Mage",
    "Droprate": "300%",
    "Location": "Crystal Cave",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Icicle Card",
    "CardId": "Icicle",
    "Affix": "Thawing",
    "Slot": "Feet",
    "Stats": "Resistance to Slow: <color=#AAFF00FF>+50%</color>",
    "Source": "Icicle",
    "Droprate": "50%",
    "Location": "Crystal Cave",
    "SpriteId": "card"
  },
  {
    "Name": "Imp Demon Card",
    "CardId": "Imp Demon",
    "Affix": "Spiked",
    "Slot": "Accessory",
    "Stats": "Reflect Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Imp Demon",
    "Droprate": "50%",
    "Location": "Demon's Maw",
    "SpriteId": "card"
  },
  {
    "Name": "Imp Devil Card",
    "CardId": "Imp Devil",
    "Affix": "Meteoric",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.5 Meteor</color>\nFire Pillar max instances: <color=#AAFF00FF>+1</color>",
    "Source": "Imp Devil",
    "Droprate": "300%",
    "Location": "Demon's Maw",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Imp Mischief Card",
    "CardId": "Imp Mischief",
    "Affix": "Mischief",
    "Slot": "Shield",
    "Stats": "Chance to reflect single target magic: <color=#AAFF00FF>+2% per level</color>",
    "Source": "Imp Mischief",
    "Droprate": "50%",
    "Location": "Demon's Maw",
    "SpriteId": "card"
  },
  {
    "Name": "Kraken Card",
    "CardId": "Eyeball Monster",
    "Affix": "Abyss",
    "Slot": "Head",
    "Stats": "Ice Shard Projectiles: <color=#AAFF00FF>+3</color>\nGrants <color=#AAFF00FF>Lv.1 Blizzard</color>",
    "Source": "Kraken",
    "Droprate": "300%",
    "Location": "Sunken Depths",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Little Star Card",
    "CardId": "Alien Star",
    "Affix": "Energy",
    "Slot": "Weapon",
    "Stats": "Mp Regen: <color=#AAFF00FF>+25%</color>",
    "Source": "Little Star",
    "Droprate": "50%",
    "Location": "Starfall Tundra",
    "SpriteId": "card"
  },
  {
    "Name": "Lurker Card",
    "CardId": "Lurker",
    "Affix": "Savage",
    "Slot": "Accessory",
    "Stats": "Crit Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Lurker",
    "Droprate": "50%",
    "Location": "Forgotten Depths 1",
    "SpriteId": "card"
  },
  {
    "Name": "Mega Ice Golem Card",
    "CardId": "Mega Ice Golem",
    "Affix": "Permafrost",
    "Slot": "Head",
    "Stats": "Chance to autocast Lv.2 Ice Shard when hit: <color=#AAFF00FF>+1% per level</color>\nGrants <color=#AAFF00FF>Lv.1 Frost Rounds</color>",
    "Source": "Mega Ice Golem",
    "Droprate": "300%",
    "Location": "Starfall Tundra",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Merman Blue Card",
    "CardId": "Fish Merman Blue",
    "Affix": "Status",
    "Slot": "Legs",
    "Stats": "Damage Status: <color=#AAFF00FF>+5%</color>",
    "Source": "Merman Blue",
    "Droprate": "50%",
    "Location": "Sunken Depths",
    "SpriteId": "card"
  },
  {
    "Name": "Merman Pink Card",
    "CardId": "Fish Merman Pink",
    "Affix": "Savage",
    "Slot": "Legs",
    "Stats": "Crit Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Merman Pink",
    "Droprate": "50%",
    "Location": "Sunken Depths",
    "SpriteId": "card"
  },
  {
    "Name": "Merman Yellow Card",
    "CardId": "Fish Merman Yellow",
    "Affix": "Lightning",
    "Slot": "Weapon",
    "Stats": "Chain Lightning Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Merman Yellow",
    "Droprate": "50%",
    "Location": "Sunken Depths",
    "SpriteId": "card"
  },
  {
    "Name": "Mole Rat Card",
    "CardId": "Mole Rat",
    "Affix": "Seismic",
    "Slot": "Weapon",
    "Stats": "Earth Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Mole Rat",
    "Droprate": "50%",
    "Location": "Windy Desert North",
    "SpriteId": "card"
  },
  {
    "Name": "Mole Rat King Card",
    "CardId": "Mole Rat King",
    "Affix": "Stomping",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.1 Stomp</color>",
    "Source": "Mole Rat King",
    "Droprate": "50%",
    "Location": "Windy Desert North",
    "SpriteId": "card"
  },
  {
    "Name": "Mosquito Bug Card",
    "CardId": "Mosquito Bug",
    "Affix": "Vampiric",
    "Slot": "Accessory",
    "Stats": "Health leech: <color=#AAFF00FF>+5%</color>",
    "Source": "Mosquito Bug",
    "Droprate": "50%",
    "Location": "Swamp",
    "SpriteId": "card"
  },
  {
    "Name": "Mosquito Pester Card",
    "CardId": "Mosquito Pester",
    "Affix": "Windproof",
    "Slot": "Legs",
    "Stats": "Wind Resistance: <color=#AAFF00FF>+15%</color>",
    "Source": "Mosquito Pester",
    "Droprate": "50%",
    "Location": "Swamp",
    "SpriteId": "card"
  },
  {
    "Name": "Mosquito Stinger Card",
    "CardId": "Mosquito Stinger",
    "Affix": "Haste",
    "Slot": "Accessory",
    "Stats": "Grants <color=#AAFF00FF>Lv.5 Haste</color>",
    "Source": "Mosquito Stinger",
    "Droprate": "50%",
    "Location": "Swamp Wilderness",
    "SpriteId": "card"
  },
  {
    "Name": "Moth Celestial Card",
    "CardId": "Moth Celestial",
    "Affix": "Lightproof",
    "Slot": "Shield",
    "Stats": "Holy Resistance: <color=#AAFF00FF>+25%</color>",
    "Source": "Moth Celestial",
    "Droprate": "50%",
    "Location": "Fairy Glen",
    "SpriteId": "card"
  },
  {
    "Name": "Moth Luna Card",
    "CardId": "Moth Luna",
    "Affix": "Unholy",
    "Slot": "Weapon",
    "Stats": "Damage vs Holy Enemies: <color=#AAFF00FF>+10%</color>",
    "Source": "Moth Luna",
    "Droprate": "50%",
    "Location": "Fairy Glen",
    "SpriteId": "card"
  },
  {
    "Name": "Moth Moon Card",
    "CardId": "Moth Moon",
    "Affix": "Cleric's",
    "Slot": "Accessory",
    "Stats": "Healing: <color=#AAFF00FF>+10%</color>",
    "Source": "Moth Moon",
    "Droprate": "50%",
    "Location": "Fairy Glen",
    "SpriteId": "card"
  },
  {
    "Name": "Mushroom Card",
    "CardId": "Mushroom",
    "Affix": "Occult",
    "Slot": "Weapon",
    "Stats": "Matk: <color=#AAFF00FF>+5</color>",
    "Source": "Mushroom",
    "Droprate": "50%",
    "Location": "Lake Field",
    "SpriteId": "card"
  },
  {
    "Name": "Nightmare Card",
    "CardId": "Nightmare",
    "Affix": "Darkproof",
    "Slot": "Shield",
    "Stats": "Shadow Resistance: <color=#AAFF00FF>+25%</color>",
    "Source": "Nightmare",
    "Droprate": "50%",
    "Location": "Abyss Castle Library",
    "SpriteId": "card"
  },
  {
    "Name": "Nose Robot Card",
    "CardId": "Nose Robot",
    "Affix": "Overheat",
    "Slot": "Head",
    "Stats": "Chance to autocast Lv.2 Fire Pillar when hit: <color=#AAFF00FF>+1% per level</color>",
    "Source": "Nose Robot",
    "Droprate": "50%",
    "Location": "The Forge",
    "SpriteId": "card"
  },
  {
    "Name": "Nozzle Robot Card",
    "CardId": "Nozzle Robot",
    "Affix": "Volatile",
    "Slot": "Accessory",
    "Stats": "Atk Spd: <color=#AAFF00FF>+25%</color>\n<color=#FF0073FF>Cannot Attack</color>",
    "Source": "Nozzle Robot",
    "Droprate": "50%",
    "Location": "The Forge",
    "SpriteId": "card"
  },
  {
    "Name": "Octopus Baby Blue Card",
    "CardId": "Octopus Baby Blue",
    "Affix": "Elusive",
    "Slot": "Accessory",
    "Stats": "Total Flee: <color=#AAFF00FF>+5%</color>",
    "Source": "Octopus Baby Blue",
    "Droprate": "50%",
    "Location": "Sunken Depths",
    "SpriteId": "card"
  },
  {
    "Name": "Octopus Baby Orange Card",
    "CardId": "Octopus Baby Orange",
    "Affix": "Elusive",
    "Slot": "Head",
    "Stats": "Total Flee: <color=#AAFF00FF>+5%</color>",
    "Source": "Octopus Baby Orange",
    "Droprate": "50%",
    "Location": "Sunken Depths",
    "SpriteId": "card"
  },
  {
    "Name": "Octopus Baby Purple Card",
    "CardId": "Octopus Baby Purple",
    "Affix": "Elusive",
    "Slot": "Feet",
    "Stats": "Total Flee: <color=#AAFF00FF>+5%</color>",
    "Source": "Octopus Baby Purple",
    "Droprate": "50%",
    "Location": "Sunken Depths",
    "SpriteId": "card"
  },
  {
    "Name": "Octopus King Blue Card",
    "CardId": "Octopus King Blue",
    "Affix": "Mind",
    "Slot": "Legs",
    "Stats": "Damage Magic: <color=#AAFF00FF>+5%</color>",
    "Source": "Octopus King Blue",
    "Droprate": "50%",
    "Location": "Turtle Nexus",
    "SpriteId": "card"
  },
  {
    "Name": "Octopus King Orange Card",
    "CardId": "Octopus King Orange",
    "Affix": "Melee",
    "Slot": "Legs",
    "Stats": "Damage Melee: <color=#AAFF00FF>+5%</color>",
    "Source": "Octopus King Orange",
    "Droprate": "50%",
    "Location": "Turtle Nexus",
    "SpriteId": "card"
  },
  {
    "Name": "Octopus King Purple Card",
    "CardId": "Octopus King Purple",
    "Affix": "Ranged",
    "Slot": "Legs",
    "Stats": "Damage Ranged: <color=#AAFF00FF>+5%</color>",
    "Source": "Octopus King Purple",
    "Droprate": "50%",
    "Location": "Turtle Nexus",
    "SpriteId": "card"
  },
  {
    "Name": "Octopus Orange Card",
    "CardId": "Octopus Orange",
    "Affix": "Status",
    "Slot": "Accessory",
    "Stats": "Damage Status: <color=#AAFF00FF>+5%</color>",
    "Source": "Octopus Orange",
    "Droprate": "50%",
    "Location": "Sunken Depths",
    "SpriteId": "card"
  },
  {
    "Name": "Octopus Purple Card",
    "CardId": "Octopus Purple",
    "Affix": "Status",
    "Slot": "Head",
    "Stats": "Damage Status: <color=#AAFF00FF>+5%</color>",
    "Source": "Octopus Purple",
    "Droprate": "50%",
    "Location": "Sunken Depths",
    "SpriteId": "card"
  },
  {
    "Name": "Octopus White Card",
    "CardId": "Octopus White",
    "Affix": "Status",
    "Slot": "Weapon",
    "Stats": "Damage Status: <color=#AAFF00FF>+5%</color>",
    "Source": "Octopus White",
    "Droprate": "50%",
    "Location": "Sunken Depths",
    "SpriteId": "card"
  },
  {
    "Name": "Petal Card",
    "CardId": "Petal",
    "Affix": "Tidal",
    "Slot": "Weapon",
    "Stats": "<color=#FF9700FF>Enchant weapon with <sprite name=Elements_6> <color=#79D7FDFF>Water</color> element</color>",
    "Source": "Petal",
    "Droprate": "50%",
    "Location": "Mystic Lake 1",
    "SpriteId": "card"
  },
  {
    "Name": "Phantom Card",
    "CardId": "Phantom",
    "Affix": "Arcanum",
    "Slot": "Head",
    "Stats": "Mp Cost: <color=#AAFF00FF>-15%</color>",
    "Source": "Phantom",
    "Droprate": "50%",
    "Location": "Sanctum of Light",
    "SpriteId": "card"
  },
  {
    "Name": "Plant Chewer Card",
    "CardId": "Plant Chewer",
    "Affix": "Immune",
    "Slot": "Shield",
    "Stats": "Neutral Resistance: <color=#AAFF00FF>+20%</color>",
    "Source": "Plant Chewer",
    "Droprate": "50%",
    "Location": "Windy Desert South",
    "SpriteId": "card"
  },
  {
    "Name": "Poison Bomb Card",
    "CardId": "Poison Bomb",
    "Affix": "Mystery",
    "Slot": "Weapon",
    "Stats": "All Stats: <color=#AAFF00FF>+1</color>\nHp: <color=#AAFF00FF>+5%</color>\nMp: <color=#AAFF00FF>+5%</color>",
    "Source": "Poison Bomb",
    "Droprate": "50%",
    "Location": "Underground Cavern",
    "SpriteId": "card"
  },
  {
    "Name": "Pollen Card",
    "CardId": "Pollen",
    "Affix": "Elusive",
    "Slot": "Chest",
    "Stats": "Flee: <color=#AAFF00FF>+15</color>",
    "Source": "Pollen",
    "Droprate": "50%",
    "Location": "Sunny Meadows 1",
    "SpriteId": "card"
  },
  {
    "Name": "Posy Card",
    "CardId": "Posy",
    "Affix": "Icy",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.2 Icebolt</color>\nChance to autocast Lv.2 Icebolt when attacking: <color=#AAFF00FF>+10%</color>",
    "Source": "Posy",
    "Droprate": "50%",
    "Location": "Mystic Lake 1",
    "SpriteId": "card"
  },
  {
    "Name": "Queen Worm Card",
    "CardId": "Queen Worm",
    "Affix": "Toxic",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.1 Venom Coating</color>",
    "Source": "Queen Worm",
    "Droprate": "300%",
    "Location": "Swamp Wilderness",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Rabbit Card",
    "CardId": "Rabbit",
    "Affix": "Swift",
    "Slot": "Feet",
    "Stats": "Move Spd: <color=#AAFF00FF>+10%</color>",
    "Source": "Rabbit",
    "Droprate": "50%",
    "Location": "Bunny Woods",
    "SpriteId": "card"
  },
  {
    "Name": "Rat Dark Card",
    "CardId": "Rat Dark",
    "Affix": null,
    "Slot": "Legs",
    "Stats": "Flee: <color=#AAFF00FF>+10</color>\nAgi: <color=#AAFF00FF>+1</color>",
    "Source": "Rat Dark",
    "Droprate": "50%",
    "Location": "Nevaris Sewers",
    "SpriteId": "card"
  },
  {
    "Name": "Rat Grey Card",
    "CardId": "Rat Grey",
    "Affix": null,
    "Slot": "Shield",
    "Stats": "Resistance to Poison: <color=#AAFF00FF>+50%</color>\nVit: <color=#AAFF00FF>+1</color>",
    "Source": "Rat Grey",
    "Droprate": "50%",
    "Location": "Nevaris Sewers",
    "SpriteId": "card"
  },
  {
    "Name": "Rat White Card",
    "CardId": "Rat White",
    "Affix": null,
    "Slot": "Accessory",
    "Stats": "Hit: <color=#AAFF00FF>+10</color>\nDex: <color=#AAFF00FF>+1</color>",
    "Source": "Rat White",
    "Droprate": "50%",
    "Location": "Nevaris Sewers",
    "SpriteId": "card"
  },
  {
    "Name": "Razor Robot Card",
    "CardId": "Razor Robot",
    "Affix": "Rapid",
    "Slot": "Feet",
    "Stats": "Atk Spd: <color=#AAFF00FF>+5%</color>\nMove Spd: <color=#AAFF00FF>+5%</color>",
    "Source": "Razor Robot",
    "Droprate": "50%",
    "Location": "The Forge",
    "SpriteId": "card"
  },
  {
    "Name": "Scorpion Card",
    "CardId": "Scorpion",
    "Affix": "Fireproof",
    "Slot": "Shield",
    "Stats": "Fire Resistance: <color=#AAFF00FF>+25%</color>",
    "Source": "Scorpion",
    "Droprate": "50%",
    "Location": "Windy Desert North",
    "SpriteId": "card"
  },
  {
    "Name": "Scorpion King Card",
    "CardId": "Scorpion King",
    "Affix": "Blazing",
    "Slot": "Chest",
    "Stats": "<color=#FF9700FF>Convert to <sprite name=Elements_5> <color=#FF7026FF>Fire</color> element</color>",
    "Source": "Scorpion King",
    "Droprate": "300%",
    "Location": "Windy Desert North",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Scorpling Card",
    "CardId": "Scorpling",
    "Affix": "Ashen",
    "Slot": "Weapon",
    "Stats": "Damage vs Fire Enemies: <color=#AAFF00FF>+10%</color>",
    "Source": "Scorpling",
    "Droprate": "50%",
    "Location": "Windy Desert North",
    "SpriteId": "card"
  },
  {
    "Name": "Seed Card",
    "CardId": "Seed",
    "Affix": "Flurry",
    "Slot": "Weapon",
    "Stats": "Piercing Flurry Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Seed",
    "Droprate": "50%",
    "Location": "Sunny Meadows 1",
    "SpriteId": "card"
  },
  {
    "Name": "Shade Card",
    "CardId": "Shade",
    "Affix": "Mystery",
    "Slot": "Head",
    "Stats": "All Stats: <color=#AAFF00FF>+1</color>\nHp: <color=#AAFF00FF>+5%</color>\nMp: <color=#AAFF00FF>+5%</color>",
    "Source": "Shade",
    "Droprate": "50%",
    "Location": "Demon's Maw",
    "SpriteId": "card"
  },
  {
    "Name": "Shadow Card",
    "CardId": "Shadow",
    "Affix": "Mystery",
    "Slot": "Accessory",
    "Stats": "All Stats: <color=#AAFF00FF>+1</color>\nHp: <color=#AAFF00FF>+5%</color>\nMp: <color=#AAFF00FF>+5%</color>",
    "Source": "Shadow",
    "Droprate": "50%",
    "Location": "Demon's Maw",
    "SpriteId": "card"
  },
  {
    "Name": "Shadow Ice Card",
    "CardId": "Ice Starflake C",
    "Affix": "Cloaking",
    "Slot": "Legs",
    "Stats": "Perfect Cloaking: <color=#FF9700FF>undetectable by shadow monsters when invisible</color>",
    "Source": "Shadow Ice",
    "Droprate": "50%",
    "Location": "Starfall Tundra",
    "SpriteId": "card"
  },
  {
    "Name": "Shark Baby Card",
    "CardId": "Shark Baby",
    "Affix": "Taunting",
    "Slot": "Shield",
    "Stats": "Threat Generation: <color=#AAFF00FF>+25% per level</color>",
    "Source": "Shark Baby",
    "Droprate": "50%",
    "Location": "Stormreef Isle",
    "SpriteId": "card"
  },
  {
    "Name": "Shark Card",
    "CardId": "Shark",
    "Affix": "Taunting",
    "Slot": "Legs",
    "Stats": "Threat Generation: <color=#AAFF00FF>+25% per level</color>",
    "Source": "Shark",
    "Droprate": "50%",
    "Location": "Sunken Depths",
    "SpriteId": "card"
  },
  {
    "Name": "Shark Pirate Card",
    "CardId": "Shark Humanoid",
    "Affix": "Taunting",
    "Slot": "Weapon",
    "Stats": "Threat Generation: <color=#AAFF00FF>+25% per level</color>",
    "Source": "Shark Pirate",
    "Droprate": "50%",
    "Location": "Stormreef Isle",
    "SpriteId": "card"
  },
  {
    "Name": "Shell Card",
    "CardId": "Shell",
    "Affix": "Immune",
    "Slot": "Legs",
    "Stats": "Neutral Resistance: <color=#AAFF00FF>+10%</color>",
    "Source": "Shell",
    "Droprate": "50%",
    "Location": "Mystic Lake 2",
    "SpriteId": "card"
  },
  {
    "Name": "Shell Robot Card",
    "CardId": "Shell Robot",
    "Affix": "Rapid",
    "Slot": "Legs",
    "Stats": "Atk Spd: <color=#AAFF00FF>+10%</color>",
    "Source": "Shell Robot",
    "Droprate": "50%",
    "Location": "The Forge",
    "SpriteId": "card"
  },
  {
    "Name": "Skeleton Card",
    "CardId": "Skeleton",
    "Affix": "Sanctified",
    "Slot": "Weapon",
    "Stats": "Holy Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Skeleton",
    "Droprate": "50%",
    "Location": "Festering Woods 1",
    "SpriteId": "card"
  },
  {
    "Name": "Skeleton Giant Card",
    "CardId": "Skeleton Giant",
    "Affix": "Sanctified",
    "Slot": "Accessory",
    "Stats": "Holy Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Skeleton Giant",
    "Droprate": "50%",
    "Location": "Abyss Castle Keep",
    "SpriteId": "card"
  },
  {
    "Name": "Skeleton Mage Card",
    "CardId": "Skeleton Mage",
    "Affix": "Grave",
    "Slot": "Weapon",
    "Stats": "Damage vs Undead Enemies: <color=#AAFF00FF>+10%</color>",
    "Source": "Skeleton Mage",
    "Droprate": "50%",
    "Location": "Abyss Castle Keep",
    "SpriteId": "card"
  },
  {
    "Name": "Snake Card",
    "CardId": "Snake",
    "Affix": "Venomous",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.2 Venom Strike</color>\nChance to autocast Lv.2 Venom Strike when attacking: <color=#AAFF00FF>+10%</color>",
    "Source": "Snake",
    "Droprate": "50%",
    "Location": "Forgotten Depths 2",
    "SpriteId": "card"
  },
  {
    "Name": "Snake Naga Card",
    "CardId": "Snake Naga",
    "Affix": "Twinfang",
    "Slot": "Weapon",
    "Stats": "Multistrike: <color=#AAFF00FF>+50%</color>",
    "Source": "Snake Naga",
    "Droprate": "300%",
    "Location": "Forgotten Depths 1",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Snakelet Card",
    "CardId": "Snakelet",
    "Affix": "Venomous",
    "Slot": "Weapon",
    "Stats": "Venom Strike Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Snakelet",
    "Droprate": "50%",
    "Location": "Forgotten Depths 1",
    "SpriteId": "card"
  },
  {
    "Name": "Snout Robot Card",
    "CardId": "Snout Robot",
    "Affix": "Pillar",
    "Slot": "Weapon",
    "Stats": "Fire Pillar Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Snout Robot",
    "Droprate": "50%",
    "Location": "The Forge",
    "SpriteId": "card"
  },
  {
    "Name": "Snow Bomb Card",
    "CardId": "Snow Bomb",
    "Affix": "Mind",
    "Slot": "Weapon",
    "Stats": "Matk: <color=#AAFF00FF>+4%</color>",
    "Source": "Snow Bomb",
    "Droprate": "50%",
    "Location": "Crystal Cave",
    "SpriteId": "card"
  },
  {
    "Name": "Solar Turtle Card",
    "CardId": "Titan Turtle Sci Green",
    "Affix": "Meteoric",
    "Slot": "Weapon",
    "Stats": "Meteor Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Solar Turtle",
    "Droprate": "50%",
    "Location": "Turtle Nexus",
    "SpriteId": "card"
  },
  {
    "Name": "Soul Card",
    "CardId": "Soul",
    "Affix": "Soul",
    "Slot": "Weapon",
    "Stats": "Soul Strike Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Soul",
    "Droprate": "50%",
    "Location": "Sanctum of Light",
    "SpriteId": "card"
  },
  {
    "Name": "Soul Mage Card",
    "CardId": "Soul Mage",
    "Affix": "Wizardry",
    "Slot": "Accessory",
    "Stats": "Cast Spd: <color=#AAFF00FF>+10%</color>",
    "Source": "Soul Mage",
    "Droprate": "50%",
    "Location": "Sanctum of Light",
    "SpriteId": "card"
  },
  {
    "Name": "Spider Card",
    "CardId": "Spider",
    "Affix": "Shadow",
    "Slot": "Weapon",
    "Stats": "Shadow Step Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Spider",
    "Droprate": "50%",
    "Location": "Forgotten Depths 1",
    "SpriteId": "card"
  },
  {
    "Name": "Spider King Card",
    "CardId": "Spider King",
    "Affix": "Poisonous",
    "Slot": "Weapon",
    "Stats": "<color=#FF9700FF>Enchant weapon with <sprite name=Elements_1> <color=#3BFF51FF>Poison</color> element</color>",
    "Source": "Spider King",
    "Droprate": "50%",
    "Location": "Forgotten Depths 2",
    "SpriteId": "card"
  },
  {
    "Name": "Spider Queen Card",
    "CardId": "Spider Queen Robot",
    "Affix": "Unnatural",
    "Slot": "Weapon",
    "Stats": "Holy Damage: <color=#AAFF00FF>+5%</color>\nShadow Damage: <color=#AAFF00FF>+5%</color>\nPoison Damage: <color=#AAFF00FF>+5%</color>\nUndead Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Spider Queen",
    "Droprate": "300%",
    "Location": "The Forge",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Spider Robot Card",
    "CardId": "Spider Robot",
    "Affix": "Combo",
    "Slot": "Weapon",
    "Stats": "Multistrike: <color=#AAFF00FF>+25%</color>",
    "Source": "Spider Robot",
    "Droprate": "50%",
    "Location": "The Forge",
    "SpriteId": "card"
  },
  {
    "Name": "Spider Toxin Card",
    "CardId": "Spider Toxin",
    "Affix": "Dancing",
    "Slot": "Weapon",
    "Stats": "Blade Dance Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Spider Toxin",
    "Droprate": "50%",
    "Location": "Forgotten Depths 1",
    "SpriteId": "card"
  },
  {
    "Name": "Spiderling Robot Card",
    "CardId": "Spiderling Robot",
    "Affix": "Poisonous",
    "Slot": "Accessory",
    "Stats": "Poison Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Spiderling Robot",
    "Droprate": "50%",
    "Location": "The Forge",
    "SpriteId": "card"
  },
  {
    "Name": "Spike Card",
    "CardId": "Spike",
    "Affix": "Frosty",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.2 Ice Shard</color>",
    "Source": "Spike",
    "Droprate": "50%",
    "Location": "Mystic Lake 2",
    "SpriteId": "card"
  },
  {
    "Name": "Spike Robot Card",
    "CardId": "Spike Robot",
    "Affix": "Rapid",
    "Slot": "Head",
    "Stats": "Atk Spd: <color=#AAFF00FF>+10%</color>",
    "Source": "Spike Robot",
    "Droprate": "50%",
    "Location": "The Forge",
    "SpriteId": "card"
  },
  {
    "Name": "Spook Card",
    "CardId": "Spook",
    "Affix": "Unbreaking",
    "Slot": "Feet",
    "Stats": "<color=#FF9700FF>Cast cannot be interrupted</color>",
    "Source": "Spook",
    "Droprate": "50%",
    "Location": "Sanctum of Light",
    "SpriteId": "card"
  },
  {
    "Name": "Spore Card",
    "CardId": "Spore",
    "Affix": "Vital",
    "Slot": "Weapon",
    "Stats": "Hp: <color=#AAFF00FF>+100</color>\nVit: <color=#AAFF00FF>+1</color>",
    "Source": "Spore",
    "Droprate": "50%",
    "Location": "Windy Desert South",
    "SpriteId": "card"
  },
  {
    "Name": "Sporeling Card",
    "CardId": "Alien Sporella",
    "Affix": "Poisonous",
    "Slot": "Weapon",
    "Stats": "Poison Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Sporeling",
    "Droprate": "50%",
    "Location": "Dark Forest",
    "SpriteId": "card"
  },
  {
    "Name": "Sprout Card",
    "CardId": "Sprout",
    "Affix": "Splintering",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.2 Earthbolt</color>\nChance to autocast Lv.2 Earthbolt when attacking: <color=#AAFF00FF>+10%</color>",
    "Source": "Sprout",
    "Droprate": "50%",
    "Location": "Sunny Meadows 2",
    "SpriteId": "card"
  },
  {
    "Name": "Starflake Card",
    "CardId": "Ice Starflake A",
    "Affix": "Stone",
    "Slot": "Legs",
    "Stats": "Def: <color=#AAFF00FF>+5%</color>\nMdef: <color=#AAFF00FF>+5%</color>",
    "Source": "Starflake",
    "Droprate": "50%",
    "Location": "Starfall Tundra",
    "SpriteId": "card"
  },
  {
    "Name": "Sting Card",
    "CardId": "Sting",
    "Affix": "Frenzy",
    "Slot": "Head",
    "Stats": "Atk Spd Limit: <color=#AAFF00FF>+1</color>",
    "Source": "Sting",
    "Droprate": "300%",
    "Location": "Sunny Meadows 2",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Storm Turtle Card",
    "CardId": "Titan Turtle Sci Pink",
    "Affix": "Tempest",
    "Slot": "Weapon",
    "Stats": "Tempest Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Storm Turtle",
    "Droprate": "50%",
    "Location": "Turtle Nexus",
    "SpriteId": "card"
  },
  {
    "Name": "Stormcoil Card",
    "CardId": "Tentacles Robot",
    "Affix": "Swift",
    "Slot": "Feet",
    "Stats": "Move Spd: <color=#AAFF00FF>+20%</color>\nMp: <color=#FF0073FF>-20%</color>",
    "Source": "Stormcoil",
    "Droprate": "50%",
    "Location": "Night Garden",
    "SpriteId": "card"
  },
  {
    "Name": "Stormjelly Card",
    "CardId": "Jellyfish Robot",
    "Affix": "Wisdom",
    "Slot": "Chest",
    "Stats": "Mp Regen: <color=#AAFF00FF>+50%</color>\nHp Regen: <color=#FF0073FF>-50%</color>",
    "Source": "Stormjelly",
    "Droprate": "50%",
    "Location": "Dark Forest",
    "SpriteId": "card"
  },
  {
    "Name": "Stormstinger Card",
    "CardId": "Stinger Robot",
    "Affix": "Wisdom",
    "Slot": "Feet",
    "Stats": "Mp Regen: <color=#AAFF00FF>+100%</color>\nMp: <color=#FF0073FF>-50%</color>",
    "Source": "Stormstinger",
    "Droprate": "50%",
    "Location": "Dark Forest",
    "SpriteId": "card"
  },
  {
    "Name": "Sun Blossom Card",
    "CardId": "Sun Blossom",
    "Affix": "Enchanted",
    "Slot": "Shield",
    "Stats": "Healing: <color=#AAFF00FF>+15%</color>",
    "Source": "Sun Blossom",
    "Droprate": "50%",
    "Location": "Fairy Glen",
    "SpriteId": "card"
  },
  {
    "Name": "Sunflora Pixie Card",
    "CardId": "Sunflora Pixie",
    "Affix": "Vocal",
    "Slot": "Head",
    "Stats": "Resistance to Silence: <color=#AAFF00FF>+50%</color>",
    "Source": "Sunflora Pixie",
    "Droprate": "300%",
    "Location": "Fairy Glen",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Sunflower Fairy Card",
    "CardId": "Sunflower Fairy",
    "Affix": "Blessed",
    "Slot": "Legs",
    "Stats": "Healing: <color=#AAFF00FF>+15%</color>",
    "Source": "Sunflower Fairy",
    "Droprate": "50%",
    "Location": "Fairy Glen",
    "SpriteId": "card"
  },
  {
    "Name": "Toadstool Card",
    "CardId": "Toadstool",
    "Affix": "Waterproof",
    "Slot": "Shield",
    "Stats": "Water Resistance: <color=#AAFF00FF>+25%</color>",
    "Source": "Toadstool",
    "Droprate": "50%",
    "Location": "Lake Field",
    "SpriteId": "card"
  },
  {
    "Name": "Treant Forest Autumn Card",
    "CardId": "Treant Forest Autumn",
    "Affix": "Autumn",
    "Slot": "Shield",
    "Stats": "Max mp recovered per second: <color=#AAFF00FF>+1%</color>\nHp Regen: <color=#FF0073FF>-50%</color>",
    "Source": "Treant Forest Autumn",
    "Droprate": "50%",
    "Location": "Treant Trail",
    "SpriteId": "card"
  },
  {
    "Name": "Treant Forest Evergreen Card",
    "CardId": "Treant Forest Evergreen",
    "Affix": "Evergreen",
    "Slot": "Shield",
    "Stats": "Hp Regen: <color=#AAFF00FF>+10% per level</color>",
    "Source": "Treant Forest Evergreen",
    "Droprate": "50%",
    "Location": "Treant Trail",
    "SpriteId": "card"
  },
  {
    "Name": "Treant Minion Autumn Card",
    "CardId": "Treant Minion Autumn",
    "Affix": "Autumn",
    "Slot": "Feet",
    "Stats": "Mp: <color=#AAFF00FF>+20</color>\nMp Regen: <color=#AAFF00FF>+25%</color>",
    "Source": "Treant Minion Autumn",
    "Droprate": "50%",
    "Location": "Treant Trail",
    "SpriteId": "card"
  },
  {
    "Name": "Treant Minion Evergreen Card",
    "CardId": "Treant Minion Evergreen",
    "Affix": "Evergreen",
    "Slot": "Legs",
    "Stats": "Hp: <color=#AAFF00FF>+100</color>\nHp Regen: <color=#AAFF00FF>+25%</color>",
    "Source": "Treant Minion Evergreen",
    "Droprate": "50%",
    "Location": "Treant Trail",
    "SpriteId": "card"
  },
  {
    "Name": "Treant Tree Autumn Card",
    "CardId": "Treant Tree Autumn",
    "Affix": "Autumn",
    "Slot": "Chest",
    "Stats": "Mp: <color=#AAFF00FF>+20%</color>",
    "Source": "Treant Tree Autumn",
    "Droprate": "50%",
    "Location": "Treant Trail",
    "SpriteId": "card"
  },
  {
    "Name": "Treant Tree Evergreen Card",
    "CardId": "Treant Tree Evergreen",
    "Affix": "Evergreen",
    "Slot": "Chest",
    "Stats": "Hp: <color=#AAFF00FF>+20%</color>",
    "Source": "Treant Tree Evergreen",
    "Droprate": "50%",
    "Location": "Treant Trail",
    "SpriteId": "card"
  },
  {
    "Name": "Turtle Baby Card",
    "CardId": "Turtle",
    "Affix": "Steadfast",
    "Slot": "Shield",
    "Stats": "Resistance to Stun: <color=#AAFF00FF>+50%</color>",
    "Source": "Turtle Baby",
    "Droprate": "50%",
    "Location": "Stormreef Isle",
    "SpriteId": "card"
  },
  {
    "Name": "Turtle Blue Card",
    "CardId": "Turtle Monster Blue",
    "Affix": "Watchful",
    "Slot": "Head",
    "Stats": "Resistance to Blind: <color=#AAFF00FF>+50%</color>",
    "Source": "Turtle Blue",
    "Droprate": "50%",
    "Location": "Stormreef Isle",
    "SpriteId": "card"
  },
  {
    "Name": "Turtle Champion Card",
    "CardId": "Turtle King",
    "Affix": "Overload",
    "Slot": "Head",
    "Stats": "Elemental Overload Damage: <color=#AAFF00FF>+15% + 2% per level</color>\nElemental Overload Mana Cost: <color=#FF0073FF>+100%</color>",
    "Source": "Turtle Champion",
    "Droprate": "300%",
    "Location": "Turtle Nexus",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Turtle Green Card",
    "CardId": "Turtle Monster Green",
    "Affix": "Purifying",
    "Slot": "Head",
    "Stats": "Resistance to Decay: <color=#AAFF00FF>+50%</color>",
    "Source": "Turtle Green",
    "Droprate": "50%",
    "Location": "Stormreef Isle",
    "SpriteId": "card"
  },
  {
    "Name": "Turtle Red Card",
    "CardId": "Turtle Monster Red",
    "Affix": "Flameguard",
    "Slot": "Head",
    "Stats": "Resistance to Burning: <color=#AAFF00FF>+50%</color>",
    "Source": "Turtle Red",
    "Droprate": "50%",
    "Location": "Stormreef Isle",
    "SpriteId": "card"
  },
  {
    "Name": "Twinkle Card",
    "CardId": "Alien Twinkle",
    "Affix": "Energy",
    "Slot": "Accessory",
    "Stats": "Mp Regen: <color=#AAFF00FF>+25%</color>",
    "Source": "Twinkle",
    "Droprate": "50%",
    "Location": "Starfall Tundra",
    "SpriteId": "card"
  },
  {
    "Name": "Vampire Bat Card",
    "CardId": "Vampire Bat",
    "Affix": "Leeching",
    "Slot": "Accessory",
    "Stats": "Siphon Hp: <color=#AAFF00FF>+10</color>",
    "Source": "Vampire Bat",
    "Droprate": "50%",
    "Location": "Forgotten Depths 2",
    "SpriteId": "card"
  },
  {
    "Name": "Vanilla Ice Card",
    "CardId": "Ice Starflake B",
    "Affix": "Energy",
    "Slot": "Legs",
    "Stats": "Mp Regen: <color=#AAFF00FF>+25%</color>\nMp Cost: <color=#AAFF00FF>-10%</color>",
    "Source": "Vanilla Ice",
    "Droprate": "50%",
    "Location": "Starfall Tundra",
    "SpriteId": "card"
  },
  {
    "Name": "Voidgazer Card",
    "CardId": "Alien One Eye",
    "Affix": "Mystery",
    "Slot": "Head",
    "Stats": "<color=#FF9700FF>Cast cannot be interrupted</color>",
    "Source": "Voidgazer",
    "Droprate": "50%",
    "Location": "Night Garden",
    "SpriteId": "card"
  },
  {
    "Name": "Voidspawn Card",
    "CardId": "Alien Cyclops",
    "Affix": "Gaze",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.1 True Sight</color>",
    "Source": "Voidspawn",
    "Droprate": "50%",
    "Location": "Dark Forest",
    "SpriteId": "card"
  },
  {
    "Name": "Werewolf Card",
    "CardId": "Werewolf",
    "Affix": "Tainted",
    "Slot": "Chest",
    "Stats": "<color=#FF9700FF>Convert to <sprite name=Elements_3> <color=#755E94FF>Shadow</color> element\n<color=#FF9700FF>Reveals Invisible Units</color></color>",
    "Source": "Werewolf",
    "Droprate": "300%",
    "Location": "Festering Woods 2",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Whirlwind Card",
    "CardId": "Whirlwind",
    "Affix": "Grounding",
    "Slot": "Weapon",
    "Stats": "Damage vs Wind Enemies: <color=#AAFF00FF>+10%</color>",
    "Source": "Whirlwind",
    "Droprate": "50%",
    "Location": "Windy Desert",
    "SpriteId": "card"
  },
  {
    "Name": "Wind Card",
    "CardId": "Wind",
    "Affix": "Storm",
    "Slot": "Weapon",
    "Stats": "Thunder Storm Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Wind",
    "Droprate": "50%",
    "Location": "Windy Desert",
    "SpriteId": "card"
  },
  {
    "Name": "Wind Mage Card",
    "CardId": "Wind Mage",
    "Affix": "Gale",
    "Slot": "Weapon",
    "Stats": "<color=#FF9700FF>Enchant weapon with <sprite name=Elements_7> <color=#FFC701FF>Wind</color> element</color>",
    "Source": "Wind Mage",
    "Droprate": "50%",
    "Location": "Windy Desert",
    "SpriteId": "card"
  },
  {
    "Name": "Wisp Blue Card",
    "CardId": "Wisp Blue",
    "Affix": "Icy",
    "Slot": "Weapon",
    "Stats": "Icebolt Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Wisp Blue",
    "Droprate": "50%",
    "Location": "Forest Field 1",
    "SpriteId": "card"
  },
  {
    "Name": "Wisp Purple Card",
    "CardId": "Wisp Purple",
    "Affix": "Shocking",
    "Slot": "Weapon",
    "Stats": "Thunderbolt Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Wisp Purple",
    "Droprate": "50%",
    "Location": "Forest Field 1",
    "SpriteId": "card"
  },
  {
    "Name": "Wisp Red Card",
    "CardId": "Wisp Red",
    "Affix": "Flaming",
    "Slot": "Weapon",
    "Stats": "Firebolt Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Wisp Red",
    "Droprate": "50%",
    "Location": "Forest Field 1",
    "SpriteId": "card"
  },
  {
    "Name": "Wisp Yellow Card",
    "CardId": "Wisp Yellow",
    "Affix": "Splintering",
    "Slot": "Weapon",
    "Stats": "Earthbolt Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Wisp Yellow",
    "Droprate": "50%",
    "Location": "Forest Field 1",
    "SpriteId": "card"
  },
  {
    "Name": "Wolf Card",
    "CardId": "Wolf",
    "Affix": "Umbral",
    "Slot": "Accessory",
    "Stats": "Shadow Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Wolf",
    "Droprate": "50%",
    "Location": "Festering Woods 2",
    "SpriteId": "card"
  },
  {
    "Name": "Wolf Pup Card",
    "CardId": "Wolf Pup",
    "Affix": "Umbral",
    "Slot": "Weapon",
    "Stats": "Shadow Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Wolf Pup",
    "Droprate": "50%",
    "Location": "Festering Woods 2",
    "SpriteId": "card"
  },
  {
    "Name": "Worm Card",
    "CardId": "Worm",
    "Affix": "Toxinproof",
    "Slot": "Shield",
    "Stats": "Poison Resistance: <color=#AAFF00FF>+25%</color>",
    "Source": "Worm",
    "Droprate": "50%",
    "Location": "Swamp Wilderness",
    "SpriteId": "card"
  },
  {
    "Name": "Worm Creep Card",
    "CardId": "Worm Creep",
    "Affix": "Poisonous",
    "Slot": "Chest",
    "Stats": "<color=#FF9700FF>Convert to <sprite name=Elements_1> <color=#3BFF51FF>Poison</color> element</color>",
    "Source": "Worm Creep",
    "Droprate": "300%",
    "Location": "Underground Cavern",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Worm Rot Card",
    "CardId": "Worm Rot",
    "Affix": "Toxinproof",
    "Slot": "Legs",
    "Stats": "Poison Resistance: <color=#AAFF00FF>+15%</color>",
    "Source": "Worm Rot",
    "Droprate": "50%",
    "Location": "Underground Cavern",
    "SpriteId": "card"
  },
  {
    "Name": "Worm Stink Card",
    "CardId": "Worm Stink",
    "Affix": "Purging",
    "Slot": "Weapon",
    "Stats": "Damage vs Poison Enemies: <color=#AAFF00FF>+10%</color>",
    "Source": "Worm Stink",
    "Droprate": "50%",
    "Location": "Underground Cavern",
    "SpriteId": "card"
  },
  {
    "Name": "Wraith Card",
    "CardId": "Wraith",
    "Affix": "Frenzied",
    "Slot": "Head",
    "Stats": "Atk Spd Limit: <color=#AAFF00FF>+2</color>\nHp: <color=#FF0073FF>-25%</color>\nMp: <color=#FF0073FF>-25%</color>",
    "Source": "Wraith",
    "Droprate": "300%",
    "Location": "Abyss Castle Crypt",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Zombie Goblin Giant Card",
    "CardId": "Zombie Goblin Giant",
    "Affix": "Undead",
    "Slot": "Weapon",
    "Stats": "<color=#FF9700FF>Enchant weapon with <sprite name=Undead> <color=#C85AE0FF>Undead</color> element</color>",
    "Source": "Zombie Goblin Giant",
    "Droprate": "50%",
    "Location": "Goblin Cave 2",
    "SpriteId": "card"
  },
  {
    "Name": "Zombie Goblin Lord Card",
    "CardId": "Zombie Goblin King",
    "Affix": "Undead",
    "Slot": "Chest",
    "Stats": "<color=#FF9700FF>Convert to <sprite name=Undead> <color=#C85AE0FF>Undead</color> element\n<color=#FF0073FF>Healing effects converted to damage</color>\n<color=#FF9700FF>Immune to Slow</color>\n<color=#FF9700FF>Immune to Curse</color>\n<color=#FF9700FF>Immune to Frozen</color>\n<color=#FF9700FF>Immune to Bleeding</color></color>",
    "Source": "Zombie Goblin Lord",
    "Droprate": "300%",
    "Location": "Goblin Cave 2",
    "SpriteId": "card_gold"
  },
  {
    "Name": "Zombie Goblin Minion Card",
    "CardId": "Zombie Goblin Minion",
    "Affix": "Purity",
    "Slot": "Legs",
    "Stats": "Undead Resistance: <color=#AAFF00FF>+15%</color>",
    "Source": "Zombie Goblin Minion",
    "Droprate": "50%",
    "Location": "Goblin Cave 1",
    "SpriteId": "card"
  },
  {
    "Name": "Zombie Goblin Soldier Card",
    "CardId": "Zombie Goblin Soldier",
    "Affix": "Undying",
    "Slot": "Shield",
    "Stats": "Hp: <color=#AAFF00FF>+25%</color>\nHealing Received: <color=#FF0073FF>-50%</color>",
    "Source": "Zombie Goblin Soldier",
    "Droprate": "50%",
    "Location": "Goblin Cave 1",
    "SpriteId": "card"
  }
];
