window.cardData = [
  {
    "Name": "Abomination Card",
    "CardId": "Abomination",
    "Affix": "Power",
    "Slot": "Chest",
    "Stats": "Atk: <color=#AAFF00FF>+1 per level</color>\nDEF: <color=#FF0073FF>-1% per level</color>",
    "Source": "Abomination",
    "Droprate": "50%",
    "Location": "Goblin Cave 2",
    "SpriteId": "card",
    "SourceLevel": 60
  },
  {
    "Name": "Abyss Archon Card",
    "CardId": "Death Mage",
    "Affix": "Cloaking",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.1 Cloaking</color>",
    "Source": "Abyss Archon",
    "Droprate": "300%",
    "Location": "Abyss Castle Library",
    "SpriteId": "card_gold",
    "SourceLevel": 130
  },
  {
    "Name": "Adder Card",
    "CardId": "Snakelet",
    "Affix": "Combo",
    "Slot": "Weapon",
    "Stats": "Multistrike: <color=#AAFF00FF>+20%</color>",
    "Source": "Adder",
    "Droprate": "50%",
    "Location": "Forgotten Depths 1",
    "SpriteId": "card",
    "SourceLevel": 43
  },
  {
    "Name": "Albino Rat Card",
    "CardId": "Rat White",
    "Affix": "Accurate",
    "Slot": "Accessory",
    "Stats": "Hit: <color=#AAFF00FF>+10</color>\nDex: <color=#AAFF00FF>+1</color>",
    "Source": "Albino Rat",
    "Droprate": "50%",
    "Location": "Nevaris Sewers",
    "SpriteId": "card",
    "SourceLevel": 20
  },
  {
    "Name": "Amber Octopus Card",
    "CardId": "Octopus King Orange",
    "Affix": "Long-Range",
    "Slot": "Weapon",
    "Stats": "Range: <color=#AAFF00FF>+1</color>\nAttack Speed: <color=#FF0073FF>-20%</color>",
    "Source": "Amber Octopus",
    "Droprate": "50%",
    "Location": "Turtle Nexus",
    "SpriteId": "card",
    "SourceLevel": 133
  },
  {
    "Name": "Amber Squid Card",
    "CardId": "Octopus Baby Orange",
    "Affix": "Elusive",
    "Slot": "Accessory",
    "Stats": "Total FLEE: <color=#AAFF00FF>+5%</color>",
    "Source": "Amber Squid",
    "Droprate": "50%",
    "Location": "Sunken Depths",
    "SpriteId": "card",
    "SourceLevel": 102
  },
  {
    "Name": "Angel Card",
    "CardId": "Angel",
    "Affix": "Sanctified",
    "Slot": "Weapon",
    "Stats": "Holy Damage: <color=#AAFF00FF>+6%</color>",
    "Source": "Angel",
    "Droprate": "50%",
    "Location": "Sanctum of Light",
    "SpriteId": "card",
    "SourceLevel": 76
  },
  {
    "Name": "Apparition Card",
    "CardId": "Nightmare",
    "Affix": "Ethereal",
    "Slot": "Accessory",
    "Stats": "Ghost Damage: <color=#AAFF00FF>+6%</color>",
    "Source": "Apparition",
    "Droprate": "50%",
    "Location": "Abyss Castle Library",
    "SpriteId": "card",
    "SourceLevel": 122
  },
  {
    "Name": "Aqua Drake Card",
    "CardId": "Dragon Water",
    "Affix": "Waterproof",
    "Slot": "Legs",
    "Stats": "Water Resistance: <color=#AAFF00FF>+15%</color>",
    "Source": "Aqua Drake",
    "Droprate": "50%",
    "Location": "Crystal Cave",
    "SpriteId": "card",
    "SourceLevel": 72
  },
  {
    "Name": "Aqua Merling Card",
    "CardId": "Fish Man Blue",
    "Affix": "Mind",
    "Slot": "Legs",
    "Stats": "Matk: <color=#AAFF00FF>+10</color>",
    "Source": "Aqua Merling",
    "Droprate": "50%",
    "Location": "Sunken Depths",
    "SpriteId": "card",
    "SourceLevel": 103
  },
  {
    "Name": "Arachne Card",
    "CardId": "Spider King",
    "Affix": "Sharp",
    "Slot": "Feet",
    "Stats": "Atk: <color=#AAFF00FF>+5</color>",
    "Source": "Arachne",
    "Droprate": "50%",
    "Location": "Forgotten Depths 2",
    "SpriteId": "card",
    "SourceLevel": 49
  },
  {
    "Name": "Archangel Card",
    "CardId": "Archangel",
    "Affix": "Lightproof",
    "Slot": "Shield",
    "Stats": "Holy Resistance: <color=#AAFF00FF>+25%</color>",
    "Source": "Archangel",
    "Droprate": "50%",
    "Location": "Sanctum of Light",
    "SpriteId": "card",
    "SourceLevel": 79
  },
  {
    "Name": "Azure Beholder Card",
    "CardId": "Eyeball Mage Blue",
    "Affix": "Mind",
    "Slot": "Chest",
    "Stats": "Matk: <color=#AAFF00FF>+1 per level</color>\nMDEF: <color=#FF0073FF>-1% per level</color>",
    "Source": "Azure Beholder",
    "Droprate": "50%",
    "Location": "Abyss Castle Library",
    "SpriteId": "card",
    "SourceLevel": 123
  },
  {
    "Name": "Azure Eyestalk Card",
    "CardId": "Eyeball Creep Blue",
    "Affix": "Focus",
    "Slot": "Head",
    "Stats": "MP: <color=#AAFF00FF>+10%</color>",
    "Source": "Azure Eyestalk",
    "Droprate": "50%",
    "Location": "Abyss Castle Crypt",
    "SpriteId": "card",
    "SourceLevel": 117
  },
  {
    "Name": "Azure Gazer Card",
    "CardId": "Eyeball Bat Blue",
    "Affix": "Radiant",
    "Slot": "Weapon",
    "Stats": "<color=#FF9700FF>Holy Light: <color=#AAFF00FF>Remove Knockback</color></color>",
    "Source": "Azure Gazer",
    "Droprate": "50%",
    "Location": "Festering Woods 1",
    "SpriteId": "card",
    "SourceLevel": 21
  },
  {
    "Name": "Azure Octopus Card",
    "CardId": "Octopus King Blue",
    "Affix": "Ranged",
    "Slot": "Weapon",
    "Stats": "Ranged Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Azure Octopus",
    "Droprate": "50%",
    "Location": "Turtle Nexus",
    "SpriteId": "card",
    "SourceLevel": 132
  },
  {
    "Name": "Azure Squid Card",
    "CardId": "Octopus Baby Blue",
    "Affix": "Elusive",
    "Slot": "Head",
    "Stats": "Total FLEE: <color=#AAFF00FF>+5%</color>",
    "Source": "Azure Squid",
    "Droprate": "50%",
    "Location": "Sunken Depths",
    "SpriteId": "card",
    "SourceLevel": 102
  },
  {
    "Name": "Azure Terrapin Card",
    "CardId": "Turtle Monster Blue",
    "Affix": "Watchful",
    "Slot": "Head",
    "Stats": "Resistance to Blind: <color=#AAFF00FF>+50%</color>",
    "Source": "Azure Terrapin",
    "Droprate": "50%",
    "Location": "Stormreef Isle",
    "SpriteId": "card",
    "SourceLevel": 63
  },
  {
    "Name": "Banshee Card",
    "CardId": "Haunt",
    "Affix": "Cloaking",
    "Slot": "Head",
    "Stats": "Perfect Cloaking: <color=#FF9700FF>undetectable by shadow monsters when invisible</color>",
    "Source": "Banshee",
    "Droprate": "50%",
    "Location": "Sanctum of Light",
    "SpriteId": "card",
    "SourceLevel": 80
  },
  {
    "Name": "Barrel Mimic Card",
    "CardId": "Mimic Barrel",
    "Affix": "Vit",
    "Slot": "Accessory",
    "Stats": "Vit: <color=#AAFF00FF>+3</color>",
    "Source": "Barrel Mimic",
    "Droprate": "50%",
    "Location": "Abyss Castle Dungeon",
    "SpriteId": "card",
    "SourceLevel": 107
  },
  {
    "Name": "Bat Card",
    "CardId": "Bat",
    "Affix": "Leeching",
    "Slot": "Accessory",
    "Stats": "Mana on Kill: <color=#AAFF00FF>+10</color>",
    "Source": "Bat",
    "Droprate": "50%",
    "Location": "Forgotten Depths 1",
    "SpriteId": "card",
    "SourceLevel": 41
  },
  {
    "Name": "Bee Card",
    "CardId": "Bee",
    "Affix": "Energy",
    "Slot": "Weapon",
    "Stats": "MP Regen: <color=#AAFF00FF>+25%</color>",
    "Source": "Bee",
    "Droprate": "50%",
    "Location": "Sunny Meadows 2",
    "SpriteId": "card",
    "SourceLevel": 6
  },
  {
    "Name": "Blaze Card",
    "CardId": "Flame",
    "Affix": "Burning",
    "Slot": "Accessory",
    "Stats": "Status Duration: <color=#AAFF00FF>+15%</color>",
    "Source": "Blaze",
    "Droprate": "50%",
    "Location": "Demon's Maw",
    "SpriteId": "card",
    "SourceLevel": 97
  },
  {
    "Name": "Bloodsucker Card",
    "CardId": "Mosquito Stinger",
    "Affix": "Haste",
    "Slot": "Accessory",
    "Stats": "Grants <color=#AAFF00FF>Lv.5 Haste</color>",
    "Source": "Bloodsucker",
    "Droprate": "50%",
    "Location": "Swamp Wilderness",
    "SpriteId": "card",
    "SourceLevel": 69
  },
  {
    "Name": "Blowfly Card",
    "CardId": "Housefly Nom",
    "Affix": "Assassin's",
    "Slot": "Weapon",
    "Stats": "Crit: <color=#AAFF00FF>+10</color>",
    "Source": "Blowfly",
    "Droprate": "50%",
    "Location": "Swamp",
    "SpriteId": "card",
    "SourceLevel": 39
  },
  {
    "Name": "Bluebottle Card",
    "CardId": "Housefly Junk",
    "Affix": "Rapid",
    "Slot": "Accessory",
    "Stats": "Attack Speed: <color=#AAFF00FF>+5%</color>",
    "Source": "Bluebottle",
    "Droprate": "50%",
    "Location": "Swamp Wilderness",
    "SpriteId": "card",
    "SourceLevel": 69
  },
  {
    "Name": "Bluefin Card",
    "CardId": "FIsh Blue",
    "Affix": "Fading",
    "Slot": "Legs",
    "Stats": "Threat Generation: <color=#FF0073FF>-25%</color>",
    "Source": "Bluefin",
    "Droprate": "50%",
    "Location": "Sunken Depths",
    "SpriteId": "card",
    "SourceLevel": 101
  },
  {
    "Name": "Bomb Card",
    "CardId": "Bomb",
    "Affix": "Volatile",
    "Slot": "Accessory",
    "Stats": "Attack Speed: <color=#AAFF00FF>+25%</color>\n<color=#FF0073FF>Cannot attack.</color>",
    "Source": "Bomb",
    "Droprate": "50%",
    "Location": "Sanctum of Light",
    "SpriteId": "card",
    "SourceLevel": 81
  },
  {
    "Name": "Book Mimic Card",
    "CardId": "Mimic Book",
    "Affix": "Int",
    "Slot": "Accessory",
    "Stats": "Int: <color=#AAFF00FF>+3</color>",
    "Source": "Book Mimic",
    "Droprate": "50%",
    "Location": "Abyss Castle Library",
    "SpriteId": "card",
    "SourceLevel": 121
  },
  {
    "Name": "Boxy Robot Card",
    "CardId": "Boxy Robot",
    "Affix": "Immune",
    "Slot": "Shield",
    "Stats": "Neutral Resistance: <color=#AAFF00FF>+20%</color>",
    "Source": "Boxy Robot",
    "Droprate": "50%",
    "Location": "The Forge",
    "SpriteId": "card",
    "SourceLevel": 130
  },
  {
    "Name": "Breeze Card",
    "CardId": "Whirlwind",
    "Affix": "Grounding",
    "Slot": "Weapon",
    "Stats": "Damage versus Wind Enemies: <color=#AAFF00FF>+10%</color>",
    "Source": "Breeze",
    "Droprate": "50%",
    "Location": "Windy Desert",
    "SpriteId": "card",
    "SourceLevel": 26
  },
  {
    "Name": "Broodmother Card",
    "CardId": "Queen Worm",
    "Affix": "Toxic",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.1 Venom Coating</color>\nChance to autocast Lv.2 Venom Strike when attacking: <color=#AAFF00FF>+1% per level</color>",
    "Source": "Broodmother",
    "Droprate": "300%",
    "Location": "Swamp Wilderness",
    "SpriteId": "card_gold",
    "SourceLevel": 75
  },
  {
    "Name": "Bull Shark Card",
    "CardId": "Shark",
    "Affix": "Taunting",
    "Slot": "Legs",
    "Stats": "Threat Generation: <color=#AAFF00FF>+10% per level</color>",
    "Source": "Bull Shark",
    "Droprate": "50%",
    "Location": "Sunken Depths",
    "SpriteId": "card",
    "SourceLevel": 104
  },
  {
    "Name": "Bumblebee Card",
    "CardId": "Bumble",
    "Affix": "Energy",
    "Slot": "Accessory",
    "Stats": "MP Regen: <color=#AAFF00FF>+25%</color>",
    "Source": "Bumblebee",
    "Droprate": "50%",
    "Location": "Sunny Meadows 2",
    "SpriteId": "card",
    "SourceLevel": 7
  },
  {
    "Name": "Bunny Card",
    "CardId": "Bunny",
    "Affix": "Basic",
    "Slot": "Weapon",
    "Stats": "Neutral Damage: <color=#AAFF00FF>+6%</color>",
    "Source": "Bunny",
    "Droprate": "50%",
    "Location": "Bunny Woods",
    "SpriteId": "card",
    "SourceLevel": 21
  },
  {
    "Name": "Cacti Card",
    "CardId": "Cacti",
    "Affix": "Spiked",
    "Slot": "Shield",
    "Stats": "Reflect Damage: <color=#AAFF00FF>+2% per level</color>",
    "Source": "Cacti",
    "Droprate": "50%",
    "Location": "Windy Desert South",
    "SpriteId": "card",
    "SourceLevel": 31
  },
  {
    "Name": "Cactus Card",
    "CardId": "Cactus",
    "Affix": "Spiked",
    "Slot": "Weapon",
    "Stats": "Reflect Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Cactus",
    "Droprate": "50%",
    "Location": "Windy Desert South",
    "SpriteId": "card",
    "SourceLevel": 33
  },
  {
    "Name": "Cactus King Card",
    "CardId": "Cactus Boss",
    "Affix": "Enduring",
    "Slot": "Feet",
    "Stats": "Grants <color=#AAFF00FF>Lv.5 Endure</color>\nHP: <color=#AAFF00FF>+10%</color>",
    "Source": "Cactus King",
    "Droprate": "300%",
    "Location": "Windy Desert South",
    "SpriteId": "card_gold",
    "SourceLevel": 40
  },
  {
    "Name": "Canary Merling Card",
    "CardId": "Fish Man Yellow",
    "Affix": "Precision",
    "Slot": "Legs",
    "Stats": "Crit: <color=#AAFF00FF>+5</color>\nCRIT Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Canary Merling",
    "Droprate": "50%",
    "Location": "Sunken Depths",
    "SpriteId": "card",
    "SourceLevel": 103
  },
  {
    "Name": "Candle Mimic Card",
    "CardId": "Mimic Candle",
    "Affix": "Dex",
    "Slot": "Accessory",
    "Stats": "Dex: <color=#AAFF00FF>+3</color>",
    "Source": "Candle Mimic",
    "Droprate": "50%",
    "Location": "Abyss Castle Dungeon",
    "SpriteId": "card",
    "SourceLevel": 109
  },
  {
    "Name": "Celestial Moth Card",
    "CardId": "Moth Celestial",
    "Affix": "Wizardry",
    "Slot": "Chest",
    "Stats": "Cast Speed: <color=#AAFF00FF>+15%</color>",
    "Source": "Celestial Moth",
    "Droprate": "50%",
    "Location": "Fairy Glen",
    "SpriteId": "card",
    "SourceLevel": 35
  },
  {
    "Name": "Chest Mimic Card",
    "CardId": "Mimic Treasure Chest",
    "Affix": "Luk",
    "Slot": "Accessory",
    "Stats": "Luk: <color=#AAFF00FF>+3</color>",
    "Source": "Chest Mimic",
    "Droprate": "50%",
    "Location": "Abyss Castle Dungeon",
    "SpriteId": "card",
    "SourceLevel": 110
  },
  {
    "Name": "Chick Card",
    "CardId": "Chick",
    "Affix": "Sharp",
    "Slot": "Weapon",
    "Stats": "Atk: <color=#AAFF00FF>+5</color>",
    "Source": "Chick",
    "Droprate": "50%",
    "Location": "Sunny Meadows 1",
    "SpriteId": "card",
    "SourceLevel": 2
  },
  {
    "Name": "Chompbloom Card",
    "CardId": "Alien Plant",
    "Affix": "Resistance",
    "Slot": "Shield",
    "Stats": "Resistance to Slow: <color=#AAFF00FF>+50%</color>\nResistance to Bleeding: <color=#AAFF00FF>+50%</color>",
    "Source": "Chompbloom",
    "Droprate": "50%",
    "Location": "Night Garden",
    "SpriteId": "card",
    "SourceLevel": 129
  },
  {
    "Name": "Chomproot Card",
    "CardId": "Alien Biteroot",
    "Affix": "Resistance",
    "Slot": "Feet",
    "Stats": "Resistance to Bleeding: <color=#AAFF00FF>+50%</color>",
    "Source": "Chomproot",
    "Droprate": "50%",
    "Location": "Dark Forest",
    "SpriteId": "card",
    "SourceLevel": 94
  },
  {
    "Name": "Cindermaw Card",
    "CardId": "Alien Wreck",
    "Affix": "Titan",
    "Slot": "Chest",
    "Stats": "<color=#FF9700FF>Immune to knockback.</color>",
    "Source": "Cindermaw",
    "Droprate": "50%",
    "Location": "Night Garden",
    "SpriteId": "card",
    "SourceLevel": 130
  },
  {
    "Name": "Cinderspike Card",
    "CardId": "Alien Spike",
    "Affix": "Spiked",
    "Slot": "Accessory",
    "Stats": "Reflect Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Cinderspike",
    "Droprate": "50%",
    "Location": "Dark Forest",
    "SpriteId": "card",
    "SourceLevel": 92
  },
  {
    "Name": "Cinderwheel Card",
    "CardId": "Alien Wheel",
    "Affix": "Steadfast",
    "Slot": "Head",
    "Stats": "Resistance to Stun: <color=#AAFF00FF>+50%</color>\nMP: <color=#FF0073FF>-25%</color>",
    "Source": "Cinderwheel",
    "Droprate": "50%",
    "Location": "Dark Forest",
    "SpriteId": "card",
    "SourceLevel": 95
  },
  {
    "Name": "Conch Card",
    "CardId": "Shell",
    "Affix": "Immune",
    "Slot": "Legs",
    "Stats": "Neutral Resistance: <color=#AAFF00FF>+10%</color>",
    "Source": "Conch",
    "Droprate": "50%",
    "Location": "Mystic Lake 2",
    "SpriteId": "card",
    "SourceLevel": 36
  },
  {
    "Name": "Coral Merman Card",
    "CardId": "Fish Merman Pink",
    "Affix": "Savage",
    "Slot": "Legs",
    "Stats": "CRIT Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Coral Merman",
    "Droprate": "50%",
    "Location": "Sunken Depths",
    "SpriteId": "card",
    "SourceLevel": 105
  },
  {
    "Name": "Cosmic Entity Card",
    "CardId": "Alien Big Blink",
    "Affix": "Cosmic",
    "Slot": "Head",
    "Stats": "MATK: <color=#AAFF00FF>+10%</color>\nATK: <color=#AAFF00FF>+10%</color>\nHP: <color=#FF0073FF>-25%</color>\nMP: <color=#FF0073FF>-25%</color>",
    "Source": "Cosmic Entity",
    "Droprate": "300%",
    "Location": "Night Garden",
    "SpriteId": "card_gold",
    "SourceLevel": 135
  },
  {
    "Name": "Crawler Card",
    "CardId": "Creeper",
    "Affix": "Savage",
    "Slot": "Weapon",
    "Stats": "CRIT Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Crawler",
    "Droprate": "50%",
    "Location": "Forgotten Depths 1",
    "SpriteId": "card",
    "SourceLevel": 45
  },
  {
    "Name": "Crimson Terrapin Card",
    "CardId": "Turtle Monster Red",
    "Affix": "Flameguard",
    "Slot": "Head",
    "Stats": "Resistance to Burning: <color=#AAFF00FF>+50%</color>",
    "Source": "Crimson Terrapin",
    "Droprate": "50%",
    "Location": "Stormreef Isle",
    "SpriteId": "card",
    "SourceLevel": 64
  },
  {
    "Name": "Cyclopling Card",
    "CardId": "Cyclops Minion",
    "Affix": "Warding",
    "Slot": "Chest",
    "Stats": "MDEF: <color=#AAFF00FF>+15%</color>",
    "Source": "Cyclopling",
    "Droprate": "50%",
    "Location": "Crystal Cave",
    "SpriteId": "card",
    "SourceLevel": 72
  },
  {
    "Name": "Cyclops Card",
    "CardId": "Cyclops",
    "Affix": "Warding",
    "Slot": "Head",
    "Stats": "MDEF: <color=#AAFF00FF>+10%</color>",
    "Source": "Cyclops",
    "Droprate": "50%",
    "Location": "Crystal Cave",
    "SpriteId": "card",
    "SourceLevel": 73
  },
  {
    "Name": "Cyclops Titan Card",
    "CardId": "Cyclops Giant",
    "Affix": "Warding",
    "Slot": "Shield",
    "Stats": "MDEF: <color=#AAFF00FF>+3% per level</color>",
    "Source": "Cyclops Titan",
    "Droprate": "50%",
    "Location": "Crystal Cave",
    "SpriteId": "card",
    "SourceLevel": 75
  },
  {
    "Name": "Darter Card",
    "CardId": "Dragonfly Arrow",
    "Affix": "Elusive",
    "Slot": "Feet",
    "Stats": "Flee: <color=#AAFF00FF>+10</color>\nAgi: <color=#AAFF00FF>+1</color>",
    "Source": "Darter",
    "Droprate": "50%",
    "Location": "Swamp",
    "SpriteId": "card",
    "SourceLevel": 36
  },
  {
    "Name": "Deathblossom Card",
    "CardId": "Blossom",
    "Affix": "Status",
    "Slot": "Head",
    "Stats": "Status Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Deathblossom",
    "Droprate": "50%",
    "Location": "Underground Cavern",
    "SpriteId": "card",
    "SourceLevel": 90
  },
  {
    "Name": "Delivery Robot Card",
    "CardId": "Delivery Robot",
    "Affix": "Carrier",
    "Slot": "Head",
    "Stats": "Weight Limit: <color=#AAFF00FF>+100 per level</color>",
    "Source": "Delivery Robot",
    "Droprate": "50%",
    "Location": "The Forge",
    "SpriteId": "card",
    "SourceLevel": 129
  },
  {
    "Name": "Demon Lord Card",
    "CardId": "Imp Devil",
    "Affix": "Meteoric",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.5 Meteor</color>",
    "Source": "Demon Lord",
    "Droprate": "300%",
    "Location": "Demon's Maw",
    "SpriteId": "card_gold",
    "SourceLevel": 105
  },
  {
    "Name": "Devourer Card",
    "CardId": "Worm Creep",
    "Affix": "Poisonous",
    "Slot": "Chest",
    "Stats": "<color=#FF9700FF>Convert to <sprite name=poison> <color=#3BFF51FF>Poison</color> element</color>",
    "Source": "Devourer",
    "Droprate": "300%",
    "Location": "Underground Cavern",
    "SpriteId": "card_gold",
    "SourceLevel": 95
  },
  {
    "Name": "Digger Card",
    "CardId": "Burrow",
    "Affix": "Stomping",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.1 Stomp</color>",
    "Source": "Digger",
    "Droprate": "50%",
    "Location": "Forest Field 2",
    "SpriteId": "card",
    "SourceLevel": 17
  },
  {
    "Name": "Dire Mole Card",
    "CardId": "Mole Rat King",
    "Affix": "Mudproof",
    "Slot": "Shield",
    "Stats": "Earth Resistance: <color=#AAFF00FF>+25%</color>",
    "Source": "Dire Mole",
    "Droprate": "50%",
    "Location": "Windy Desert North",
    "SpriteId": "card",
    "SourceLevel": 35
  },
  {
    "Name": "Direwolf Card",
    "CardId": "Direwolf",
    "Affix": "Assassin's",
    "Slot": "Head",
    "Stats": "Total CRIT Rate: <color=#AAFF00FF>+15%</color>",
    "Source": "Direwolf",
    "Droprate": "50%",
    "Location": "Abyss Castle Crypt",
    "SpriteId": "card",
    "SourceLevel": 120
  },
  {
    "Name": "Dusk Drake Card",
    "CardId": "Dragon Dusk",
    "Affix": "Purifying",
    "Slot": "Head",
    "Stats": "Resistance to Curse: <color=#AAFF00FF>+50%</color>",
    "Source": "Dusk Drake",
    "Droprate": "50%",
    "Location": "Sanctum of Light",
    "SpriteId": "card",
    "SourceLevel": 77
  },
  {
    "Name": "Earth Wisp Card",
    "CardId": "Wisp Yellow",
    "Affix": "Seismic",
    "Slot": "Weapon",
    "Stats": "Earth Damage: <color=#AAFF00FF>+6%</color>",
    "Source": "Earth Wisp",
    "Droprate": "50%",
    "Location": "Forest Field 1",
    "SpriteId": "card",
    "SourceLevel": 15
  },
  {
    "Name": "Egg Card",
    "CardId": "Egg",
    "Affix": "Vital",
    "Slot": "Head",
    "Stats": "HP: <color=#AAFF00FF>+100</color>",
    "Source": "Egg",
    "Droprate": "50%",
    "Location": "Sunny Meadows 1",
    "SpriteId": "card",
    "SourceLevel": 4
  },
  {
    "Name": "Egglet Card",
    "CardId": "Egglet",
    "Affix": "Rapid",
    "Slot": "Weapon",
    "Stats": "Attack Speed: <color=#AAFF00FF>+10%</color>\nAgi: <color=#AAFF00FF>+1</color>",
    "Source": "Egglet",
    "Droprate": "50%",
    "Location": "Bunny Woods",
    "SpriteId": "card",
    "SourceLevel": 23
  },
  {
    "Name": "Elder Fire Card",
    "CardId": "Elder Wisp Yellow",
    "Affix": "Pyre",
    "Slot": "Accessory",
    "Stats": "Fire Damage: <color=#AAFF00FF>+6%</color>",
    "Source": "Elder Fire",
    "Droprate": "50%",
    "Location": "Demon's Maw",
    "SpriteId": "card",
    "SourceLevel": 99
  },
  {
    "Name": "Elder Frost Card",
    "CardId": "Elder Wisp Blue",
    "Affix": "Glacial",
    "Slot": "Accessory",
    "Stats": "Water Damage: <color=#AAFF00FF>+6%</color>",
    "Source": "Elder Frost",
    "Droprate": "50%",
    "Location": "Crystal Cave",
    "SpriteId": "card",
    "SourceLevel": 74
  },
  {
    "Name": "Elder Lightning Card",
    "CardId": "Elder Wisp Purple",
    "Affix": "Spark",
    "Slot": "Accessory",
    "Stats": "Wind Damage: <color=#AAFF00FF>+6%</color>",
    "Source": "Elder Lightning",
    "Droprate": "50%",
    "Location": "Underground Cavern",
    "SpriteId": "card",
    "SourceLevel": 89
  },
  {
    "Name": "Ember Card",
    "CardId": "Fire",
    "Affix": "Energy",
    "Slot": "Head",
    "Stats": "HP Regen: <color=#AAFF00FF>+25%</color>\nMP Regen: <color=#AAFF00FF>+25%</color>",
    "Source": "Ember",
    "Droprate": "50%",
    "Location": "Demon's Maw",
    "SpriteId": "card",
    "SourceLevel": 96
  },
  {
    "Name": "Eyeclops Arcanist Card",
    "CardId": "Cyclops Bat Wizard",
    "Affix": "Wizardry",
    "Slot": "Head",
    "Stats": "Cast Speed: <color=#AAFF00FF>+15%</color>",
    "Source": "Eyeclops Arcanist",
    "Droprate": "50%",
    "Location": "Abyss Castle Keep",
    "SpriteId": "card",
    "SourceLevel": 113
  },
  {
    "Name": "Eyeclops Bat Card",
    "CardId": "Cyclops Bat",
    "Affix": "Mind",
    "Slot": "Legs",
    "Stats": "Magic Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Eyeclops Bat",
    "Droprate": "50%",
    "Location": "Abyss Castle Keep",
    "SpriteId": "card",
    "SourceLevel": 111
  },
  {
    "Name": "Eyeclops Mage Card",
    "CardId": "Cyclops Bat Mage",
    "Affix": "Magic",
    "Slot": "Weapon",
    "Stats": "Magic Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Eyeclops Mage",
    "Droprate": "50%",
    "Location": "Abyss Castle Library",
    "SpriteId": "card",
    "SourceLevel": 123
  },
  {
    "Name": "Fairy Card",
    "CardId": "Butterfly Fairy",
    "Affix": "Unbreaking",
    "Slot": "Legs",
    "Stats": "<color=#FF9700FF>Casting cannot be interrupted.</color>\nMP: <color=#FF0073FF>-10%</color>",
    "Source": "Fairy",
    "Droprate": "50%",
    "Location": "Fairy Glen",
    "SpriteId": "card",
    "SourceLevel": 33
  },
  {
    "Name": "Festive Baby Card",
    "CardId": "Mini Ice Bear B",
    "Affix": "Lightproof",
    "Slot": "Legs",
    "Stats": "Holy Resistance: <color=#AAFF00FF>+15%</color>",
    "Source": "Festive Baby",
    "Droprate": "50%",
    "Location": "Starfall Tundra",
    "SpriteId": "card",
    "SourceLevel": 132
  },
  {
    "Name": "Festive Bear Card",
    "CardId": "Ice Bear B",
    "Affix": "Stone",
    "Slot": "Legs",
    "Stats": "DEF: <color=#AAFF00FF>+5%</color>\nMDEF: <color=#AAFF00FF>+5%</color>",
    "Source": "Festive Bear",
    "Droprate": "50%",
    "Location": "Starfall Tundra",
    "SpriteId": "card",
    "SourceLevel": 135
  },
  {
    "Name": "Fire Glimmer Card",
    "CardId": "Glow Wisp Yellow",
    "Affix": "Pyre",
    "Slot": "Chest",
    "Stats": "Fire Damage: <color=#AAFF00FF>+1% per level</color>\nMATK: <color=#AAFF00FF>+1%</color>",
    "Source": "Fire Glimmer",
    "Droprate": "50%",
    "Location": "Fairy Glen",
    "SpriteId": "card",
    "SourceLevel": 33
  },
  {
    "Name": "Fire Mage Card",
    "CardId": "Fire Mage",
    "Affix": "Mind",
    "Slot": "Weapon",
    "Stats": "MATK: <color=#AAFF00FF>+4%</color>",
    "Source": "Fire Mage",
    "Droprate": "50%",
    "Location": "Demon's Maw",
    "SpriteId": "card",
    "SourceLevel": 99
  },
  {
    "Name": "Fire Wisp Card",
    "CardId": "Wisp Red",
    "Affix": "Pyre",
    "Slot": "Weapon",
    "Stats": "Fire Damage: <color=#AAFF00FF>+6%</color>",
    "Source": "Fire Wisp",
    "Droprate": "50%",
    "Location": "Forest Field 1",
    "SpriteId": "card",
    "SourceLevel": 14
  },
  {
    "Name": "Flame Drake Card",
    "CardId": "Dragon Fire",
    "Affix": "Fireproof",
    "Slot": "Legs",
    "Stats": "Fire Resistance: <color=#AAFF00FF>+15%</color>",
    "Source": "Flame Drake",
    "Droprate": "50%",
    "Location": "Demon's Maw",
    "SpriteId": "card",
    "SourceLevel": 98
  },
  {
    "Name": "Fledgling Card",
    "CardId": "Fledgling",
    "Affix": "Accurate",
    "Slot": "Weapon",
    "Stats": "Hit: <color=#AAFF00FF>+25</color>",
    "Source": "Fledgling",
    "Droprate": "50%",
    "Location": "Sunny Meadows 2",
    "SpriteId": "card",
    "SourceLevel": 8
  },
  {
    "Name": "Flora Card",
    "CardId": "Flora",
    "Affix": "Frosty",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.1 Ice Shard</color>",
    "Source": "Flora",
    "Droprate": "50%",
    "Location": "Mystic Lake 1",
    "SpriteId": "card",
    "SourceLevel": 34
  },
  {
    "Name": "Frost Glimmer Card",
    "CardId": "Glow Wisp Blue",
    "Affix": "Glacial",
    "Slot": "Chest",
    "Stats": "Water Damage: <color=#AAFF00FF>+1% per level</color>\nMATK: <color=#AAFF00FF>+1%</color>",
    "Source": "Frost Glimmer",
    "Droprate": "50%",
    "Location": "Mystic Lake 1",
    "SpriteId": "card",
    "SourceLevel": 32
  },
  {
    "Name": "Frost Wisp Card",
    "CardId": "Wisp Blue",
    "Affix": "Glacial",
    "Slot": "Weapon",
    "Stats": "Water Damage: <color=#AAFF00FF>+6%</color>",
    "Source": "Frost Wisp",
    "Droprate": "50%",
    "Location": "Forest Field 1",
    "SpriteId": "card",
    "SourceLevel": 11
  },
  {
    "Name": "Frost Wyvern Card",
    "CardId": "Dragon Blizzard",
    "Affix": "Diamond",
    "Slot": "Chest",
    "Stats": "Resistance to Frozen: <color=#AAFF00FF>+50%</color>",
    "Source": "Frost Wyvern",
    "Droprate": "50%",
    "Location": "Crystal Cave",
    "SpriteId": "card",
    "SourceLevel": 74
  },
  {
    "Name": "Fungi Card",
    "CardId": "Fungi",
    "Affix": "Heal",
    "Slot": "Accessory",
    "Stats": "Grants <color=#AAFF00FF>Lv.5 Heal</color>",
    "Source": "Fungi",
    "Droprate": "50%",
    "Location": "Lake Field",
    "SpriteId": "card",
    "SourceLevel": 28
  },
  {
    "Name": "Gadfly Card",
    "CardId": "Housefly Icky",
    "Affix": "Assassin's",
    "Slot": "Accessory",
    "Stats": "Crit: <color=#AAFF00FF>+5</color>",
    "Source": "Gadfly",
    "Droprate": "50%",
    "Location": "Swamp",
    "SpriteId": "card",
    "SourceLevel": 37
  },
  {
    "Name": "Gale Card",
    "CardId": "Wind",
    "Affix": "Focus",
    "Slot": "Feet",
    "Stats": "MP: <color=#AAFF00FF>+10 per level</color>\nMP: <color=#AAFF00FF>+1% per level</color>",
    "Source": "Gale",
    "Droprate": "50%",
    "Location": "Windy Desert",
    "SpriteId": "card",
    "SourceLevel": 28
  },
  {
    "Name": "Ghost Card",
    "CardId": "Ghost",
    "Affix": "Cloaking",
    "Slot": "Legs",
    "Stats": "Perfect Cloaking: <color=#FF9700FF>undetectable by shadow monsters when invisible</color>",
    "Source": "Ghost",
    "Droprate": "50%",
    "Location": "Sanctum of Light",
    "SpriteId": "card",
    "SourceLevel": 77
  },
  {
    "Name": "Gnat Card",
    "CardId": "Mosquito Bug",
    "Affix": "Vampiric",
    "Slot": "Accessory",
    "Stats": "Health Leech: <color=#AAFF00FF>+5%</color>",
    "Source": "Gnat",
    "Droprate": "50%",
    "Location": "Swamp",
    "SpriteId": "card",
    "SourceLevel": 37
  },
  {
    "Name": "Goblin Assassin Card",
    "CardId": "Goblin Trooper Assassin",
    "Affix": "Mobile",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.1 Shadow Step</color>",
    "Source": "Goblin Assassin",
    "Droprate": "50%",
    "Location": "Goblin Field",
    "SpriteId": "card",
    "SourceLevel": 43
  },
  {
    "Name": "Goblin Card",
    "CardId": "Goblin Minion",
    "Affix": "Bashing",
    "Slot": "Weapon",
    "Stats": "Bash Area: <color=#AAFF00FF>+3</color>",
    "Source": "Goblin",
    "Droprate": "50%",
    "Location": "Goblin Field",
    "SpriteId": "card",
    "SourceLevel": 41
  },
  {
    "Name": "Goblin Grunt Card",
    "CardId": "Goblin Trooper",
    "Affix": "Mudproof",
    "Slot": "Legs",
    "Stats": "Earth Resistance: <color=#AAFF00FF>+15%</color>",
    "Source": "Goblin Grunt",
    "Droprate": "50%",
    "Location": "Goblin Field",
    "SpriteId": "card",
    "SourceLevel": 44
  },
  {
    "Name": "Goblin Mage Card",
    "CardId": "Goblin Trooper Mage",
    "Affix": "Free",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.3 Free Cast</color>",
    "Source": "Goblin Mage",
    "Droprate": "50%",
    "Location": "Goblin Field",
    "SpriteId": "card",
    "SourceLevel": 42
  },
  {
    "Name": "Goblin Soldier Card",
    "CardId": "Goblin Trooper Soldier",
    "Affix": "Vital",
    "Slot": "Legs",
    "Stats": "HP: <color=#AAFF00FF>+50 per level</color>",
    "Source": "Goblin Soldier",
    "Droprate": "50%",
    "Location": "Goblin Field",
    "SpriteId": "card",
    "SourceLevel": 45
  },
  {
    "Name": "Goldtail Card",
    "CardId": "Fish Yellow",
    "Affix": "Perfect",
    "Slot": "Legs",
    "Stats": "Perfect Dodge: <color=#AAFF00FF>+5%</color>",
    "Source": "Goldtail",
    "Droprate": "50%",
    "Location": "Sunken Depths",
    "SpriteId": "card",
    "SourceLevel": 102
  },
  {
    "Name": "Gremlin Card",
    "CardId": "Imp Mischief",
    "Affix": "Mischief",
    "Slot": "Shield",
    "Stats": "Chance to reflect single-target magic.: <color=#AAFF00FF>+2% per level</color>",
    "Source": "Gremlin",
    "Droprate": "50%",
    "Location": "Demon's Maw",
    "SpriteId": "card",
    "SourceLevel": 96
  },
  {
    "Name": "Gripper Robot Card",
    "CardId": "Gripper Robot",
    "Affix": "Immune",
    "Slot": "Chest",
    "Stats": "Neutral Resistance: <color=#AAFF00FF>+10%</color>\nHP: <color=#AAFF00FF>+10%</color>",
    "Source": "Gripper Robot",
    "Droprate": "50%",
    "Location": "The Forge",
    "SpriteId": "card",
    "SourceLevel": 130
  },
  {
    "Name": "Hawker Card",
    "CardId": "Dragonfly Swift",
    "Affix": "Elusive",
    "Slot": "Shield",
    "Stats": "Flee: <color=#AAFF00FF>+25</color>",
    "Source": "Hawker",
    "Droprate": "50%",
    "Location": "Swamp Wilderness",
    "SpriteId": "card",
    "SourceLevel": 68
  },
  {
    "Name": "Hellhound Card",
    "CardId": "Dog Bowwow",
    "Affix": "Flaming",
    "Slot": "Weapon",
    "Stats": "<color=#FF9700FF>Fireball: <color=#AAFF00FF>Remove Knockback</color></color>\n<color=#FF9700FF>Firewall: <color=#AAFF00FF>Remove Knockback</color></color>",
    "Source": "Hellhound",
    "Droprate": "50%",
    "Location": "Windy Desert North",
    "SpriteId": "card",
    "SourceLevel": 34
  },
  {
    "Name": "Hermit Card",
    "CardId": "Spike",
    "Affix": "Focus",
    "Slot": "Legs",
    "Stats": "MP: <color=#AAFF00FF>+10%</color>",
    "Source": "Hermit",
    "Droprate": "50%",
    "Location": "Mystic Lake 2",
    "SpriteId": "card",
    "SourceLevel": 40
  },
  {
    "Name": "Hermit King Card",
    "CardId": "Hermit King",
    "Affix": "Hydro",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.1 Hydro Vortex</color>",
    "Source": "Hermit King",
    "Droprate": "300%",
    "Location": "Mystic Lake 2",
    "SpriteId": "card_gold",
    "SourceLevel": 45
  },
  {
    "Name": "Horror Card",
    "CardId": "Horror",
    "Affix": "Exorcist",
    "Slot": "Weapon",
    "Stats": "Damage versus Shadow Enemies: <color=#AAFF00FF>+10%</color>",
    "Source": "Horror",
    "Droprate": "50%",
    "Location": "Forgotten Depths 2",
    "SpriteId": "card",
    "SourceLevel": 50
  },
  {
    "Name": "Hound Card",
    "CardId": "Dog Bark",
    "Affix": "Flaming",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.1 Fireball</color>",
    "Source": "Hound",
    "Droprate": "50%",
    "Location": "Forest Field 2",
    "SpriteId": "card",
    "SourceLevel": 20
  },
  {
    "Name": "Hydro Turtle Card",
    "CardId": "Titan Turtle Sci Blue",
    "Affix": "Freezing",
    "Slot": "Weapon",
    "Stats": "<color=#FF9700FF>Blizzard: <color=#AAFF00FF>Remove Knockback</color></color>",
    "Source": "Hydro Turtle",
    "Droprate": "50%",
    "Location": "Turtle Nexus",
    "SpriteId": "card",
    "SourceLevel": 134
  },
  {
    "Name": "Ice Baby Card",
    "CardId": "Mini Ice Bear A",
    "Affix": "Thawing",
    "Slot": "Legs",
    "Stats": "Resistance to Frozen: <color=#AAFF00FF>+50%</color>",
    "Source": "Ice Baby",
    "Droprate": "50%",
    "Location": "Starfall Tundra",
    "SpriteId": "card",
    "SourceLevel": 132
  },
  {
    "Name": "Ice Bear Card",
    "CardId": "Ice Bear A",
    "Affix": "Vital",
    "Slot": "Chest",
    "Stats": "HP: <color=#AAFF00FF>+800</color>\nMP: <color=#FF0073FF>-15%</color>",
    "Source": "Ice Bear",
    "Droprate": "50%",
    "Location": "Starfall Tundra",
    "SpriteId": "card",
    "SourceLevel": 134
  },
  {
    "Name": "Ice Card",
    "CardId": "Ice",
    "Affix": "Icepick",
    "Slot": "Accessory",
    "Stats": "<color=#FF9700FF>Immune to reflected damage.</color>",
    "Source": "Ice",
    "Droprate": "50%",
    "Location": "Crystal Cave",
    "SpriteId": "card",
    "SourceLevel": 71
  },
  {
    "Name": "Ice Mage Card",
    "CardId": "Ice Mage",
    "Affix": "Thawing",
    "Slot": "Chest",
    "Stats": "<color=#FF9700FF>Convert to <sprite name=water> <color=#79D7FDFF>Water</color> element</color>\nResistance to Frozen: <color=#AAFF00FF>+50%</color>",
    "Source": "Ice Mage",
    "Droprate": "300%",
    "Location": "Crystal Cave",
    "SpriteId": "card_gold",
    "SourceLevel": 80
  },
  {
    "Name": "Ice Titan Card",
    "CardId": "Mega Ice Golem",
    "Affix": "Permafrost",
    "Slot": "Head",
    "Stats": "Chance to autocast Lv.2 Ice Shard when hit: <color=#AAFF00FF>+1% per level</color>\nGrants <color=#AAFF00FF>Lv.1 Frost Rounds</color>",
    "Source": "Ice Titan",
    "Droprate": "300%",
    "Location": "Starfall Tundra",
    "SpriteId": "card_gold",
    "SourceLevel": 140
  },
  {
    "Name": "Icicle Card",
    "CardId": "Icicle",
    "Affix": "Thawing",
    "Slot": "Feet",
    "Stats": "Resistance to Slow: <color=#AAFF00FF>+50%</color>",
    "Source": "Icicle",
    "Droprate": "50%",
    "Location": "Crystal Cave",
    "SpriteId": "card",
    "SourceLevel": 73
  },
  {
    "Name": "Imp Card",
    "CardId": "Imp Demon",
    "Affix": "Swift",
    "Slot": "Legs",
    "Stats": "Movement Speed: <color=#AAFF00FF>+10%</color>",
    "Source": "Imp",
    "Droprate": "50%",
    "Location": "Demon's Maw",
    "SpriteId": "card",
    "SourceLevel": 97
  },
  {
    "Name": "Inferno Wyvern Card",
    "CardId": "Dragon Inferno",
    "Affix": "Power",
    "Slot": "Weapon",
    "Stats": "ATK: <color=#AAFF00FF>+4%</color>",
    "Source": "Inferno Wyvern",
    "Droprate": "50%",
    "Location": "Demon's Maw",
    "SpriteId": "card",
    "SourceLevel": 99
  },
  {
    "Name": "Jade Beholder Card",
    "CardId": "Eyeball Mage Green",
    "Affix": "Undead",
    "Slot": "Accessory",
    "Stats": "Undead Damage: <color=#AAFF00FF>+6%</color>",
    "Source": "Jade Beholder",
    "Droprate": "50%",
    "Location": "Abyss Castle Library",
    "SpriteId": "card",
    "SourceLevel": 124
  },
  {
    "Name": "Jade Eyestalk Card",
    "CardId": "Eyeball Creep Green",
    "Affix": "Focus",
    "Slot": "Accessory",
    "Stats": "MP: <color=#AAFF00FF>+10%</color>",
    "Source": "Jade Eyestalk",
    "Droprate": "50%",
    "Location": "Abyss Castle Crypt",
    "SpriteId": "card",
    "SourceLevel": 118
  },
  {
    "Name": "Jade Gazer Card",
    "CardId": "Eyeball Bat Green",
    "Affix": "Purity",
    "Slot": "Shield",
    "Stats": "Undead Resistance: <color=#AAFF00FF>+25%</color>",
    "Source": "Jade Gazer",
    "Droprate": "50%",
    "Location": "Festering Woods 1",
    "SpriteId": "card",
    "SourceLevel": 22
  },
  {
    "Name": "Jellooze Card",
    "CardId": "Slime Jelly",
    "Affix": "Poisonous",
    "Slot": "Accessory",
    "Stats": "Poison Damage: <color=#AAFF00FF>+6%</color>",
    "Source": "Jellooze",
    "Droprate": "50%",
    "Location": "Swamp Wilderness",
    "SpriteId": "card",
    "SourceLevel": 67
  },
  {
    "Name": "Kraken Card",
    "CardId": "Eyeball Monster",
    "Affix": "Abyss",
    "Slot": "Head",
    "Stats": "Ice Shard Projectiles: <color=#AAFF00FF>+3</color>\nGrants <color=#AAFF00FF>Lv.1 Blizzard</color>",
    "Source": "Kraken",
    "Droprate": "300%",
    "Location": "Sunken Depths",
    "SpriteId": "card_gold",
    "SourceLevel": 110
  },
  {
    "Name": "Lady Fey Card",
    "CardId": "Sunflora Pixie",
    "Affix": "Vocal",
    "Slot": "Head",
    "Stats": "Resistance to Silence: <color=#AAFF00FF>+50%</color>",
    "Source": "Lady Fey",
    "Droprate": "300%",
    "Location": "Fairy Glen",
    "SpriteId": "card_gold",
    "SourceLevel": 40
  },
  {
    "Name": "Lightning Glimmer Card",
    "CardId": "Glow Wisp Purple",
    "Affix": "Spark",
    "Slot": "Chest",
    "Stats": "Wind Damage: <color=#AAFF00FF>+1% per level</color>\nMATK: <color=#AAFF00FF>+1%</color>",
    "Source": "Lightning Glimmer",
    "Droprate": "50%",
    "Location": "Windy Desert",
    "SpriteId": "card",
    "SourceLevel": 27
  },
  {
    "Name": "Lightning Wisp Card",
    "CardId": "Wisp Purple",
    "Affix": "Spark",
    "Slot": "Weapon",
    "Stats": "Wind Damage: <color=#AAFF00FF>+6%</color>",
    "Source": "Lightning Wisp",
    "Droprate": "50%",
    "Location": "Forest Field 1",
    "SpriteId": "card",
    "SourceLevel": 12
  },
  {
    "Name": "Little Star Card",
    "CardId": "Alien Star",
    "Affix": "Sanctified",
    "Slot": "Accessory",
    "Stats": "Holy Damage: <color=#AAFF00FF>+6%</color>",
    "Source": "Little Star",
    "Droprate": "50%",
    "Location": "Starfall Tundra",
    "SpriteId": "card",
    "SourceLevel": 131
  },
  {
    "Name": "Luna Moth Card",
    "CardId": "Moth Luna",
    "Affix": "Wizardry",
    "Slot": "Weapon",
    "Stats": "Cast Speed: <color=#AAFF00FF>+10%</color>",
    "Source": "Luna Moth",
    "Droprate": "50%",
    "Location": "Fairy Glen",
    "SpriteId": "card",
    "SourceLevel": 32
  },
  {
    "Name": "Lurker Card",
    "CardId": "Lurker",
    "Affix": "Savage",
    "Slot": "Accessory",
    "Stats": "CRIT Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Lurker",
    "Droprate": "50%",
    "Location": "Forgotten Depths 1",
    "SpriteId": "card",
    "SourceLevel": 43
  },
  {
    "Name": "Lycanthrope Card",
    "CardId": "Werewolf",
    "Affix": "Tainted",
    "Slot": "Chest",
    "Stats": "<color=#FF9700FF>Convert to <sprite name=shadow> <color=#755E94FF>Shadow</color> element\n<color=#FF9700FF>Reveals invisible units.</color></color>",
    "Source": "Lycanthrope",
    "Droprate": "300%",
    "Location": "Festering Woods 2",
    "SpriteId": "card_gold",
    "SourceLevel": 35
  },
  {
    "Name": "Maggot Card",
    "CardId": "Worm Rot",
    "Affix": "Toxinproof",
    "Slot": "Legs",
    "Stats": "Poison Resistance: <color=#AAFF00FF>+15%</color>",
    "Source": "Maggot",
    "Droprate": "50%",
    "Location": "Underground Cavern",
    "SpriteId": "card",
    "SourceLevel": 88
  },
  {
    "Name": "Magma Golem Card",
    "CardId": "Golem Fire",
    "Affix": "Stone",
    "Slot": "Head",
    "Stats": "DEF: <color=#AAFF00FF>+10%</color>",
    "Source": "Magma Golem",
    "Droprate": "50%",
    "Location": "Demon's Maw",
    "SpriteId": "card",
    "SourceLevel": 100
  },
  {
    "Name": "Man-Eater Card",
    "CardId": "Plant Chewer",
    "Affix": "Basic",
    "Slot": "Weapon",
    "Stats": "Damage versus Neutral Enemies: <color=#AAFF00FF>+10%</color>",
    "Source": "Man-Eater",
    "Droprate": "50%",
    "Location": "Windy Desert South",
    "SpriteId": "card",
    "SourceLevel": 34
  },
  {
    "Name": "Mandrake Card",
    "CardId": "Flower Pot Monster",
    "Affix": "Quagmire",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.1 Earth Spikes</color>",
    "Source": "Mandrake",
    "Droprate": "50%",
    "Location": "Treant Trail",
    "SpriteId": "card",
    "SourceLevel": 20
  },
  {
    "Name": "Maple Ancient Card",
    "CardId": "Treant Forest Autumn",
    "Affix": "Autumn",
    "Slot": "Shield",
    "Stats": "Maximum MP recovered per second: <color=#AAFF00FF>+1%</color>",
    "Source": "Maple Ancient",
    "Droprate": "50%",
    "Location": "Treant Trail",
    "SpriteId": "card",
    "SourceLevel": 19
  },
  {
    "Name": "Maple Sapling Card",
    "CardId": "Treant Minion Autumn",
    "Affix": "Autumn",
    "Slot": "Feet",
    "Stats": "MP: <color=#AAFF00FF>+20</color>\nMP Regen: <color=#AAFF00FF>+25%</color>",
    "Source": "Maple Sapling",
    "Droprate": "50%",
    "Location": "Treant Trail",
    "SpriteId": "card",
    "SourceLevel": 16
  },
  {
    "Name": "Maple Treant Card",
    "CardId": "Treant Tree Autumn",
    "Affix": "Autumn",
    "Slot": "Chest",
    "Stats": "MP: <color=#AAFF00FF>+20%</color>",
    "Source": "Maple Treant",
    "Droprate": "50%",
    "Location": "Treant Trail",
    "SpriteId": "card",
    "SourceLevel": 17
  },
  {
    "Name": "Miasma Card",
    "CardId": "Poison Bomb",
    "Affix": "Toxic",
    "Slot": "Accessory",
    "Stats": "Status Duration: <color=#AAFF00FF>+15%</color>",
    "Source": "Miasma",
    "Droprate": "50%",
    "Location": "Underground Cavern",
    "SpriteId": "card",
    "SourceLevel": 87
  },
  {
    "Name": "Mole Card",
    "CardId": "Mole Rat",
    "Affix": "Vital",
    "Slot": "Legs",
    "Stats": "HP: <color=#AAFF00FF>+10%</color>",
    "Source": "Mole",
    "Droprate": "50%",
    "Location": "Windy Desert North",
    "SpriteId": "card",
    "SourceLevel": 32
  },
  {
    "Name": "Moon Moth Card",
    "CardId": "Moth Moon",
    "Affix": "Cloaking",
    "Slot": "Chest",
    "Stats": "Perfect Cloaking: <color=#FF9700FF>undetectable by shadow monsters when invisible</color>",
    "Source": "Moon Moth",
    "Droprate": "50%",
    "Location": "Fairy Glen",
    "SpriteId": "card",
    "SourceLevel": 34
  },
  {
    "Name": "Mosquito Card",
    "CardId": "Mosquito Pester",
    "Affix": "Windproof",
    "Slot": "Legs",
    "Stats": "Wind Resistance: <color=#AAFF00FF>+15%</color>",
    "Source": "Mosquito",
    "Droprate": "50%",
    "Location": "Swamp",
    "SpriteId": "card",
    "SourceLevel": 40
  },
  {
    "Name": "Naga Card",
    "CardId": "Snake Naga",
    "Affix": "Twinfang",
    "Slot": "Weapon",
    "Stats": "Multistrike: <color=#AAFF00FF>+30%</color>",
    "Source": "Naga",
    "Droprate": "300%",
    "Location": "Forgotten Depths 1",
    "SpriteId": "card_gold",
    "SourceLevel": 50
  },
  {
    "Name": "Nautilus Card",
    "CardId": "Petal",
    "Affix": "Hoarfrost",
    "Slot": "Weapon",
    "Stats": "Damage versus Water Enemies: <color=#AAFF00FF>+10%</color>",
    "Source": "Nautilus",
    "Droprate": "50%",
    "Location": "Mystic Lake 1",
    "SpriteId": "card",
    "SourceLevel": 35
  },
  {
    "Name": "Night Baron Card",
    "CardId": "Bat Lord",
    "Affix": "Siphoning",
    "Slot": "Accessory",
    "Stats": "Siphon MP: <color=#AAFF00FF>+3</color>",
    "Source": "Night Baron",
    "Droprate": "300%",
    "Location": "Forgotten Depths 2",
    "SpriteId": "card_gold",
    "SourceLevel": 55
  },
  {
    "Name": "Night Drake Card",
    "CardId": "Dragon Nightfall",
    "Affix": "Savage",
    "Slot": "Head",
    "Stats": "CRIT Damage: <color=#AAFF00FF>+10%</color>",
    "Source": "Night Drake",
    "Droprate": "50%",
    "Location": "Sanctum of Light",
    "SpriteId": "card",
    "SourceLevel": 79
  },
  {
    "Name": "Nightbloom Card",
    "CardId": "Bloom",
    "Affix": "Status",
    "Slot": "Accessory",
    "Stats": "Status Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Nightbloom",
    "Droprate": "50%",
    "Location": "Underground Cavern",
    "SpriteId": "card",
    "SourceLevel": 89
  },
  {
    "Name": "Nightfiend Card",
    "CardId": "Shadow",
    "Affix": "Mystery",
    "Slot": "Accessory",
    "Stats": "All Stats: <color=#AAFF00FF>+1</color>\nHP: <color=#AAFF00FF>+5%</color>\nMP: <color=#AAFF00FF>+5%</color>",
    "Source": "Nightfiend",
    "Droprate": "50%",
    "Location": "Demon's Maw",
    "SpriteId": "card",
    "SourceLevel": 100
  },
  {
    "Name": "Nightlord Card",
    "CardId": "Monster Bat King",
    "Affix": "Mana Burn",
    "Slot": "Head",
    "Stats": "Siphon MP: <color=#AAFF00FF>+3</color>\nMP: <color=#FF0073FF>-50%</color>",
    "Source": "Nightlord",
    "Droprate": "50%",
    "Location": "Goblin Cave 2",
    "SpriteId": "card",
    "SourceLevel": 56
  },
  {
    "Name": "Nightwing Card",
    "CardId": "Monster Bat",
    "Affix": "Focus",
    "Slot": "Feet",
    "Stats": "MP: <color=#AAFF00FF>+10%</color>",
    "Source": "Nightwing",
    "Droprate": "50%",
    "Location": "Goblin Cave 1",
    "SpriteId": "card",
    "SourceLevel": 51
  },
  {
    "Name": "Nose Robot Card",
    "CardId": "Nose Robot",
    "Affix": "Overheat",
    "Slot": "Head",
    "Stats": "Chance to autocast Lv.2 Fire Pillar when hit: <color=#AAFF00FF>+1% per level</color>",
    "Source": "Nose Robot",
    "Droprate": "50%",
    "Location": "The Forge",
    "SpriteId": "card",
    "SourceLevel": 128
  },
  {
    "Name": "Nosferatu Card",
    "CardId": "Vampire Bat",
    "Affix": "Leeching",
    "Slot": "Accessory",
    "Stats": "Siphon HP: <color=#AAFF00FF>+10</color>",
    "Source": "Nosferatu",
    "Droprate": "50%",
    "Location": "Forgotten Depths 2",
    "SpriteId": "card",
    "SourceLevel": 46
  },
  {
    "Name": "Nozzle Robot Card",
    "CardId": "Nozzle Robot",
    "Affix": "Carrier",
    "Slot": "Legs",
    "Stats": "Weight Limit: <color=#AAFF00FF>+100 per level</color>",
    "Source": "Nozzle Robot",
    "Droprate": "50%",
    "Location": "The Forge",
    "SpriteId": "card",
    "SourceLevel": 127
  },
  {
    "Name": "Nymph Card",
    "CardId": "Sun Blossom",
    "Affix": "Blessed",
    "Slot": "Shield",
    "Stats": "Healing: <color=#AAFF00FF>+15%</color>",
    "Source": "Nymph",
    "Droprate": "50%",
    "Location": "Fairy Glen",
    "SpriteId": "card",
    "SourceLevel": 32
  },
  {
    "Name": "Oozelord Card",
    "CardId": "Slime Monster",
    "Affix": "Anti-Venom",
    "Slot": "Head",
    "Stats": "Resistance to Poison: <color=#AAFF00FF>+50%</color>",
    "Source": "Oozelord",
    "Droprate": "50%",
    "Location": "Swamp Wilderness",
    "SpriteId": "card",
    "SourceLevel": 70
  },
  {
    "Name": "Orc Card",
    "CardId": "Goblin Giant",
    "Affix": "Vital",
    "Slot": "Feet",
    "Stats": "HP: <color=#AAFF00FF>+10%</color>",
    "Source": "Orc",
    "Droprate": "50%",
    "Location": "Goblin Village",
    "SpriteId": "card",
    "SourceLevel": 48
  },
  {
    "Name": "Orc Crusher Card",
    "CardId": "Goblin Warcrusher",
    "Affix": "Seismic",
    "Slot": "Accessory",
    "Stats": "Earth Damage: <color=#AAFF00FF>+6%</color>",
    "Source": "Orc Crusher",
    "Droprate": "50%",
    "Location": "Goblin Warcamp",
    "SpriteId": "card",
    "SourceLevel": 125
  },
  {
    "Name": "Orc King Card",
    "CardId": "Goblin Giant Gold",
    "Affix": "Earthen",
    "Slot": "Chest",
    "Stats": "<color=#FF9700FF>Convert to <sprite name=earth> <color=#BB7B2FFF>Earth</color> element</color>",
    "Source": "Orc King",
    "Droprate": "300%",
    "Location": "Goblin Village",
    "SpriteId": "card_gold",
    "SourceLevel": 55
  },
  {
    "Name": "Orc Mage Card",
    "CardId": "Goblin Giant Mage",
    "Affix": "Seismic",
    "Slot": "Chest",
    "Stats": "Earth Damage: <color=#AAFF00FF>+1% per level</color>\nMATK: <color=#AAFF00FF>+1%</color>",
    "Source": "Orc Mage",
    "Droprate": "50%",
    "Location": "Goblin Village",
    "SpriteId": "card",
    "SourceLevel": 46
  },
  {
    "Name": "Orc Reaver Card",
    "CardId": "Goblin Warblade",
    "Affix": "Spiked",
    "Slot": "Chest",
    "Stats": "Reflect Damage: <color=#AAFF00FF>+30%</color>",
    "Source": "Orc Reaver",
    "Droprate": "50%",
    "Location": "Goblin Warcamp",
    "SpriteId": "card",
    "SourceLevel": 123
  },
  {
    "Name": "Orc Soldier Card",
    "CardId": "Goblin Giant Devil",
    "Affix": "Quaking",
    "Slot": "Weapon",
    "Stats": "Damage versus Earth Enemies: <color=#AAFF00FF>+10%</color>",
    "Source": "Orc Soldier",
    "Droprate": "50%",
    "Location": "Goblin Village",
    "SpriteId": "card",
    "SourceLevel": 50
  },
  {
    "Name": "Orc Warchief Card",
    "CardId": "Goblin Warchief",
    "Affix": "Elemental",
    "Slot": "Weapon",
    "Stats": "Fire Damage: <color=#AAFF00FF>+6%</color>\nWater Damage: <color=#AAFF00FF>+6%</color>\nWind Damage: <color=#AAFF00FF>+6%</color>\nEarth Damage: <color=#AAFF00FF>+6%</color>",
    "Source": "Orc Warchief",
    "Droprate": "300%",
    "Location": "Goblin Warcamp",
    "SpriteId": "card_gold",
    "SourceLevel": 130
  },
  {
    "Name": "Orc Warlock Card",
    "CardId": "Goblin Warlock",
    "Affix": "Mind",
    "Slot": "Head",
    "Stats": "MATK: <color=#AAFF00FF>+4%</color>",
    "Source": "Orc Warlock",
    "Droprate": "50%",
    "Location": "Goblin Warcamp",
    "SpriteId": "card",
    "SourceLevel": 121
  },
  {
    "Name": "Phantom Card",
    "CardId": "Phantom",
    "Affix": "Ethereal",
    "Slot": "Shield",
    "Stats": "Ghost Resistance: <color=#AAFF00FF>+25%</color>",
    "Source": "Phantom",
    "Droprate": "50%",
    "Location": "Sanctum of Light",
    "SpriteId": "card",
    "SourceLevel": 83
  },
  {
    "Name": "Pine Ancient Card",
    "CardId": "Treant Forest Evergreen",
    "Affix": "Evergreen",
    "Slot": "Shield",
    "Stats": "HP Regen: <color=#AAFF00FF>+10% per level</color>",
    "Source": "Pine Ancient",
    "Droprate": "50%",
    "Location": "Treant Trail",
    "SpriteId": "card",
    "SourceLevel": 19
  },
  {
    "Name": "Pine Sapling Card",
    "CardId": "Treant Minion Evergreen",
    "Affix": "Evergreen",
    "Slot": "Legs",
    "Stats": "HP: <color=#AAFF00FF>+100</color>\nHP Regen: <color=#AAFF00FF>+25%</color>",
    "Source": "Pine Sapling",
    "Droprate": "50%",
    "Location": "Treant Trail",
    "SpriteId": "card",
    "SourceLevel": 17
  },
  {
    "Name": "Pine Treant Card",
    "CardId": "Treant Tree Evergreen",
    "Affix": "Evergreen",
    "Slot": "Chest",
    "Stats": "HP: <color=#AAFF00FF>+20%</color>",
    "Source": "Pine Treant",
    "Droprate": "50%",
    "Location": "Treant Trail",
    "SpriteId": "card",
    "SourceLevel": 18
  },
  {
    "Name": "Pixie Card",
    "CardId": "Butterfly Pixie",
    "Affix": "Unholy",
    "Slot": "Weapon",
    "Stats": "Damage versus Holy Enemies: <color=#AAFF00FF>+10%</color>",
    "Source": "Pixie",
    "Droprate": "50%",
    "Location": "Fairy Glen",
    "SpriteId": "card",
    "SourceLevel": 35
  },
  {
    "Name": "Plague Rat Card",
    "CardId": "Rat Grey",
    "Affix": "Anti-Venom",
    "Slot": "Shield",
    "Stats": "Resistance to Poison: <color=#AAFF00FF>+50%</color>\nVit: <color=#AAFF00FF>+1</color>",
    "Source": "Plague Rat",
    "Droprate": "50%",
    "Location": "Nevaris Sewers",
    "SpriteId": "card",
    "SourceLevel": 18
  },
  {
    "Name": "Plum Squid Card",
    "CardId": "Octopus Baby Purple",
    "Affix": "Elusive",
    "Slot": "Feet",
    "Stats": "Total FLEE: <color=#AAFF00FF>+5%</color>",
    "Source": "Plum Squid",
    "Droprate": "50%",
    "Location": "Sunken Depths",
    "SpriteId": "card",
    "SourceLevel": 103
  },
  {
    "Name": "Pollen Card",
    "CardId": "Pollen",
    "Affix": "Elusive",
    "Slot": "Chest",
    "Stats": "Flee: <color=#AAFF00FF>+15</color>",
    "Source": "Pollen",
    "Droprate": "50%",
    "Location": "Sunny Meadows 1",
    "SpriteId": "card",
    "SourceLevel": 1
  },
  {
    "Name": "Pup Card",
    "CardId": "Dog Pup",
    "Affix": "Flaming",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.3 Firebolt</color>",
    "Source": "Pup",
    "Droprate": "50%",
    "Location": "Forest Field 2",
    "SpriteId": "card",
    "SourceLevel": 19
  },
  {
    "Name": "Rabbit Card",
    "CardId": "Rabbit",
    "Affix": "Swift",
    "Slot": "Feet",
    "Stats": "Movement Speed: <color=#AAFF00FF>+10%</color>",
    "Source": "Rabbit",
    "Droprate": "50%",
    "Location": "Bunny Woods",
    "SpriteId": "card",
    "SourceLevel": 25
  },
  {
    "Name": "Raiju Card",
    "CardId": "Cat Bolt",
    "Affix": "Gale",
    "Slot": "Chest",
    "Stats": "<color=#FF9700FF>Convert to <sprite name=wind> <color=#FFC701FF>Wind</color> element</color>",
    "Source": "Raiju",
    "Droprate": "300%",
    "Location": "Windy Desert",
    "SpriteId": "card_gold",
    "SourceLevel": 35
  },
  {
    "Name": "Razor Robot Card",
    "CardId": "Razor Robot",
    "Affix": "Rapid",
    "Slot": "Feet",
    "Stats": "Attack Speed: <color=#AAFF00FF>+5%</color>\nMovement Speed: <color=#AAFF00FF>+5%</color>",
    "Source": "Razor Robot",
    "Droprate": "50%",
    "Location": "The Forge",
    "SpriteId": "card",
    "SourceLevel": 126
  },
  {
    "Name": "Reaper Card",
    "CardId": "Grim Reaper",
    "Affix": "Melee",
    "Slot": "Weapon",
    "Stats": "Melee Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Reaper",
    "Droprate": "50%",
    "Location": "Abyss Castle Crypt",
    "SpriteId": "card",
    "SourceLevel": 119
  },
  {
    "Name": "Rime Drake Card",
    "CardId": "Dragon Ice",
    "Affix": "Freezing",
    "Slot": "Weapon",
    "Stats": "<color=#FF9700FF>Ice Shard: <color=#AAFF00FF>Pierces Targets</color></color>",
    "Source": "Rime Drake",
    "Droprate": "50%",
    "Location": "Crystal Cave",
    "SpriteId": "card",
    "SourceLevel": 73
  },
  {
    "Name": "Rime Golem Card",
    "CardId": "Golem Ice",
    "Affix": "Stone",
    "Slot": "Shield",
    "Stats": "DEF: <color=#AAFF00FF>+3% per level</color>",
    "Source": "Rime Golem",
    "Droprate": "50%",
    "Location": "Crystal Cave",
    "SpriteId": "card",
    "SourceLevel": 75
  },
  {
    "Name": "Rooster Card",
    "CardId": "Bird",
    "Affix": "Sniper",
    "Slot": "Head",
    "Stats": "Total HIT: <color=#AAFF00FF>+10%</color>",
    "Source": "Rooster",
    "Droprate": "50%",
    "Location": "Sunny Meadows 2",
    "SpriteId": "card",
    "SourceLevel": 10
  },
  {
    "Name": "Roseate Merling Card",
    "CardId": "Fish Man Pink",
    "Affix": "Power",
    "Slot": "Legs",
    "Stats": "Atk: <color=#AAFF00FF>+10</color>",
    "Source": "Roseate Merling",
    "Droprate": "50%",
    "Location": "Sunken Depths",
    "SpriteId": "card",
    "SourceLevel": 103
  },
  {
    "Name": "Rosetail Card",
    "CardId": "Fish Pink",
    "Affix": "Violent",
    "Slot": "Legs",
    "Stats": "Atk: <color=#AAFF00FF>+5</color>\nMatk: <color=#AAFF00FF>+5</color>",
    "Source": "Rosetail",
    "Droprate": "50%",
    "Location": "Sunken Depths",
    "SpriteId": "card",
    "SourceLevel": 101
  },
  {
    "Name": "Ruby Beholder Card",
    "CardId": "Eyeball Mage Red",
    "Affix": "Vampiric",
    "Slot": "Shield",
    "Stats": "Health Leech: <color=#AAFF00FF>+5%</color>",
    "Source": "Ruby Beholder",
    "Droprate": "50%",
    "Location": "Abyss Castle Library",
    "SpriteId": "card",
    "SourceLevel": 125
  },
  {
    "Name": "Ruby Eyestalk Card",
    "CardId": "Eyeball Creep Red",
    "Affix": "Focus",
    "Slot": "Feet",
    "Stats": "MP: <color=#AAFF00FF>+10%</color>",
    "Source": "Ruby Eyestalk",
    "Droprate": "50%",
    "Location": "Abyss Castle Crypt",
    "SpriteId": "card",
    "SourceLevel": 118
  },
  {
    "Name": "Ruby Gazer Card",
    "CardId": "Eyeball Bat Red",
    "Affix": "Vampiric",
    "Slot": "Shield",
    "Stats": "Chance to autocast Lv.2 Life Drain when hit: <color=#AAFF00FF>+1% per level</color>",
    "Source": "Ruby Gazer",
    "Droprate": "50%",
    "Location": "Festering Woods 1",
    "SpriteId": "card",
    "SourceLevel": 24
  },
  {
    "Name": "Sapphire Merman Card",
    "CardId": "Fish Merman Blue",
    "Affix": "Chaining",
    "Slot": "Shield",
    "Stats": "Shield Throw Chains: <color=#AAFF00FF>+2</color>",
    "Source": "Sapphire Merman",
    "Droprate": "50%",
    "Location": "Sunken Depths",
    "SpriteId": "card",
    "SourceLevel": 105
  },
  {
    "Name": "Scorpion Card",
    "CardId": "Scorpion",
    "Affix": "Fireproof",
    "Slot": "Shield",
    "Stats": "Fire Resistance: <color=#AAFF00FF>+25%</color>",
    "Source": "Scorpion",
    "Droprate": "50%",
    "Location": "Windy Desert North",
    "SpriteId": "card",
    "SourceLevel": 33
  },
  {
    "Name": "Scorpion King Card",
    "CardId": "Scorpion King",
    "Affix": "Blazing",
    "Slot": "Chest",
    "Stats": "<color=#FF9700FF>Convert to <sprite name=fire> <color=#FF7026FF>Fire</color> element</color>",
    "Source": "Scorpion King",
    "Droprate": "300%",
    "Location": "Windy Desert North",
    "SpriteId": "card_gold",
    "SourceLevel": 40
  },
  {
    "Name": "Scorpling Card",
    "CardId": "Scorpling",
    "Affix": "Ashen",
    "Slot": "Weapon",
    "Stats": "Damage versus Fire Enemies: <color=#AAFF00FF>+10%</color>",
    "Source": "Scorpling",
    "Droprate": "50%",
    "Location": "Windy Desert North",
    "SpriteId": "card",
    "SourceLevel": 31
  },
  {
    "Name": "Sea Blossom Card",
    "CardId": "Posy",
    "Affix": "Icy",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.3 Icebolt</color>",
    "Source": "Sea Blossom",
    "Droprate": "50%",
    "Location": "Mystic Lake 1",
    "SpriteId": "card",
    "SourceLevel": 31
  },
  {
    "Name": "Seedling Card",
    "CardId": "Seed",
    "Affix": "Vital",
    "Slot": "Weapon",
    "Stats": "HP: <color=#AAFF00FF>+100</color>\nVit: <color=#AAFF00FF>+1</color>",
    "Source": "Seedling",
    "Droprate": "50%",
    "Location": "Sunny Meadows 1",
    "SpriteId": "card",
    "SourceLevel": 5
  },
  {
    "Name": "Seraphim Arbiter Card",
    "CardId": "Angel Mage",
    "Affix": "Pure",
    "Slot": "Chest",
    "Stats": "<color=#FF9700FF>Convert to <sprite name=holy> <color=#FCE9EBFF>Holy</color> element</color>",
    "Source": "Seraphim Arbiter",
    "Droprate": "300%",
    "Location": "Sanctum of Light",
    "SpriteId": "card_gold",
    "SourceLevel": 90
  },
  {
    "Name": "Sewer Rat Card",
    "CardId": "Rat Dark",
    "Affix": "Elusive",
    "Slot": "Legs",
    "Stats": "Flee: <color=#AAFF00FF>+10</color>\nAgi: <color=#AAFF00FF>+1</color>",
    "Source": "Sewer Rat",
    "Droprate": "50%",
    "Location": "Nevaris Sewers",
    "SpriteId": "card",
    "SourceLevel": 16
  },
  {
    "Name": "Shade Card",
    "CardId": "Shade",
    "Affix": "Mystery",
    "Slot": "Head",
    "Stats": "All Stats: <color=#AAFF00FF>+1</color>\nHP: <color=#AAFF00FF>+5%</color>\nMP: <color=#AAFF00FF>+5%</color>",
    "Source": "Shade",
    "Droprate": "50%",
    "Location": "Demon's Maw",
    "SpriteId": "card",
    "SourceLevel": 98
  },
  {
    "Name": "Shadow Ice Card",
    "CardId": "Ice Starflake C",
    "Affix": "Umbral",
    "Slot": "Accessory",
    "Stats": "Shadow Damage: <color=#AAFF00FF>+6%</color>",
    "Source": "Shadow Ice",
    "Droprate": "50%",
    "Location": "Starfall Tundra",
    "SpriteId": "card",
    "SourceLevel": 134
  },
  {
    "Name": "Shadow Wyvern Card",
    "CardId": "Dragon Darkness",
    "Affix": "Violent",
    "Slot": "Chest",
    "Stats": "ATK: <color=#AAFF00FF>+1% per level</color>\nMATK: <color=#AAFF00FF>+1% per level</color>\nHP: <color=#FF0073FF>-50%</color>",
    "Source": "Shadow Wyvern",
    "Droprate": "50%",
    "Location": "Sanctum of Light",
    "SpriteId": "card",
    "SourceLevel": 84
  },
  {
    "Name": "Shark Buccaneer Card",
    "CardId": "Shark Humanoid",
    "Affix": "Taunting",
    "Slot": "Weapon",
    "Stats": "Threat Generation: <color=#AAFF00FF>+10% per level</color>",
    "Source": "Shark Buccaneer",
    "Droprate": "50%",
    "Location": "Stormreef Isle",
    "SpriteId": "card",
    "SourceLevel": 65
  },
  {
    "Name": "Sharkling Card",
    "CardId": "Shark Baby",
    "Affix": "Taunting",
    "Slot": "Shield",
    "Stats": "Threat Generation: <color=#AAFF00FF>+10% per level</color>",
    "Source": "Sharkling",
    "Droprate": "50%",
    "Location": "Stormreef Isle",
    "SpriteId": "card",
    "SourceLevel": 62
  },
  {
    "Name": "Shell Robot Card",
    "CardId": "Shell Robot",
    "Affix": "Rapid",
    "Slot": "Legs",
    "Stats": "Attack Speed: <color=#AAFF00FF>+10%</color>",
    "Source": "Shell Robot",
    "Droprate": "50%",
    "Location": "The Forge",
    "SpriteId": "card",
    "SourceLevel": 126
  },
  {
    "Name": "Shroom Card",
    "CardId": "Mushroom",
    "Affix": "Occult",
    "Slot": "Weapon",
    "Stats": "Matk: <color=#AAFF00FF>+5</color>",
    "Source": "Shroom",
    "Droprate": "50%",
    "Location": "Lake Field",
    "SpriteId": "card",
    "SourceLevel": 26
  },
  {
    "Name": "Skeleton Card",
    "CardId": "Skeleton",
    "Affix": "Undead",
    "Slot": "Weapon",
    "Stats": "Undead Damage: <color=#AAFF00FF>+6%</color>",
    "Source": "Skeleton",
    "Droprate": "50%",
    "Location": "Festering Woods 1",
    "SpriteId": "card",
    "SourceLevel": 25
  },
  {
    "Name": "Skeleton Giant Card",
    "CardId": "Skeleton Giant",
    "Affix": "Melee",
    "Slot": "Legs",
    "Stats": "Melee Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Skeleton Giant",
    "Droprate": "50%",
    "Location": "Abyss Castle Keep",
    "SpriteId": "card",
    "SourceLevel": 115
  },
  {
    "Name": "Skeleton Mage Card",
    "CardId": "Skeleton Mage",
    "Affix": "Mind",
    "Slot": "Accessory",
    "Stats": "MATK: <color=#AAFF00FF>+4%</color>",
    "Source": "Skeleton Mage",
    "Droprate": "50%",
    "Location": "Abyss Castle Keep",
    "SpriteId": "card",
    "SourceLevel": 113
  },
  {
    "Name": "Skimmer Card",
    "CardId": "Dragonfly Darner",
    "Affix": "Elusive",
    "Slot": "Legs",
    "Stats": "Flee: <color=#AAFF00FF>+20</color>",
    "Source": "Skimmer",
    "Droprate": "50%",
    "Location": "Swamp",
    "SpriteId": "card",
    "SourceLevel": 39
  },
  {
    "Name": "Slime Card",
    "CardId": "Slime",
    "Affix": "Toxinproof",
    "Slot": "Shield",
    "Stats": "Poison Resistance: <color=#AAFF00FF>+25%</color>",
    "Source": "Slime",
    "Droprate": "50%",
    "Location": "Swamp",
    "SpriteId": "card",
    "SourceLevel": 38
  },
  {
    "Name": "Snapvine Card",
    "CardId": "Plant Monster",
    "Affix": "Status",
    "Slot": "Weapon",
    "Stats": "Status Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Snapvine",
    "Droprate": "50%",
    "Location": "Swamp Wilderness",
    "SpriteId": "card",
    "SourceLevel": 67
  },
  {
    "Name": "Snout Robot Card",
    "CardId": "Snout Robot",
    "Affix": "Pillar",
    "Slot": "Weapon",
    "Stats": "Fire Pillar Maximum Instances: <color=#AAFF00FF>+1</color>",
    "Source": "Snout Robot",
    "Droprate": "50%",
    "Location": "The Forge",
    "SpriteId": "card",
    "SourceLevel": 129
  },
  {
    "Name": "Snowball Card",
    "CardId": "Snow Bomb",
    "Affix": "Freezing",
    "Slot": "Accessory",
    "Stats": "Status Duration: <color=#AAFF00FF>+15%</color>",
    "Source": "Snowball",
    "Droprate": "50%",
    "Location": "Crystal Cave",
    "SpriteId": "card",
    "SourceLevel": 71
  },
  {
    "Name": "Solar Turtle Card",
    "CardId": "Titan Turtle Sci Green",
    "Affix": "Power",
    "Slot": "Accessory",
    "Stats": "ATK: <color=#AAFF00FF>+4%</color>",
    "Source": "Solar Turtle",
    "Droprate": "50%",
    "Location": "Turtle Nexus",
    "SpriteId": "card",
    "SourceLevel": 131
  },
  {
    "Name": "Soul Card",
    "CardId": "Soul",
    "Affix": "Ethereal",
    "Slot": "Weapon",
    "Stats": "Ghost Damage: <color=#AAFF00FF>+6%</color>",
    "Source": "Soul",
    "Droprate": "50%",
    "Location": "Sanctum of Light",
    "SpriteId": "card",
    "SourceLevel": 78
  },
  {
    "Name": "Soul Mage Card",
    "CardId": "Soul Mage",
    "Affix": "Wizardry",
    "Slot": "Accessory",
    "Stats": "Cast Speed: <color=#AAFF00FF>+10%</color>",
    "Source": "Soul Mage",
    "Droprate": "50%",
    "Location": "Sanctum of Light",
    "SpriteId": "card",
    "SourceLevel": 85
  },
  {
    "Name": "Spark Drake Card",
    "CardId": "Dragon Spark",
    "Affix": "Power",
    "Slot": "Head",
    "Stats": "ATK: <color=#AAFF00FF>+4%</color>",
    "Source": "Spark Drake",
    "Droprate": "50%",
    "Location": "Demon's Maw",
    "SpriteId": "card",
    "SourceLevel": 97
  },
  {
    "Name": "Sparkit Card",
    "CardId": "Cat Meow",
    "Affix": "Shocking",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.3 Thunderbolt</color>",
    "Source": "Sparkit",
    "Droprate": "50%",
    "Location": "Forest Field 2",
    "SpriteId": "card",
    "SourceLevel": 16
  },
  {
    "Name": "Spectre Card",
    "CardId": "Gloom",
    "Affix": "Mystery",
    "Slot": "Weapon",
    "Stats": "All Stats: <color=#AAFF00FF>+1</color>\nHP: <color=#AAFF00FF>+5%</color>\nMP: <color=#AAFF00FF>+5%</color>",
    "Source": "Spectre",
    "Droprate": "50%",
    "Location": "Abyss Castle Crypt",
    "SpriteId": "card",
    "SourceLevel": 116
  },
  {
    "Name": "Spider Card",
    "CardId": "Spider",
    "Affix": "Shadow",
    "Slot": "Weapon",
    "Stats": "Shadow Step Range: <color=#AAFF00FF>+3</color>",
    "Source": "Spider",
    "Droprate": "50%",
    "Location": "Forgotten Depths 1",
    "SpriteId": "card",
    "SourceLevel": 42
  },
  {
    "Name": "Spider Robot Card",
    "CardId": "Spider Robot",
    "Affix": "Prototype",
    "Slot": "Weapon",
    "Stats": "<color=#FF9700FF>Jump Shot: <color=#AAFF00FF>Remove Knockback</color></color>\n<color=#FF9700FF>Shrapnel: <color=#AAFF00FF>Remove Knockback</color></color>",
    "Source": "Spider Robot",
    "Droprate": "50%",
    "Location": "The Forge",
    "SpriteId": "card",
    "SourceLevel": 128
  },
  {
    "Name": "Spiderling Robot Card",
    "CardId": "Spiderling Robot",
    "Affix": "Darkproof",
    "Slot": "Legs",
    "Stats": "Shadow Resistance: <color=#AAFF00FF>+15%</color>",
    "Source": "Spiderling Robot",
    "Droprate": "50%",
    "Location": "The Forge",
    "SpriteId": "card",
    "SourceLevel": 128
  },
  {
    "Name": "Spike Robot Card",
    "CardId": "Spike Robot",
    "Affix": "Rapid",
    "Slot": "Head",
    "Stats": "Attack Speed: <color=#AAFF00FF>+10%</color>",
    "Source": "Spike Robot",
    "Droprate": "50%",
    "Location": "The Forge",
    "SpriteId": "card",
    "SourceLevel": 127
  },
  {
    "Name": "Spitter Card",
    "CardId": "Plant Shooter",
    "Affix": "Poisonous",
    "Slot": "Weapon",
    "Stats": "Poison Damage: <color=#AAFF00FF>+6%</color>",
    "Source": "Spitter",
    "Droprate": "50%",
    "Location": "Swamp",
    "SpriteId": "card",
    "SourceLevel": 38
  },
  {
    "Name": "Spook Card",
    "CardId": "Spook",
    "Affix": "Unbreaking",
    "Slot": "Feet",
    "Stats": "<color=#FF9700FF>Casting cannot be interrupted.</color>",
    "Source": "Spook",
    "Droprate": "50%",
    "Location": "Sanctum of Light",
    "SpriteId": "card",
    "SourceLevel": 82
  },
  {
    "Name": "Spore Card",
    "CardId": "Spore",
    "Affix": "Vital",
    "Slot": "Shield",
    "Stats": "HP: <color=#AAFF00FF>+1% per level</color>\nVit: <color=#AAFF00FF>+1</color>",
    "Source": "Spore",
    "Droprate": "50%",
    "Location": "Windy Desert South",
    "SpriteId": "card",
    "SourceLevel": 32
  },
  {
    "Name": "Sprite Card",
    "CardId": "Butterfly Hue",
    "Affix": "Blessed",
    "Slot": "Weapon",
    "Stats": "Healing: <color=#AAFF00FF>+10%</color>",
    "Source": "Sprite",
    "Droprate": "50%",
    "Location": "Fairy Glen",
    "SpriteId": "card",
    "SourceLevel": 31
  },
  {
    "Name": "Sprout Card",
    "CardId": "Sprout",
    "Affix": "Splintering",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.3 Earthbolt</color>",
    "Source": "Sprout",
    "Droprate": "50%",
    "Location": "Sunny Meadows 2",
    "SpriteId": "card",
    "SourceLevel": 9
  },
  {
    "Name": "Squidling Card",
    "CardId": "Squid Baby",
    "Affix": "Focus",
    "Slot": "Head",
    "Stats": "MP: <color=#AAFF00FF>+10 per level</color>\nMP: <color=#AAFF00FF>+1% per level</color>",
    "Source": "Squidling",
    "Droprate": "50%",
    "Location": "Sunken Depths",
    "SpriteId": "card",
    "SourceLevel": 102
  },
  {
    "Name": "Starflake Card",
    "CardId": "Ice Starflake A",
    "Affix": "Arcanum",
    "Slot": "Head",
    "Stats": "MP Cost: <color=#AAFF00FF>-15%</color>",
    "Source": "Starflake",
    "Droprate": "50%",
    "Location": "Starfall Tundra",
    "SpriteId": "card",
    "SourceLevel": 133
  },
  {
    "Name": "Stone Golem Card",
    "CardId": "Golem Earth",
    "Affix": "Stone",
    "Slot": "Chest",
    "Stats": "DEF: <color=#AAFF00FF>+15%</color>",
    "Source": "Stone Golem",
    "Droprate": "50%",
    "Location": "Windy Desert South",
    "SpriteId": "card",
    "SourceLevel": 35
  },
  {
    "Name": "Storm Turtle Card",
    "CardId": "Titan Turtle Sci Pink",
    "Affix": "Lightning",
    "Slot": "Weapon",
    "Stats": "Chain Lightning Chains: <color=#AAFF00FF>+2</color>",
    "Source": "Storm Turtle",
    "Droprate": "50%",
    "Location": "Turtle Nexus",
    "SpriteId": "card",
    "SourceLevel": 135
  },
  {
    "Name": "Stormcoil Card",
    "CardId": "Tentacles Robot",
    "Affix": "Swift",
    "Slot": "Feet",
    "Stats": "Movement Speed: <color=#AAFF00FF>+20%</color>\nMP: <color=#FF0073FF>-20%</color>",
    "Source": "Stormcoil",
    "Droprate": "50%",
    "Location": "Night Garden",
    "SpriteId": "card",
    "SourceLevel": 127
  },
  {
    "Name": "Stormjelly Card",
    "CardId": "Jellyfish Robot",
    "Affix": "Energy",
    "Slot": "Chest",
    "Stats": "MP Regen: <color=#AAFF00FF>+50%</color>\nHP Regen: <color=#FF0073FF>-50%</color>",
    "Source": "Stormjelly",
    "Droprate": "50%",
    "Location": "Dark Forest",
    "SpriteId": "card",
    "SourceLevel": 91
  },
  {
    "Name": "Stormstinger Card",
    "CardId": "Stinger Robot",
    "Affix": "Energy",
    "Slot": "Feet",
    "Stats": "MP Regen: <color=#AAFF00FF>+100%</color>\nMP: <color=#FF0073FF>-50%</color>",
    "Source": "Stormstinger",
    "Droprate": "50%",
    "Location": "Dark Forest",
    "SpriteId": "card",
    "SourceLevel": 94
  },
  {
    "Name": "Suphara Card",
    "CardId": "Spider Queen Robot",
    "Affix": "Unnatural",
    "Slot": "Weapon",
    "Stats": "Holy Damage: <color=#AAFF00FF>+6%</color>\nShadow Damage: <color=#AAFF00FF>+6%</color>\nPoison Damage: <color=#AAFF00FF>+6%</color>\nUndead Damage: <color=#AAFF00FF>+6%</color>",
    "Source": "Suphara",
    "Droprate": "300%",
    "Location": "The Forge",
    "SpriteId": "card_gold",
    "SourceLevel": 135
  },
  {
    "Name": "Sword Mimic Card",
    "CardId": "Mimic Sword",
    "Affix": "Str",
    "Slot": "Accessory",
    "Stats": "Str: <color=#AAFF00FF>+3</color>",
    "Source": "Sword Mimic",
    "Droprate": "50%",
    "Location": "Abyss Castle Keep",
    "SpriteId": "card",
    "SourceLevel": 114
  },
  {
    "Name": "Sylvie Card",
    "CardId": "Sunflower Fairy",
    "Affix": "Blessed",
    "Slot": "Legs",
    "Stats": "Healing: <color=#AAFF00FF>+15%</color>",
    "Source": "Sylvie",
    "Droprate": "50%",
    "Location": "Fairy Glen",
    "SpriteId": "card",
    "SourceLevel": 34
  },
  {
    "Name": "Toadstool Card",
    "CardId": "Toadstool",
    "Affix": "Waterproof",
    "Slot": "Shield",
    "Stats": "Water Resistance: <color=#AAFF00FF>+25%</color>",
    "Source": "Toadstool",
    "Droprate": "50%",
    "Location": "Lake Field",
    "SpriteId": "card",
    "SourceLevel": 30
  },
  {
    "Name": "Trap Mimic Card",
    "CardId": "Mimic Living Trap",
    "Affix": "Agi",
    "Slot": "Accessory",
    "Stats": "Agi: <color=#AAFF00FF>+3</color>",
    "Source": "Trap Mimic",
    "Droprate": "50%",
    "Location": "Abyss Castle Dungeon",
    "SpriteId": "card",
    "SourceLevel": 106
  },
  {
    "Name": "Turtle Baby Card",
    "CardId": "Turtle",
    "Affix": "Steadfast",
    "Slot": "Shield",
    "Stats": "Resistance to Stun: <color=#AAFF00FF>+50%</color>",
    "Source": "Turtle Baby",
    "Droprate": "50%",
    "Location": "Stormreef Isle",
    "SpriteId": "card",
    "SourceLevel": 61
  },
  {
    "Name": "Turtle Champion Card",
    "CardId": "Turtle King",
    "Affix": "Overload",
    "Slot": "Head",
    "Stats": "Elemental Overload Damage: <color=#AAFF00FF>+15% + 2% per level</color>\nElemental Overload Mana Cost: <color=#FF0073FF>+100%</color>",
    "Source": "Turtle Champion",
    "Droprate": "300%",
    "Location": "Turtle Nexus",
    "SpriteId": "card_gold",
    "SourceLevel": 140
  },
  {
    "Name": "Twinkle Card",
    "CardId": "Alien Twinkle",
    "Affix": "Blessed",
    "Slot": "Accessory",
    "Stats": "Healing: <color=#AAFF00FF>+10%</color>",
    "Source": "Twinkle",
    "Droprate": "50%",
    "Location": "Starfall Tundra",
    "SpriteId": "card",
    "SourceLevel": 135
  },
  {
    "Name": "Umbral Acolyte Card",
    "CardId": "NightmareAcolyte",
    "Affix": "Acolyte",
    "Slot": "Accessory",
    "Stats": "Status Duration: <color=#AAFF00FF>+10%</color>",
    "Source": "Umbral Acolyte",
    "Droprate": "50%",
    "Location": "Dark Fortress Lv1",
    "SpriteId": "card",
    "SourceLevel": 136
  },
  {
    "Name": "Umbral Berserker Card",
    "CardId": "NightmareBerserker",
    "Affix": "Berserker",
    "Slot": "Head",
    "Stats": "DEF Pierce: <color=#AAFF00FF>+2% per level</color>",
    "Source": "Umbral Berserker",
    "Droprate": "50%",
    "Location": "Dark Fortress Lv2",
    "SpriteId": "card",
    "SourceLevel": 148
  },
  {
    "Name": "Umbral Gunslinger Card",
    "CardId": "NightmareGunslinger",
    "Affix": "Gunslinger",
    "Slot": "Head",
    "Stats": "Perfect Hit: <color=#AAFF00FF>+3% per level</color>\nRanged Damage: <color=#AAFF00FF>+1% per level</color>\nRange: <color=#AAFF00FF>+1</color>",
    "Source": "Umbral Gunslinger",
    "Droprate": "50%",
    "Location": "Dark Fortress Lv2",
    "SpriteId": "card",
    "SourceLevel": 147
  },
  {
    "Name": "Umbral Knight Card",
    "CardId": "NightmareKnight",
    "Affix": "Knight",
    "Slot": "Accessory",
    "Stats": "Threat Generation: <color=#AAFF00FF>+25% per level</color>",
    "Source": "Umbral Knight",
    "Droprate": "50%",
    "Location": "Dark Fortress Lv1",
    "SpriteId": "card",
    "SourceLevel": 140
  },
  {
    "Name": "Umbral Mage Card",
    "CardId": "NightmareMage",
    "Affix": "Mage",
    "Slot": "Accessory",
    "Stats": "Matk: <color=#AAFF00FF>+5</color>\nMDEF Pierce: <color=#AAFF00FF>+5%</color>",
    "Source": "Umbral Mage",
    "Droprate": "50%",
    "Location": "Dark Fortress Lv1",
    "SpriteId": "card",
    "SourceLevel": 137
  },
  {
    "Name": "Umbral Necromancer Card",
    "CardId": "NightmareNecromancer",
    "Affix": "Necromancer",
    "Slot": "Head",
    "Stats": "MDEF Pierce: <color=#AAFF00FF>+2% per level</color>",
    "Source": "Umbral Necromancer",
    "Droprate": "50%",
    "Location": "Dark Fortress Lv2",
    "SpriteId": "card",
    "SourceLevel": 149
  },
  {
    "Name": "Umbral Paladin Card",
    "CardId": "NightmarePaladin",
    "Affix": "Paladin",
    "Slot": "Head",
    "Stats": "Final Damage Reduction: <color=#AAFF00FF>+1% per level</color>\nMP: <color=#FF0073FF>-2% per level</color>",
    "Source": "Umbral Paladin",
    "Droprate": "50%",
    "Location": "Dark Fortress Lv2",
    "SpriteId": "card",
    "SourceLevel": 150
  },
  {
    "Name": "Umbral Priest Card",
    "CardId": "NightmarePriest",
    "Affix": "Priest",
    "Slot": "Head",
    "Stats": "Healing: <color=#AAFF00FF>+2% per level</color>\nMP Cost: <color=#AAFF00FF>-2% per level</color>",
    "Source": "Umbral Priest",
    "Droprate": "50%",
    "Location": "Dark Fortress Lv2",
    "SpriteId": "card",
    "SourceLevel": 146
  },
  {
    "Name": "Umbral Rogue Card",
    "CardId": "NightmareRogue",
    "Affix": "Rogue",
    "Slot": "Accessory",
    "Stats": "Attack Speed: <color=#AAFF00FF>+5%</color>\nTotal FLEE: <color=#AAFF00FF>+5%</color>",
    "Source": "Umbral Rogue",
    "Droprate": "50%",
    "Location": "Dark Fortress Lv1",
    "SpriteId": "card",
    "SourceLevel": 137
  },
  {
    "Name": "Umbral Scout Card",
    "CardId": "NightmareScout",
    "Affix": "Scout",
    "Slot": "Accessory",
    "Stats": "Atk: <color=#AAFF00FF>+5</color>\nTotal HIT: <color=#AAFF00FF>+5%</color>",
    "Source": "Umbral Scout",
    "Droprate": "50%",
    "Location": "Dark Fortress Lv1",
    "SpriteId": "card",
    "SourceLevel": 138
  },
  {
    "Name": "Umbral Shinobi Card",
    "CardId": "NightmareShinobi",
    "Affix": "Shinobi",
    "Slot": "Head",
    "Stats": "Cooldown Recovery: <color=#AAFF00FF>+1% per level</color>\nMP Cost: <color=#FF0073FF>+2% per level</color>",
    "Source": "Umbral Shinobi",
    "Droprate": "50%",
    "Location": "Dark Fortress Lv2",
    "SpriteId": "card",
    "SourceLevel": 149
  },
  {
    "Name": "Umbral Summoner Card",
    "CardId": "NightmareSummoner",
    "Affix": "Summoner",
    "Slot": "Accessory",
    "Stats": "Summon All Stats: <color=#AAFF00FF>+5</color>",
    "Source": "Umbral Summoner",
    "Droprate": "50%",
    "Location": "Dark Fortress Lv1",
    "SpriteId": "card",
    "SourceLevel": 139
  },
  {
    "Name": "Umbral Warrior Card",
    "CardId": "NightmareWarrior",
    "Affix": "Warrior",
    "Slot": "Accessory",
    "Stats": "CRIT Damage: <color=#AAFF00FF>+5%</color>\nDEF Pierce: <color=#AAFF00FF>+5%</color>",
    "Source": "Umbral Warrior",
    "Droprate": "50%",
    "Location": "Dark Fortress Lv1",
    "SpriteId": "card",
    "SourceLevel": 139
  },
  {
    "Name": "Umbral Wizard Card",
    "CardId": "NightmareWizard",
    "Affix": "Wizard",
    "Slot": "Head",
    "Stats": "Magic Damage: <color=#AAFF00FF>+1% per level</color>\nCast Range: <color=#AAFF00FF>+2</color>",
    "Source": "Umbral Wizard",
    "Droprate": "50%",
    "Location": "Dark Fortress Lv2",
    "SpriteId": "card",
    "SourceLevel": 147
  },
  {
    "Name": "Vanilla Ice Card",
    "CardId": "Ice Starflake B",
    "Affix": "Energy",
    "Slot": "Legs",
    "Stats": "MP Regen: <color=#AAFF00FF>+25%</color>\nMP Cost: <color=#AAFF00FF>-10%</color>",
    "Source": "Vanilla Ice",
    "Droprate": "50%",
    "Location": "Starfall Tundra",
    "SpriteId": "card",
    "SourceLevel": 133
  },
  {
    "Name": "Venom Bud Card",
    "CardId": "Bud",
    "Affix": "Fleet",
    "Slot": "Head",
    "Stats": "Movement Speed: <color=#AAFF00FF>+10%</color>\nHP: <color=#FF0073FF>-5%</color>\nMP: <color=#FF0073FF>-5%</color>",
    "Source": "Venom Bud",
    "Droprate": "50%",
    "Location": "Underground Cavern",
    "SpriteId": "card",
    "SourceLevel": 86
  },
  {
    "Name": "Verdant Terrapin Card",
    "CardId": "Turtle Monster Green",
    "Affix": "Purifying",
    "Slot": "Head",
    "Stats": "Resistance to Decay: <color=#AAFF00FF>+50%</color>",
    "Source": "Verdant Terrapin",
    "Droprate": "50%",
    "Location": "Stormreef Isle",
    "SpriteId": "card",
    "SourceLevel": 63
  },
  {
    "Name": "Vespa Card",
    "CardId": "Sting",
    "Affix": "Frenzy",
    "Slot": "Head",
    "Stats": "Attack Speed Limit: <color=#AAFF00FF>+1</color>",
    "Source": "Vespa",
    "Droprate": "300%",
    "Location": "Sunny Meadows 2",
    "SpriteId": "card_gold",
    "SourceLevel": 15
  },
  {
    "Name": "Vinecrawler Card",
    "CardId": "Plant Worm",
    "Affix": "Status",
    "Slot": "Legs",
    "Stats": "Status Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Vinecrawler",
    "Droprate": "50%",
    "Location": "Swamp Wilderness",
    "SpriteId": "card",
    "SourceLevel": 70
  },
  {
    "Name": "Violet Octopus Card",
    "CardId": "Octopus King Purple",
    "Affix": "Ranged",
    "Slot": "Legs",
    "Stats": "Ranged Damage: <color=#AAFF00FF>+5%</color>",
    "Source": "Violet Octopus",
    "Droprate": "50%",
    "Location": "Turtle Nexus",
    "SpriteId": "card",
    "SourceLevel": 133
  },
  {
    "Name": "Viper Card",
    "CardId": "Snake",
    "Affix": "Venomous",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.3 Venom Strike</color>",
    "Source": "Viper",
    "Droprate": "50%",
    "Location": "Forgotten Depths 2",
    "SpriteId": "card",
    "SourceLevel": 47
  },
  {
    "Name": "Voidgazer Card",
    "CardId": "Alien One Eye",
    "Affix": "Unbreaking",
    "Slot": "Head",
    "Stats": "<color=#FF9700FF>Casting cannot be interrupted.</color>",
    "Source": "Voidgazer",
    "Droprate": "50%",
    "Location": "Night Garden",
    "SpriteId": "card",
    "SourceLevel": 126
  },
  {
    "Name": "Voidspawn Card",
    "CardId": "Alien Cyclops",
    "Affix": "Gaze",
    "Slot": "Head",
    "Stats": "Grants <color=#AAFF00FF>Lv.1 True Sight</color>",
    "Source": "Voidspawn",
    "Droprate": "50%",
    "Location": "Dark Forest",
    "SpriteId": "card",
    "SourceLevel": 93
  },
  {
    "Name": "Voltpaw Card",
    "CardId": "Cat Lightning",
    "Affix": "Windproof",
    "Slot": "Shield",
    "Stats": "Wind Resistance: <color=#AAFF00FF>+25%</color>",
    "Source": "Voltpaw",
    "Droprate": "50%",
    "Location": "Windy Desert",
    "SpriteId": "card",
    "SourceLevel": 29
  },
  {
    "Name": "Vorpal Hare Card",
    "CardId": "Hare",
    "Affix": "Fleet",
    "Slot": "Feet",
    "Stats": "Movement Speed: <color=#AAFF00FF>+20%</color>",
    "Source": "Vorpal Hare",
    "Droprate": "300%",
    "Location": "Bunny Woods",
    "SpriteId": "card_gold",
    "SourceLevel": 30
  },
  {
    "Name": "Widow Card",
    "CardId": "Spider Toxin",
    "Affix": "Purging",
    "Slot": "Weapon",
    "Stats": "Damage versus Poison Enemies: <color=#AAFF00FF>+10%</color>",
    "Source": "Widow",
    "Droprate": "50%",
    "Location": "Forgotten Depths 1",
    "SpriteId": "card",
    "SourceLevel": 44
  },
  {
    "Name": "Wight Card",
    "CardId": "Death",
    "Affix": "Ethereal",
    "Slot": "Legs",
    "Stats": "Ghost Resistance: <color=#AAFF00FF>+15%</color>",
    "Source": "Wight",
    "Droprate": "50%",
    "Location": "Abyss Castle Keep",
    "SpriteId": "card",
    "SourceLevel": 112
  },
  {
    "Name": "Wind Mage Card",
    "CardId": "Wind Mage",
    "Affix": "Storm",
    "Slot": "Weapon",
    "Stats": "<color=#FF9700FF>Thunder Storm autocasts Static Field</color>",
    "Source": "Wind Mage",
    "Droprate": "50%",
    "Location": "Windy Desert",
    "SpriteId": "card",
    "SourceLevel": 30
  },
  {
    "Name": "Wolf Card",
    "CardId": "Wolf",
    "Affix": "Darkproof",
    "Slot": "Shield",
    "Stats": "Shadow Resistance: <color=#AAFF00FF>+25%</color>",
    "Source": "Wolf",
    "Droprate": "50%",
    "Location": "Festering Woods 2",
    "SpriteId": "card",
    "SourceLevel": 30
  },
  {
    "Name": "Wolf Cub Card",
    "CardId": "Wolf Pup",
    "Affix": "Umbral",
    "Slot": "Weapon",
    "Stats": "Shadow Damage: <color=#AAFF00FF>+6%</color>",
    "Source": "Wolf Cub",
    "Droprate": "50%",
    "Location": "Festering Woods 2",
    "SpriteId": "card",
    "SourceLevel": 26
  },
  {
    "Name": "Worm Card",
    "CardId": "Worm",
    "Affix": "Purity",
    "Slot": "Legs",
    "Stats": "Undead Resistance: <color=#AAFF00FF>+15%</color>",
    "Source": "Worm",
    "Droprate": "50%",
    "Location": "Swamp Wilderness",
    "SpriteId": "card",
    "SourceLevel": 68
  },
  {
    "Name": "Wraith King Card",
    "CardId": "Wraith",
    "Affix": "Frenzied",
    "Slot": "Head",
    "Stats": "Attack Speed Limit: <color=#AAFF00FF>+2</color>\nHP: <color=#FF0073FF>-25%</color>\nMP: <color=#FF0073FF>-25%</color>",
    "Source": "Wraith King",
    "Droprate": "300%",
    "Location": "Abyss Castle Crypt",
    "SpriteId": "card_gold",
    "SourceLevel": 125
  },
  {
    "Name": "Zombie Goblin Card",
    "CardId": "Zombie Goblin Minion",
    "Affix": "Grave",
    "Slot": "Weapon",
    "Stats": "Damage versus Undead Enemies: <color=#AAFF00FF>+10%</color>",
    "Source": "Zombie Goblin",
    "Droprate": "50%",
    "Location": "Goblin Cave 1",
    "SpriteId": "card",
    "SourceLevel": 53
  },
  {
    "Name": "Zombie Grunt Card",
    "CardId": "Zombie Goblin Soldier",
    "Affix": "Undying",
    "Slot": "Shield",
    "Stats": "HP: <color=#AAFF00FF>+25%</color>\nHealing Received: <color=#FF0073FF>-50%</color>",
    "Source": "Zombie Grunt",
    "Droprate": "50%",
    "Location": "Goblin Cave 1",
    "SpriteId": "card",
    "SourceLevel": 55
  },
  {
    "Name": "Zombie Orc Card",
    "CardId": "Zombie Goblin Giant",
    "Affix": "Occult",
    "Slot": "Feet",
    "Stats": "Matk: <color=#AAFF00FF>+5</color>",
    "Source": "Zombie Orc",
    "Droprate": "50%",
    "Location": "Goblin Cave 2",
    "SpriteId": "card",
    "SourceLevel": 58
  },
  {
    "Name": "Zombie Orc Lord Card",
    "CardId": "Zombie Goblin King",
    "Affix": "Undead",
    "Slot": "Chest",
    "Stats": "<color=#FF9700FF>Convert to <sprite name=undead> <color=#C85AE0FF>Undead</color> element\n<color=#FF0073FF>Healing effects are converted to damage.</color>\n<color=#FF9700FF>Immune to Slow</color>\n<color=#FF9700FF>Immune to Curse</color>\n<color=#FF9700FF>Immune to Frozen</color>\n<color=#FF9700FF>Immune to Bleeding</color></color>",
    "Source": "Zombie Orc Lord",
    "Droprate": "300%",
    "Location": "Goblin Cave 2",
    "SpriteId": "card_gold",
    "SourceLevel": 65
  }
];
